### ISSUE TITLE
Dowlink for Class A

### ISSUE THREAD

**Issue by kammyy** [gotthardp/lorawan-server#106]
While sending the downlink message for Class A devices, the json recommended is -

{"devaddr":"11223344", "data":"0026BF08BD03CD35000000000000FFFF", "confirmed":true}
    {"data":"00", "port":2, "time":"2017-03-04T21:05:30.2000"}

For A type device, the downlink is sent immediately after previous uplink.

1. Why do i need to specify "the time" in the json above?
2. How am i supposed to know the time when the next uplink from the A type device will come?

Thanks

**Comment by gotthardp** [comment]
Hello. I hope I didn't say anywhere this was a Class A example. You're right, you cannot know the uplink time-- the "time" parameter is for Class C only (as indicated [here](https://github.com/gotthardp/lorawan-server/blob/master/doc/JSON.md)).

**Comment by kammyy** [comment]
It means that the jason for class A is:
{"devaddr":"11223344", "data":"0026BF08BD03CD35000000000000FFFF", "confirmed":true}

What about port in class A?

Also,for class C: What is the point of having time . Isn't the message sent to device immediately by default?

**Comment by gotthardp** [comment]
Correct.

Have a look in the documentation of the `port` parameter: *If not specified for Class A, the port number of last uplink will be used. Mandatory for Class C.*

The `time` is to distinguish between Class A and Class C downlinks. Even class C device can do Class A downlinks.

**Comment by kammyy** [comment]
Understood.

Thanks Petr.

**Comment by gotthardp** [comment]
Glad I could help :) I also clarified the documentation.
