### ISSUE TITLE
First run database missing

### ISSUE THREAD

**Issue by kazi93** [gotthardp/lorawan-server#111]
@gotthardp As per the documenation : The server run-time files are automatically created during the first run. It includes the database in Mnesia.lorawan@* and log files. 
However, I cannot see Mnesia.lorawan@* and log files. 

OS: Debian 8 (Jessie) (64 bits)

root@vps416657:/usr/lib/lorawan-server# ls
bin  lib  releases
root@vps416657:/usr/lib/lorawan-server# systemctl status lorawan-server -l
● lorawan-server.service - LoRaWAN Server
   Loaded: loaded (/lib/systemd/system/lorawan-server.service; disabled)
   Active: active (running) since Tue 2017-05-30 14:40:57 CEST; 25s ago
  Process: 17585 ExecStop=/usr/lib/lorawan-server/bin/lorawanctl stop (code=exited, status=1/FAILURE)
  Process: 17602 ExecStart=/usr/lib/lorawan-server/bin/lorawan-daemon (code=exited, status=0/SUCCESS)
 Main PID: 17603 (su)
   CGroup: /system.slice/lorawan-server.service
           ‣ 17603 su lorawan -s /bin/sh -c /usr/lib/lorawan-server/bin/lorawan-server

May 30 14:40:58 vps416657.ovh.net lorawan-daemon[17602]: 14:40:58.181 [debug] Supervisor {<0.223.0>,ranch_acceptors_sup} started ranch_acceptor:start_link(#Port<0.5340>, ranch_tcp, <0.222.0>) at pid <0.233.0>
May 30 14:40:58 vps416657.ovh.net lorawan-daemon[17602]: 14:40:58.181 [debug] Supervisor {<0.221.0>,ranch_listener_sup} started ranch_acceptors_sup:start_link(http, 10, ranch_tcp, [{connection_type,supervisor},{port,8080}]) at pid <0.223.0>
May 30 14:40:58 vps416657.ovh.net lorawan-daemon[17602]: 14:40:58.182 [debug] Supervisor ranch_sup started ranch_listener_sup:start_link(http, 10, ranch_tcp, [{connection_type,supervisor},{port,8080}], cowboy_clear, #{connection_type => supervisor,env => #{dispatch => [{'_',[],[{[<<"applications">>],[],lorawan_admin_applications,...},...]}]}}) at pid <0.221.0>
May 30 14:40:58 vps416657.ovh.net lorawan-daemon[17602]: 14:40:58.185 [info] server started
May 30 14:40:58 vps416657.ovh.net lorawan-daemon[17602]: 14:40:58.191 [debug] Supervisor lorawan_sup started lorawan_gw_router:start_link() at pid <0.236.0>
May 30 14:40:58 vps416657.ovh.net lorawan-daemon[17602]: 14:40:58.193 [debug] Supervisor lorawan_sup started lorawan_gw_forwarder:start_link([{port,1700}]) at pid <0.237.0>
May 30 14:40:58 vps416657.ovh.net lorawan-daemon[17602]: 14:40:58.194 [debug] Supervisor lorawan_sup started lorawan_connector_sup:start_link() at pid <0.238.0>
May 30 14:40:58 vps416657.ovh.net lorawan-daemon[17602]: 14:40:58.196 [debug] Supervisor lorawan_sup started lorawan_connector_factory:start_link() at pid <0.239.0>
May 30 14:40:58 vps416657.ovh.net lorawan-daemon[17602]: 14:40:58.196 [info] Application lorawan_server started on node lorawan@vps416657
May 30 14:40:58 vps416657.ovh.net lorawan-daemon[17602]: 14:40:58.388 [debug] Lager installed handler lager_backend_throttle into lager_event

**Comment by gotthardp** [comment]
Have you searched in `/var/lib/lorawan-server`?
