### ISSUE TITLE
time to receive !!

### ISSUE THREAD

**Issue by YousseMes** [gotthardp/lorawan-server#112]
Hi !
thank you for your Job !
I have just one probleme why I receive date every minute and not in really time
please thear's some configuration to fix that ?
![issu](https://cloud.githubusercontent.com/assets/28385566/26590308/77553d22-455a-11e7-80cf-02965afd0280.JPG)

**Comment by gotthardp** [comment]
Hi. I am not sure I understand the issue. The device sends the data. It's upto the device to decide when to send data. What do you expect to see there?

**Comment by YousseMes** [comment]
I want to receive in server at real time

**Comment by gotthardp** [comment]
LoRaWAN is not intended for real-time operations. The devices have to obey duty cycle regulations, so they have to wait few seconds before sending again.

**Comment by Ankitjd18** [comment]
Hi,
Below is the JSON payload we receive on uplink
`{"data":"0E5E3345395B6D84","datetime":"2017-06-01T09:33:18Z","devaddr":"0040D0E3","fcnt":270,"group":"testing","last_lost":false,"port":2,"rxq":{"codr":"4/5","datr":"SF12BW125","freq":865.403,"lsnr":9.2,"rssi":-27,"time":"2017-06-01T09:34:33.308854Z","tmst":1530369108},"shall_reply":true}`

Here we can see fields as "datetime", "time", which has a constant difference of 1 min 16 sec. What are these two "time" fields? Also, what is `tmst` field in the payload?

**Comment by gotthardp** [comment]
Hi. The `rxq` parameters correspond to what the gateway set. See https://github.com/Lora-net/packet_forwarder/blob/master/PROTOCOL.TXT. The `datetime` is a server time, whereas the `time` is GPS time.

**Comment by gotthardp** [comment]
Will update the documentation accordingly.
