### ISSUE TITLE
gateway registration failed by web form: unknown_mac in Dashboard

### ISSUE THREAD

**Issue by kazi93** [gotthardp/lorawan-server#113]
@gotthardp I failed to add the gateways in the web form(Infrastructure >Gateways List): When I click the submit button it simply does not work. In the Dashboard and debug console I have the below :
Last Occurred	Entity	Eid	Text
2017-05-31 20:06:16	gateway	B827EBFFFF5E0AAE	unknown_mac
2017-05-31 20:06:04	gateway	B827EBFFFFC53182	unknown_mac
2017-05-31 20:05:46	gateway	B827EBFFFF5E0AAE	{uplinks_lost,1}
2017-05-31 20:05:04	gateway	B827EBFFFFC53182	{uplinks_lost,1}

root@vps416657:~# systemctl status lorawan-server -l
● lorawan-server.service - LoRaWAN Server
   Loaded: loaded (/lib/systemd/system/lorawan-server.service; disabled)
   Active: active (running) since Tue 2017-05-30 14:40:57 CEST; 1 day 5h ago
  Process: 17585 ExecStop=/usr/lib/lorawan-server/bin/lorawanctl stop (code=exited, status=1/FAILURE)
  Process: 17602 ExecStart=/usr/lib/lorawan-server/bin/lorawan-daemon (code=exited, status=0/SUCCESS)
 Main PID: 17603 (su)
   CGroup: /system.slice/lorawan-server.service
           ‣ 17603 su lorawan -s /bin/sh -c /usr/lib/lorawan-server/bin/lorawan-server

May 31 20:16:04 vps416657.ovh.net lorawan-daemon[17602]: 20:16:04.379 [warning] gateway B827EBFFFFC53182 {uplinks_lost,1}
May 31 20:16:04 vps416657.ovh.net lorawan-daemon[17602]: 20:16:04.379 [error] gateway B827EBFFFFC53182 unknown_mac
May 31 20:16:16 vps416657.ovh.net lorawan-daemon[17602]: 20:16:16.391 [error] gateway B827EBFFFF5E0AAE unknown_mac
May 31 20:16:20 vps416657.ovh.net lorawan-daemon[17602]: 20:16:20.474 [error] gateway B827EBFFFF5E0AAE unknown_mac
May 31 20:16:34 vps416657.ovh.net lorawan-daemon[17602]: 20:16:34.375 [error] gateway B827EBFFFFC53182 unknown_mac
May 31 20:16:34 vps416657.ovh.net lorawan-daemon[17602]: 20:16:34.377 [error] gateway B827EBFFFFC53182 unknown_mac
May 31 20:16:46 vps416657.ovh.net lorawan-daemon[17602]: 20:16:46.367 [warning] gateway B827EBFFFF5E0AAE {uplinks_lost,1}
May 31 20:16:46 vps416657.ovh.net lorawan-daemon[17602]: 20:16:46.368 [error] gateway B827EBFFFF5E0AAE unknown_mac
May 31 20:17:04 vps416657.ovh.net lorawan-daemon[17602]: 20:17:04.375 [error] gateway B827EBFFFFC53182 unknown_mac
May 31 20:17:04 vps416657.ovh.net lorawan-daemon[17602]: 20:17:04.378 [error] gateway B827EBFFFFC53182 unknown_mac

**Comment by gotthardp** [comment]
When the gateway is unknown, you get the unknown_mac error. This is correct.

I guess you didn't fill all fields when adding the gateway.
