### ISSUE TITLE
RX Slot used ?

### ISSUE THREAD

**Issue by kammyy** [gotthardp/lorawan-server#121]
Which RX slot is used to send ACK for confirmed uplink message for A type device?

The "TX Window" selection, on the device register page, : Is it applicable for A type device or C Type device or both?

Does the "TX Window" affects the RX slot used for sending ACK for confirmed uplink for A type device?

Thanks

**Comment by gotthardp** [comment]
The Tx Window affects all. There is one algorithm for everything.

**Comment by kammyy** [comment]
I am missing a lot of ACK messages when sending confirmed uplinks from A type device. What could be wrong?  

The same device did not missed ACK from server when they were configured a class C.

**Comment by gotthardp** [comment]
What tx window settings you use?

**Comment by kammyy** [comment]
Currently i have set it to RX1.

What should i use?

**Comment by kammyy** [comment]
If i set it to Auto, what is the logic followed in selecting between two slots?

**Comment by gotthardp** [comment]
Try RX2, please. "Auto" is determined based on how fast the application module responds. It usually uses RX1.

**Comment by gotthardp** [comment]
Does the issue persist, or may I close this?
