### ISSUE TITLE
Adding new devices using REST api

### ISSUE THREAD

**Issue by Sviests** [gotthardp/lorawan-server#129]
Is the functionality to add devices using the provided REST api available? I see that there is a POST method provided for the /devices resource but no example on the data needed to provide...

**Comment by gotthardp** [comment]
Yes, it is. I was too lazy to provide an example. HTTP GET some existing device to see what parameters are there and then see in the web-admin what parameters are optional (most of them). There is 1:1 mapping between the REST API and the web admin, so you can safely omit all optional ones.

**Comment by Sviests** [comment]
Great news! Thanks!
