### ISSUE TITLE
mqqt solution !

### ISSUE THREAD

**Issue by YousseMes** [gotthardp/lorawan-server#130]
hi 👍 
I thanks you for your good job  , for this moment i receive  trames but
i have just one probleme how to use mqqt and client for uplink 
can you help me please

**Comment by gotthardp** [comment]
Hello. Did you try to follow the https://github.com/gotthardp/lorawan-server/blob/master/doc/Integration.md guide? How far did you get?

**Comment by YousseMes** [comment]
oooh !!  
Im sorry i don't see that thank you again 
good job gotthardp 🥇🥇🥇🥇🥇
