### ISSUE TITLE
mqtt downlink 

### ISSUE THREAD

**Issue by YousseMes** [gotthardp/lorawan-server#132]
can you please tell me how i can send a downlink , I use mosquitto it work good by testinf sub and pub 
when i send data i have this problem :/

![image](https://user-images.githubusercontent.com/28385566/27229202-f086d5a4-52aa-11e7-8662-913c83e90064.png)
![image](https://user-images.githubusercontent.com/28385566/27229235-20d2d6b8-52ab-11e7-996b-6b42010e494b.png)
![image](https://user-images.githubusercontent.com/28385566/27229258-387000a2-52ab-11e7-86b7-b6d5422a961e.png)
![image](https://user-images.githubusercontent.com/28385566/27229299-60dc78cc-52ab-11e7-9fed-8d16f44e5a36.png)

**Comment by YousseMes** [comment]
also I have a message in server lorawan [warning] ClientID is NULL!

**Comment by gotthardp** [comment]
Could you try removing the (unnecessary) spaces between JSON fields?

The `[warning] ClientID is NULL!` is harmless. You can fix it by specifying some (whatever) ClientID for the connector.

**Comment by YousseMes** [comment]
yes I made it but i can't always make a downlink :/

**Comment by YousseMes** [comment]
![image](https://user-images.githubusercontent.com/28385566/27274601-4e2af0e8-54d4-11e7-99f7-dd8c5b5d8a47.png)

i see that it was a downlink fonction but in the node nothing 
![image](https://user-images.githubusercontent.com/28385566/27274632-6acc02a0-54d4-11e7-88ac-779c7fc581d1.png)

**Comment by gotthardp** [comment]
what exactly was the command you used? the devaddr has to match, obviously

**Comment by YousseMes** [comment]
mosquitto_pub -h 127.0.0.1 -p 1883 -t 'in/260118B3' -m '{"devaddr":"260118B3","data":"00","confirmed":true,"port":1,"time":"immediately"}'

**Comment by gotthardp** [comment]
try without "time: immediately" please

**Comment by YousseMes** [comment]
always the same problem  the message sent but i can't see downlink in the node 
please how can i see the log ?

**Comment by gotthardp** [comment]
https://github.com/gotthardp/lorawan-server/blob/master/doc/Troubleshooting.md

**Comment by YousseMes** [comment]
![image](https://user-images.githubusercontent.com/28385566/27278530-f34a918e-54e1-11e7-869d-9b1738a8b684.png)
also i have this problem

**Comment by YousseMes** [comment]
i have this problem 
2017-06-19 11:50:29.083 [error] <0.263.0>@lorawan_application_backend:data_to_fields:203 Fun failed error:function_clause

**Comment by gotthardp** [comment]
This means the erlang functions for uplink/downlink parsing/building are wrong. If you post them here I can check them for you.

**Comment by YousseMes** [comment]
![image](https://user-images.githubusercontent.com/28385566/27282837-0c2316c6-54f2-11e7-82b0-15f77b8362b0.png)

**Comment by gotthardp** [comment]
And what data is the device sending?, What is on the Received Frames list?

**Comment by YousseMes** [comment]
![image](https://user-images.githubusercontent.com/28385566/27283453-ab6888fe-54f4-11e7-8f8e-55e53789b110.png)

**Comment by YousseMes** [comment]
it's some data from arduino lmic it's in hexadecimal

**Comment by gotthardp** [comment]
But the uplink parser is designed for data from Semtech Mote, which sends much more data. You have to change them, or simply remove them all and keep the field blank.

**Comment by YousseMes** [comment]
so how can i send a downlink ?

**Comment by YousseMes** [comment]
ok it's work now i used rabbitmq i can send a downlink 
i close that
