### ISSUE TITLE
CFList on Join Accept message

### ISSUE THREAD

**Issue by julien78910** [gotthardp/lorawan-server#137]
Hello gotthardp,

Sorry to bother you again but I have a question on a feature that I didn't found on this project.
It is the CFList bytes in the Join Accept message to configure the Tx channels of the LoRa modules after an OTAA.
Is it a feature that already exist or should I wait for a next version ?

I can pre-configure my LoRa modules so it is not a big deal if this feature doesn't exist. Just if it is already done, I would use it to have something more configurable.

Thanks,
Julien

**Comment by gotthardp** [comment]
Hi Julien, the CFList is not implemented. I will implement it in some of the future releases.

**Comment by gotthardp** [comment]
CFList implemented; will be in the future 0.5.0 release
