### ISSUE TITLE
Can't add a gateway after installing a server with docker

### ISSUE THREAD

**Issue by Suko** [gotthardp/lorawan-server#138]
Maybe I am missing something but I can't add a gateway after installing a server with docker tag "latest". 

EDIT:
the same problem occurs on "stable". I also tested to add a device and it worked.

Error Message:
TypeError: Cannot read property 'length' of null
    at Array.parse_bitstring (admin.js:793)
    at e.value (ng-admin.min.js:1)
    at ng-admin.min.js:1
    at Array.forEach (<anonymous>)
    at e.value (ng-admin.min.js:1)
    at e.value (ng-admin.min.js:47)
    at fn (eval at compile (ng-admin.min.js:9), <anonymous>:4:284)
    at i (ng-admin.min.js:10)
    at p.$eval (ng-admin.min.js:8)
    at p.$apply (ng-admin.min.js:8)

This function is on location admin.js:793
function parse_bitstring(value, entry) {
    if(value.length > 0)
    {
        var parts = value.split(':', 2);
        return {val: parts[0], len: +parts[1]};
    }
    else
        return null;
}

**Comment by Suko** [comment]
The same problem occurs with Docker stabile.
 
This is on location admin.js:793
function parse_bitstring(value, entry) {
    if(value.length > 0)
    {
        var parts = value.split(':', 2);
        return {val: parts[0], len: +parts[1]};
    }
    else
        return null;
}

**Comment by Suko** [comment]
Strange behavior: If I add field SubID and delete it submit works.
Posible solution:
if(value && value.length > 0)
{
var parts = value.split(':', 2);
return {val: parts[0], len: +parts[1]};
}
else
return null;
}

**Comment by gotthardp** [comment]
Oh, that's a bug. I am sorry for that.
It's been there for a while. Thanks for reporting this, I just committed the fix you suggested.

**Comment by gotthardp** [comment]
Fixed in v0.4.6
