### ISSUE TITLE
Supports confirmed data uplink and downlink

### ISSUE THREAD

**Issue by lodovico-zhu** [gotthardp/lorawan-server#14]
Hi,gotthardp

can you add some codes to support confirmed data uplink and downlink,or give me some help on how to implement this function.Thanks  a lot !!!

**Comment by gotthardp** [comment]
Hello. I think I implemented the confirmed uplink/downlink, but I have no straightforward means to test it. Could you please check if/how it works and let me know?

**Comment by lodovico-zhu** [comment]
Hi,gotthardp,thanks very much for you work!!! I have test it as soon as I get your code,with a  freq  433Mhz,and YES ! it's done very well! Thanks again!

**Comment by gotthardp** [comment]
Thanks nice to hear. Should you need anything else, just let me know.
