### ISSUE TITLE
Billing add-on

### ISSUE THREAD

**Issue by batulzii** [gotthardp/lorawan-server#142]
This server is private LoraWAN network, and it is solid enough to use for commercial purpose.
Any plan or advice third party billing add-on?

**Comment by gotthardp** [comment]
Hello. Billing is usually done by dedicated platforms based on "charging tickets" indicating that someone has consumed a certain service amount. I am not aware of any suitable open source billing system, but when you find one it should be relatively easy to generate charging tickets using any API the system supports.

**Comment by batulzii** [comment]
Thank you! Petr

**Comment by batulzii** [comment]
.
Could you advice how tire node with payment. Any flag that will be used for this purpose. Disable/ Enable

**Comment by gotthardp** [comment]
What should the flag do? I think the server should generate little JSON messages when a frame a received and another system shall process these "charging tickets" and generate invoices.

**Comment by batulzii** [comment]
got it! Thanks Petr.

**Comment by batulzii** [comment]
idea about flag was in case of customer did not pay and have to disable that node

**Comment by gotthardp** [comment]
The server has an ignore-list (under Infrastructure). You could put the device in that list.
