### ISSUE TITLE
Deduplication of gateways with long delay

### ISSUE THREAD

**Issue by gotthardp** [gotthardp/lorawan-server#147]
When we have gateways with long delays (3G connected):
 * the de-duplication timer may fire before data from all gateways are received (we see two frames in the list)
 * this unnecessarily delays the response

Refactoring of this is required to:
 * not waste time waiting for other requests (can start processing immediately)
 * decide "best gateway" just before the response is about to send
 * LinkCheckReq.GwCnt should be also populated correctly

For debugging purposes log the reception from all gateways, but **after** processing the data.

**Comment by UzixLS** [comment]
Can this make OTAA impossible in cases when device in scope of multiple gateways with significantly different pings?

**Comment by gotthardp** [comment]
I don't think so. The join request from the first (fastest) gateway will be relayed to the server and processed and then the join response will be sent through the gateway that received the best signal quality.

**Comment by gotthardp** [comment]
done in the latest devel branch
