### ISSUE TITLE
How to install server on Mac OS - documentation

### ISSUE THREAD

**Issue by Suko** [gotthardp/lorawan-server#149]
**Using the Binary Release on Mac OS**
Install Erlang, `brew install erlang`
Unpack the release.

`unzip lorawan-server-<VERSION>.zip`  
`mv lorawan-server-<VERSION> lorawan-server`
`cd lorawan-server/bin/`
`./lorawan-server`

**Add to Manual Installation**

Rebar installation on Mac OS 
On Mac OS, run command `brew install rebar`

npm, the JavaScript package manager:
On Mac OS, run command `brew install node`

**Comment by gotthardp** [comment]
Updated. Thanks!
