### ISSUE TITLE
[error] node 26011B64 {not_found,undefined}

### ISSUE THREAD

**Issue by kazi93** [gotthardp/lorawan-server#150]
I am receiving frames without problems however having the below in the debug terminal as well as "Event List" window. Note: I am using "Lora lite gateway" from IMST.

<img width="989" alt="screen shot 2017-07-07 at 17 52 57" src="https://user-images.githubusercontent.com/18202431/27965998-f3d1fb14-633d-11e7-8729-83c1d6b0ce5d.png">

**Comment by gotthardp** [comment]
This is related to a Backed connector. Looks like you have a handler, but didn't define any connector ID. Correct?

**Comment by kazi93** [comment]
Yes.
