### ISSUE TITLE
downlink_lost

### ISSUE THREAD

**Issue by YousseMes** [gotthardp/lorawan-server#152]
hi there ! 
please i don't know why i lost the downlink ,when i send  uplink i see donwlink and the node but after that i lost it without receive it :( 
![image](https://user-images.githubusercontent.com/28385566/28012352-ce29e05a-6565-11e7-9eac-e9d534635159.png)

**Comment by gotthardp** [comment]
Did you try to follow https://github.com/gotthardp/lorawan-server/blob/master/doc/Troubleshooting.md#no-downlink-frames-sent ?

**Comment by gotthardp** [comment]
I assume the issue is fixed now.
