### ISSUE TITLE
More filters in the Devices and Nodes tab

### ISSUE THREAD

**Issue by dhavalhparikh** [gotthardp/lorawan-server#153]
Hi,
This is a request for an enhancement.
Is it possible to add more filters in the **Devices** and **Nodes** tab?
It would be great to filter by **DevAddr** in the Nodes tab and **DevEUI** in the Devices tab. The current filters only allow to sort by Application and Group.

Thanks!
Dhaval

**Comment by gotthardp** [comment]
Hello. That's easy to do. I just did commit a path-- it will be included in the next release (due probably by the end of this week).

**Comment by dhavalhparikh** [comment]
@gotthardp Awesome! Thank you.
