### ISSUE TITLE
warning repeated_reset

### ISSUE THREAD

**Issue by jimibi** [gotthardp/lorawan-server#154]
Hi,

During OTAA, i receive en event: warning  repeated_reset.
What does that mean?

**Comment by gotthardp** [comment]
Hello. It meana that no frames were received since last join. It may be ok but it may be due to device error.

**Comment by jimibi** [comment]
Hi,
Yes my device stay in OTAA search While the server just saved it.
I think I have a compatibility problem.
This works well with the gateway manufacturer's server.
In ABP mode I have no problem with your server.

**Comment by gotthardp** [comment]
It could also mean that the OTAA doesn't work. See some hints here: https://github.com/gotthardp/lorawan-server/blob/master/doc/Troubleshooting.md#no-downlink-frames-sent
