### ISSUE TITLE
sensor re-join bugginess

### ISSUE THREAD

**Issue by SayreBlades** [gotthardp/lorawan-server#156]
We are testing a scenario whereby our sensor is re-joining the network, but prior to the re-join the sensor's appeui has been changed.  We suspected this should be rejected by LNS but it is not.

Even after deletion of the original device and node within LNS, and then re-creating the device with original appeui/deveui, the sensor rejoin is successful.  This seems to be invalid behavior.

Here is a screen shot if that helps (sensitive information F'd out).  We are using OTAA.
![screen shot 2017-07-12 at 11 33 07 am](https://user-images.githubusercontent.com/748161/28125878-ea84d30e-66f5-11e7-98d6-a6c44ef7d001.png)

**Comment by gotthardp** [comment]
The AppEUI is not used in the server. Shall it be?

**Comment by SayreBlades** [comment]
FYI, it seems this behavior isnt actually particular to a re-join scenario.  On the first join our sensor was able to successfully join with inconsistent appeui's.

**Comment by SayreBlades** [comment]
Hi Gotthard, Im actually not sure if it should be.  Let us review the lorawan spec.  It just seems to be incorrect behavior, but it may actually not be specified.

**Comment by gotthardp** [comment]
Yeah. It's never checked, because it's just an ID that is useless in case of this server, but let's consider this a bug. I will:
 - make AppEUI optional, so it can be disabled if someone doesn't like it
 - check the AppEUI against what device sent and issue an error if they don't match

**Comment by gotthardp** [comment]
I just implemented that and will include that in next release. Please check.

**Comment by SayreBlades** [comment]
Thanks much!
