### ISSUE TITLE
I  Can't view API Administration page 

### ISSUE THREAD

**Issue by suhaibfs** [gotthardp/lorawan-server#157]
Hello there,
I am new to LoRa, I installed Erlang 20 on my linux server, then I installed lorawan-server using .deb package. I allowed 8080 port on my firewall, yet I can't view the API page.
Note : I am not running the server locally.

What can be the issue here?

Thanks in advance!
<img width="668" alt="loraserver 1" src="https://user-images.githubusercontent.com/20699277/28153230-f3c6989e-67d6-11e7-9c07-7c67b2f4f296.PNG">
<img width="352" alt="loraserver 2" src="https://user-images.githubusercontent.com/20699277/28153231-f3cabe06-67d6-11e7-8f4e-889fcf8a3610.PNG">

**Comment by gotthardp** [comment]
And how do you access the API page? What error are you seeing?

**Comment by suhaibfs** [comment]
I am supposed to open http://MYSERVERIP:8080 to access it right?
when I open that in my browser I get time out error
This site can’t be reached
[Server IP] took too long to respond.

**Comment by gotthardp** [comment]
That is weird. I see that 80 and 443 is open too, could there be some httpd/proxy related issue?

**Comment by suhaibfs** [comment]
The issue was from the server provider side (Alibaba Cloud), they have ( Security Group List ) where I had to allow 8080 PORT access. Now everything works fine ( server side ), moving to setting up my Raspberry PI for packet forwarding.
Thank you for your help.

**Comment by gotthardp** [comment]
Cool. Thanks for letting me know.
