### ISSUE TITLE
How to authenticate for the REST api.

### ISSUE THREAD

**Issue by gjoosen** [gotthardp/lorawan-server#162]
Hello,

How should I authenticate for the REST api.
I'm using postman to test the REST api, but when I try the following url: `IP:8080/users` I get the following status back: 401 Unauthorized. Is there some kind of JWT to authenticate, I cannot find anything about this in the documentation.

**Comment by gotthardp** [comment]
It's pure HTTP Basic authentication. the tool shall reply to 401 with the password. did it?

**Comment by gjoosen** [comment]
The tool doesn't ask for a password or something, just returns 401.
Here is a screenshot of the tool return.
<img width="1138" alt="screen shot 2017-07-15 at 00 29 47" src="https://user-images.githubusercontent.com/3176196/28233123-e5db8158-68f4-11e7-8484-a1eee84fd23b.png">

**Comment by gotthardp** [comment]
You have to enter the password before sending the request:
https://www.getpostman.com/docs/postman/sending_api_requests/authorization

**Comment by gjoosen** [comment]
Thanks, solved the problem!
