### ISSUE TITLE
Ability to use funs with RAW

### ISSUE THREAD

**Issue by altishchenko** [gotthardp/lorawan-server#174]
Hello Petr,
I think it would be a great idea to be able to use Up/Down funs with RAW mode, might help a lot things out there. The call-reply format should be binary-in (possibly accompanied by a map of gateway/devaddr/deveui etc) --> binary-out. Same applies to downlinks also.

**Comment by gotthardp** [comment]
Oh, yes. Binary-in, binary-out is not supported, but can be done quite easily.

**Comment by altishchenko** [comment]
Exactly what I ask :) ! This way I can even fool Adafruit :)

**Comment by gotthardp** [comment]
I did a basic implementation, preserving the API (so without any maps, just port and data). Will you test it, please?

**Comment by altishchenko** [comment]
Sorry, fell out for a while. Will test it straight away!

**Comment by altishchenko** [comment]
It just works great! Thank you Petr!!!
