### ISSUE TITLE
Pass MAC message type in TxQ

### ISSUE THREAD

**Issue by altishchenko** [gotthardp/lorawan-server#176]
Can you add a MAC message type to the TxQ, so that I can differentiate the 'presumed' delay between join-accept and data messages in case #txq.time is undefined?

**Comment by gotthardp** [comment]
This delay is auto-calculated by the server-- the TxQ.tmst = RxQ.tmst + downlink delay.

**Comment by altishchenko** [comment]
Oh, I see.
