### ISSUE TITLE
Error 400 on POST request

### ISSUE THREAD

**Issue by Jorrie911** [gotthardp/lorawan-server#178]
Hey,

Great work on the Lora server. I just have a question regarding the POST requests.
When I try to POST data to a server (http://posttestserver.com/post.php for testing purposes). I get a Error 400.
Below is some extract from ngrep

T 10.0.0.173:54937 -> 107.170.47.130:80 [AP]
POST  HTTP/1.1..content-length: 146..host: posttestserver.com:80..content-type: application/x-www-form-urlencoded....appargs=Arg&data=%00%00%00%00%00%17%00%17%00C%0C%CC%0C%CC%00%01%00%00%FE%00%FE%00%FE%00%FE%00%FF%1E%1E%00%00%00%00%00%
00%00%00%04%00Y%8Cf%FD%00%00
##
T 107.170.47.130:80 -> 10.0.0.173:54937 [AP]
HTTP/1.1 400 Bad Request..Date: Thu, 10 Aug 2017 12:00:40 GMT..Server: Apache/2.4.18 (Ubuntu)..Content-Length: 311..Connection: close..Content-Type: text/html; charset=iso-8859-1....<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">.<html><head>.<title>400 Bad Request</title>.</head><body>.<h1>Bad Request</h1>.<p>Your browser sent a request that this server could not understand.<br />.</p>.<hr>.<address>Apache/2.4.18 (Ubuntu) Server at doptsv1.localdomain Port 80</address>.</body></html>.
#####
Any help will be appreciated, I am quite new to the Lora communication and also Linux, so I might be doing something wrong

Thanks

**Comment by gotthardp** [comment]
Hi. To what URI are you posting and what you ware trying to achieve?

**Comment by Jorrie911** [comment]
I am posting to http://posttestserver.com/post.php(just for testing now) then I can see the data on
http://posttestserver.com/data/

When this works successfully I will create a php file on my own server to process the data and put the data into a SQL database

**Comment by gotthardp** [comment]
I still don't see how this is related to lorawan-server. Could you please explain this a bit more?

**Comment by Jorrie911** [comment]
When I post with the lorawan-server I get a Error 400, which indicates that there might be a problem with the HTTP header or data that has to be send.
This is found in the debug.log:
2017-08-10 15:38:14.797 [debug] <0.360.0>@lorawan_connector_http:handle_info:83 HTTP request failed: 400

Using some other way of posting(such as hurl.it) to test the posttestserver.com the connection is successful (200) and the data is received on the other end

**Comment by gotthardp** [comment]
But again: what URI on the lorawan-server are you POSTing to?

**Comment by Jorrie911** [comment]
![image](https://user-images.githubusercontent.com/30899448/29173995-4637973a-7de5-11e7-8a6e-0b7675d226b1.png)

This is what my setup looks like

**Comment by gotthardp** [comment]
I see now. It may be because of the data attribute. You defined some 'Parse Uplink' handler function, right?

**Comment by Jorrie911** [comment]
Yes,
Since I am not that fimiliar with fun, I used a sample from another issue I found:
fun(_Port, Bin) ->
#{data => binary_to_list(Bin)}
end.

It seems to work well because as you can see in the ngrep extract above:
data=%00%00%00%00%00%17%00%17%00C%0C%CC%0C%CC%00%01%00%00%FE%00%FE%00%FE%00%FE%00%FF%1E%1E%00%00%00%00%00%
00%00%00%04%00Y%8Cf%FD%00%00

This is correct this is my data

**Comment by gotthardp** [comment]
You may be getting the error because the data are binary. Have you tried Raw payload instead?

**Comment by Jorrie911** [comment]
Could you please give an example of how the erlang code will look for a Raw payload?

**Comment by gotthardp** [comment]
Just switch the handler to Raw. No functions are used there.

**Comment by Jorrie911** [comment]
With the RAW the data doesn't display correctly as seen below
This is the ngrep
T 10.0.0.173:46771 -> 107.170.47.130:80 [AP]
  POST  HTTP/1.1..content-length: 45..host: posttestserver.com:80..content-type: application/octet-stream.............C.............................Y.{~..
##
T 107.170.47.130:80 -> 10.0.0.173:46771 [AP]
  HTTP/1.1 400 Bad Request..Date: Fri, 11 Aug 2017 07:41:00 GMT..Server: Apache/2.4.18 (Ubuntu)..Content-Length: 311..Connection: close..Content-Type: text/
  html; charset=iso-8859-1....<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">.<html><head>.<title>400 Bad Request</title>.</head><body>.<h1>Bad Request</
  h1>.<p>Your browser sent a request that this server could not understand.<br />.</p>.<hr>.<address>Apache/2.4.18 (Ubuntu) Server at doptsv1.localdomain Po
  rt 80</address>.</body></html>.
########

**Comment by gotthardp** [comment]
Well, but this is an issue of the other server. It should be able to accept application/octet-stream.

**Comment by Jorrie911** [comment]
Using hurl.it to simulate a POST the server accepts application/octet-stream
![image](https://user-images.githubusercontent.com/30899448/29261210-ad05b316-80ce-11e7-8ab5-ff7ac7b05970.png)

**Comment by gotthardp** [comment]
Good to hear. Thanks for letting me know.
