### ISSUE TITLE
Notes editbox

### ISSUE THREAD

**Issue by Kralg** [gotthardp/lorawan-server#180]
Hi, would it be possible to add some kind of notes in devices, node and gateway edit windows?
I have some additional information about them and what I am doing right now I am saving that information in a local db. I suppose it could be possible to add some kind of erlang application which would use mnesia db and store additional data in it, but maybe notes editbox would be smoother implementation and handy option. My additional data right now can have around 300 symbols or so. It will probably be some kind of json packets.
Other suggestions are welcome.

**Comment by gotthardp** [comment]
Hello. The 'Group' and 'Arguments' fields are intended for some application related data. These are not sufficient for you?

**Comment by Kralg** [comment]
> Arguments, which is an opaque string with application-specific settings. 

So server is not using Arguments anywhere just saves it and that is it? This probably would work.
Group I am using to group the devices and send multiple downlinks to all of them.

**Comment by gotthardp** [comment]
Correct. Server just stores the values and sends the values to backend applications.
