### ISSUE TITLE
Hash password

### ISSUE THREAD

**Issue by patrickrst** [gotthardp/lorawan-server#189]
Passwords seem to be stored in plaintext in the file `/var/lib/lorawan-server/Mnesia.lorawan/users.DCD`.

It would be nice to hash them to improve security. The following links may be helpful:

* https://github.com/ferd/erlpass (is based on erlang-bcrypt)
* https://github.com/smarkets/erlang-bcrypt

**Comment by gotthardp** [comment]
True. Will do.

**Comment by gotthardp** [comment]
Done. Will be included in the coming 0.5.0 release.
