### ISSUE TITLE
packet with fcnt 0 not handled

### ISSUE THREAD

**Issue by lignode** [gotthardp/lorawan-server#194]
after each join accept, when device send an confirmed packet with fcnt 0, the server just ignore it.  it looks like after each join accept, the server reset fcntup to 0. then when it receive a fcnt 0 packet, server process the packet as an retransmitted packet because of the same fcnt 0.
is this behaviour correct? i'm very confused, because semtech test case send their first packet after joining with fcnt 0 instead of 1.

**Comment by gotthardp** [comment]
I am confused too, but you may be right. I will double check with other implementations.

**Comment by qingchuwudi** [comment]
Yeah,it seems that `0` while be updated to `1` by mote program in the first frame.

[LoRaMac-node](https://github.com/Lora-net/LoRaMac-node)

**Comment by gotthardp** [comment]
And does PrepareFrame send 0 or 1 in the first uplink? I thought I did test it and it sent 1.

**Comment by qingchuwudi** [comment]
yeah, it does send `1`.

**Comment by gotthardp** [comment]
I don't want to change it if the reference node firmware sends 1. Could someone prove that sending 1 is wrong?

**Comment by lignode** [comment]
there is a change in reference node code. please look at commit  075e4fc2c62863c88849a312d3163e4beef874f8  of https://github.com/Lora-net/LoRaMac-node .
in earlier code, the UpLinkCounter is initialized to 1, after that, 0.
seems like Semtech not very clear on their own spec :(

**Comment by qingchuwudi** [comment]
My server is using `1`, and I'm waiting for the new LoRaWAN spec. Although, node code has bean initialized with `0`.

**Comment by gotthardp** [comment]
Other users suffer from this problem too, so I made a fix to allow a device after join to start with 0 or 1.

**Comment by gotthardp** [comment]
Release in v0.4.11
