### ISSUE TITLE
updating erlang debian

### ISSUE THREAD

**Issue by DenDeze** [gotthardp/lorawan-server#195]
wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
sudo dpkg -i erlang-solutions_1.0_all.deb

sudo apt-get update
sudo apt-get install erlang

USING THE NORMAL ERLANG FROM DEBIAN REPOSITORIES DOES NOT WORK. please note in docs

**Comment by gotthardp** [comment]
That is correct (for now). Will clarify the docs.

**Comment by DenDeze** [comment]
Thank you!

**Comment by gotthardp** [comment]
Fixed. Thank you!
