### ISSUE TITLE
How to add new region AS923-925?

### ISSUE THREAD

**Issue by richerhuang** [gotthardp/lorawan-server#196]
How to add new region for AS923-925?
https://www.thethingsnetwork.org/wiki/LoRaWAN/Frequencies/Frequency-Plans

**Comment by gotthardp** [comment]
The AS923 is not an easy one. It requires the CFList in Accept, which is not implemented yet. See the issue #137.

**Comment by richerhuang** [comment]
Can I just add channel plan without CFList in AS923 ?
Currently AS920-JP is working fine for me.

**Comment by gotthardp** [comment]
The AS920-JP was introduced in the commit https://github.com/gotthardp/lorawan-server/commit/5b36edc8525b7d91c3819348796d4cdfea75b584, so you can have a look what is necessary.

**Comment by gotthardp** [comment]
The CFList was just implemented and will be included in the future 0.5 release.
