### ISSUE TITLE
small url error on event list

### ISSUE THREAD

**Issue by erwan-rissel** [gotthardp/lorawan-server#197]
Hello,
First thank you for your awesome network server.
Using 0.4.10
I just had an uplink missed event on a sensor i'm currently testing.
On the event page (and on the dashboard too btw), the Eid link is wrong: /admin is repeated twice.

Attached below is a screenshot, pay attention to the url bottom left 
![image](https://user-images.githubusercontent.com/25006176/30328446-a74ca214-97cf-11e7-8714-4f08e3551ec0.png)

**Comment by gotthardp** [comment]
Hello. I am glad you like the server. I just made an update to fix this.
