### ISSUE TITLE
gotthardp lorwan server on Multitech conduit mlinux

### ISSUE THREAD

**Issue by pdl86** [gotthardp/lorawan-server#198]
Hello 
does anyone succeed to install the lorawan-server on a Multitech conduit mLinux gateway ? 
we need to build simple stand-alone network ( but with possibility later one to add two or three gateways as slaves), integrtaed MQTT connector  and with easy to use lorawan-server ( thank to petr GUI) .

any feedback will be appreciated.
regards
Philippe

**Comment by gotthardp** [comment]
Not yet, but working on this.

**Comment by pdl86** [comment]
Hi Petr

good news.

Any expected date ?

may I help ( testing, check , ...) ?

regards

philippe


Le 13/09/2017 à 10:25, Petr Gotthard a écrit :

**Comment by gotthardp** [comment]
Hello. I finally reached some success. It is documented [here](https://github.com/gotthardp/lorawan-server/blob/master/doc/Embedded.md#multitech-mlinux). May need some testing and tuning though. Feel free to suggest updates.

**Comment by pdl86** [comment]
Hello

thanks for teh info , we will give a try next week.



Le 22/09/2017 à 00:40, Petr Gotthard a écrit :
