### ISSUE TITLE
Include all gateway's info which received the same message before deduplication in backend JSON message

### ISSUE THREAD

**Issue by kajilemon** [gotthardp/lorawan-server#199]
Currently One received gateway info which has been selected by best RSSI is included in JSON message. For multiple gateways situation,  I think it's desirable to include ALL gateways info (mac, lsnr, rssi and freq) which received the same message before deduplication in backend JSON message.

**Comment by gotthardp** [comment]
Yes, but it needs larger refactoring. It will be done together with #147.

**Comment by gotthardp** [comment]
ready in the devel branch, will become 0.5.0 one day
