### ISSUE TITLE
TLS schema 

### ISSUE THREAD

**Issue by batulzii** [gotthardp/lorawan-server#200]
It is possible to define the ssl:// scheme for the server but there are no configuration options for setting the various TLS parameters.  Any plan?

**Comment by gotthardp** [comment]
You mean admin via HTTPS or something else? What config are you missing?

**Comment by batulzii** [comment]
web admiin and application socket are  needs tls..application will be fine, if it require token for connection to the server.

**Comment by gotthardp** [comment]
But for web admin and WebSocket you can set any TLS parameters you want.
