### ISSUE TITLE
Can not create Handler

### ISSUE THREAD

**Issue by pdl86** [gotthardp/lorawan-server#201]
Hello 
I'm trying to create an handler , but get a "Status Change error" systematically

What's strange  : 
1°  Format : whatever is chosen ( Json, raw data, Web form) , the "ticker valid /invalid" shows both ( X and V)
2 uplink  fields : I suspect that "rxq" has to be chosen for parsing ? 
 ( by the way , ,where are coming from these fields value ? )
3 Parse uplink and Build downlink are almost "standard" ( derived from the doc) 
4) the connector is existing , but the "ticker valid /invalid" shows both ( X and V)

what could  be wrong ? 

![image](https://user-images.githubusercontent.com/30148795/30541332-3c1ca330-9c7b-11e7-985e-eaa2e06708d0.png)

thanks in advance 
philippe

**Comment by pdl86** [comment]
Finally I've found  the error, withing the Parse Uplink syntax,  neither Long nor AltGPS , in the second member were  existing, and the order of assignation was inverted.
sorry for the distrubance

**Comment by gotthardp** [comment]
True. While at this-- please note that the variables in the `<< >>` brackets shall start with a capital letter. The first `ts` doesn't (if I see correctly).

**Comment by pdl86** [comment]
Petr
thanks for the tip: it will probably save me some serious time !
regards
philippe
