### ISSUE TITLE
Is the SNR over demodulation floor calculated correctly?

### ISSUE THREAD

**Issue by javierpedrido** [gotthardp/lorawan-server#206]
In lorawan_mac_commands.erl instead of Margin - 32, shouldn't it be (Margin > 31) ? -Margin + 32 : Margin?
The Lora spec says its a 6bit signed int.

**Comment by gotthardp** [comment]
Looks like it is not, thanks for reporting this. From some reason I thought it's unsigned, shift by 32.
I just fixed that.

**Comment by javierpedrido** [comment]
Thanks for the fix and for writting the server!
