### ISSUE TITLE
How to send a list of frequency channels to a device ?

### ISSUE THREAD

**Issue by greenlora** [gotthardp/lorawan-server#207]
Hello,

Is it possible to send a list of frequency channels to a device ?
Does the Network Server send NewChannelReq command to devices ? As I read that Joinaccept frames doesn't support CFList, it means that only the 3 mandatory channels are used for EU 868Mhz.

Thanks

**Comment by gotthardp** [comment]
Hello. The NewChannelReq is not supported either. Yes, currently only the 3 mandatory channels are used for  EU 868Mhz.

**Comment by gotthardp** [comment]
CFList implemented; will be in the future 0.5.0 release
