### ISSUE TITLE
beam.smp issue (ubuntu 16.04 LTS)

### ISSUE THREAD

**Issue by kazi93** [gotthardp/lorawan-server#217]
@gotthardp @kajilemon So, my server suddenly stopped responding. I guess the emqt too. I think the real culprit is beam.smp. Any previous experience ?? Erlang version 20 already.

<img width="691" alt="screen shot 2017-10-12 at 03 23 44" src="https://user-images.githubusercontent.com/18202431/31474732-ecb554ec-aefc-11e7-9bfd-924b06d7b21c.png">

Memory usage: 

<img width="597" alt="screen shot 2017-10-12 at 03 33 51" src="https://user-images.githubusercontent.com/18202431/31474966-523e0984-aefe-11e7-9f68-01ce716e6450.png">

**Comment by gotthardp** [comment]
Hello. I have no idea why this could happen. If it's a bug, then it's an Erlang/OS bug.
