### ISSUE TITLE
===> Compiling _build/default/lib/cowlib/src/cow_multipart.erl failed

### ISSUE THREAD

**Issue by y0913011021** [gotthardp/lorawan-server#222]
===> Compiling cowlib
===> Compiling _build/default/lib/cowlib/src/cow_multipart.erl failed
_build/default/lib/cowlib/src/cow_multipart.erl:427: syntax error before: '{'
_build/default/lib/cowlib/src/cow_multipart.erl:526: syntax error before: '{'

_build/default/lib/cowlib/src/cow_multipart.erl:22: function boundary/0 undefined
_build/default/lib/cowlib/src/cow_multipart.erl:425: spec for undefined function cow_multipart:boundary/0
_build/default/lib/cowlib/src/cow_multipart.erl:529: illegal guard expression

make: *** [build] Error 1

**Comment by gotthardp** [comment]
Looks like Erlang 18. You need Erlang 19 or 20.
