### ISSUE TITLE
Moved logs to /var/log

### ISSUE THREAD

**Issue by kazi93** [gotthardp/lorawan-server#223]
@gotthardp I have installed v0.4.12 (started in background as a daemon) by unpacking /usr/lib/lorawan-server. And start the server by "systemctl start lorawan-server"
However, found database in /var/lib/lorawan-server but not logs which suppose to be in /var/log/lorawan-server.  Where am I lost? Do I need to uncomment "lager" in sys.config before starting the server at the first time? 

attachment : sudo tail -f /var/log/syslog
[log.txt](https://github.com/gotthardp/lorawan-server/files/1418297/log.txt)

Btw : this how I install :+1: 
The lorawan-server can be started in background as a daemon. On Linux systems with systemd you should:

Unpack the binary release to /usr/lib/lorawan-server
Copy bin/lorawan-server.service to /lib/systemd/system
Create a dedicated user by useradd --home-dir /var/lib/lorawan-server --create-home lorawan
Start the server by systemctl start lorawan-server
This will put the database into /var/lib/lorawan-server and server logs into /var/log/lorawan-server.

**Comment by gotthardp** [comment]
Failed to open log file /var/log/lorawan-server/debug.log with error permission denied

the directory lorawan-server must be owned by the lorawan user

**Comment by gotthardp** [comment]
There was one step missing from the installation guide. I just fixed it.

Thanks for reporting this and sorry for the inconvenience.

**Comment by kazi93** [comment]
Thank you
