### ISSUE TITLE
Never ending "Data has changed, please reload" for gateway

### ISSUE THREAD

**Issue by gotthardp** [gotthardp/lorawan-server#224]
Gateway statistics are stored in DB, so any uplink/downlink changes the gateway DB record, so it's impossible to edit it via web admin.

**Comment by gotthardp** [comment]
Fixed in 0.4.13.

**Comment by bnjroos** [comment]
I am still getting it in various situations.

**Comment by gotthardp** [comment]
Yeah, it's not perfect yet. The new version 0.5.0 will fix this problem is a bit better way.
