### ISSUE TITLE
Inserting JSON/RAW data to mongodb

### ISSUE THREAD

**Issue by kazi93** [gotthardp/lorawan-server#228]
@gotthardp What could be the possible WAY to insert the data to the mongodb or mysql? Websocket ? customise script? I would like to avoid the mqtt method.

**Comment by gotthardp** [comment]
I'd recommend creating a little application adapter and store the data to mongodb directly from Erlang. There is an Erlang MongoDB client as well as Erlang ODBC driver.

**Comment by kazi93** [comment]
thank you
