### ISSUE TITLE
"Confirm" shows crossed (x) in "Received Frames" v.0.4.12

### ISSUE THREAD

**Issue by kazi93** [gotthardp/lorawan-server#230]
@gotthardp Hi! Greetings! Could you please confirm what am I missing. Why does it shows cross icon in the  Confirm attribute or feature. Is it something to do with unknown_appid?
<img width="1005" alt="screen shot 2017-11-03 at 13 11 04" src="https://user-images.githubusercontent.com/18202431/32373291-d8b35388-c098-11e7-82ce-c35541bb82d7.png">
<img width="991" alt="screen shot 2017-11-03 at 13 59 13" src="https://user-images.githubusercontent.com/18202431/32374761-50420556-c09f-11e7-9de6-821af4b5af69.png">

**Comment by gotthardp** [comment]
Hello. It's means the message is "unconfirmed", i.e. not confirmed (see LoRaWAN message types).

**Comment by kazi93** [comment]
@gotthardp So, created handlers, connectors and parsing as the same way I did with v 0.4.10. Currently running two server with v0.4.10 and v0.4.12 with the same config and same sensor. So, I do not really understand why is it showing crossed and unknown_appid.

**Comment by gotthardp** [comment]
The crossed symbol is unrelated to unknown_appid.
 * It is crossed because it was sent as unconfirmed; it's not an error. (Earlier versions had a bug, which showed a tick instead a cross).
 * The unknown app is displayed when the Node's *Group* name does not correspond to any handler. Could there be a typo?

**Comment by kazi93** [comment]
It is not a typo. However, it resolved. Thank you

**Comment by gotthardp** [comment]
Was it due to a bug in the server or documentation?

**Comment by susiloharjo** [comment]
how to resolved this @kazi93 ?
