### ISSUE TITLE
All nodes shows up in "Received Frames" v.0.4.13

### ISSUE THREAD

**Issue by kazi93** [gotthardp/lorawan-server#232]
@gotthardp I just added the credentials of a single node in the "Nodes" but I see others nodes in the "Received Frames" too though without data ..

**Comment by gotthardp** [comment]
And this is good or bad? It meant to be new fearure.

**Comment by altishchenko** [comment]
IMHO, it is good. This way you can see not yet configured devices around without consulting the logs :)

**Comment by gotthardp** [comment]
Yeah. And it's also beneficial to debug collisions with devices belonging to some other network.
