### ISSUE TITLE
Http client to send frames to a remote http server?

### ISSUE THREAD

**Issue by kazi93** [gotthardp/lorawan-server#234]
@gotthardp I would like to send all the received data or frames if possible (JSON) format to a remote http server for further processing. Your recommendation is highly appreciated. Many thanks in advance.

**Comment by gotthardp** [comment]
Hello. Uplink shall work right now. Downlink will be in 0.5.0.

**Comment by kazi93** [comment]
@gotthardp Thank you. Any instruction? documentation to implement the client?

**Comment by gotthardp** [comment]
The backend instructions cover also HTTP
https://github.com/gotthardp/lorawan-server/blob/master/doc/Backends.md
