### ISSUE TITLE
More info on Gateway detail page

### ISSUE THREAD

**Issue by webfrank** [gotthardp/lorawan-server#242]
Hi,
   could be useful to display last IP:PORT of connected gateway. Info is in event log but could be displayed on gateway status as well.

**Comment by gotthardp** [comment]
Hello. Yeah, I can record and display that.

I even consider adding some Ansible-like scripting to query gateway HW/OS info and do mass-configuration of the gateways. This will have to wait a bit though.

**Comment by gotthardp** [comment]
The future 0.5.0 will display the IP address.
