### ISSUE TITLE
RX_DELAY modification

### ISSUE THREAD

**Issue by gnob417** [gotthardp/lorawan-server#243]
Hi, i want to know that it is possible to modify RX1_DELAY or RX2_DELAY value.
I already know the specification of LoRaWAN, however, I just want to know it is possible or not on code level.
if so, where is the part of delay value registration?

**Comment by gotthardp** [comment]
Hello. To modify the delays simply add (and modify the value of) one or more of the following parameters to the lorawan_server config
```erlang
        {join1_delay, 5000000}, % us
        {join2_delay, 6000000}, % us
        {rx1_delay, 1000000}, % us
        {rx2_delay, 2000000}, % us
```
