### ISSUE TITLE
home location does not reflect $LORAWAN_HOME 

### ISSUE THREAD

**Issue by hallard** [gotthardp/lorawan-server#244]
Hi,

I'm using the latest release 0.4.13 on a RPI 3 (jessie) with an ic880a concentrator. To make the system more robust I decided to use in read only mode, this mean all my FS is RO (It's not the first time I'm doing so, so I know it works). You can have more detail [here](https://hallard.me/raspberry-pi-read-only/) but it's not the topic

For this one (first time I need to write data) I decided to move lorawan-server database location to a tmpfs area on Ram (`/mnt/ramdisk`).  So here how it works:

- on lorawan-server start copy from SD to Ramdisk
- on lorawan-server stop copy from Ramdisk to SD
- every hour Sync Ramdisk to SD

I added setting of environment variables in `lorawan-server.service` as follow
```
[Service]
Type=simple
Environment=LORAWAN_HOME=/mnt/ramdisk/lorawan-server
Environment=LORAWAN_LOG_ROOT=/var/log/lorawan-server
ExecStartPre=/usr/local/bin/disk2ram
ExecStart=/usr/lib/lorawan-server/bin/lorawan-server
ExecStop=/usr/lib/lorawan-server/bin/lorawanctl stop
ExecStopPost=/usr/local/bin/ram2disk
User=lorawan
```

But I noticed something very strange in process, so I added displaying environment variables with echo before launching the real lorawan-server in it's startup script.
So last lines of `/usr/lib/lorawan-server/bin/lorawan-server` are

```shell
echo "LORAWAN_HOME=$LORAWAN_HOME ROOT=$ROOT_DIR CONFIG=$SYS_CONFIG"
cd $LORAWAN_HOME && erl -noinput +Bd -sname lorawan -pa $ROOT_DIR/lib/*/ebin -s lorawan_app $ERL_ARGS -config $SYS_CONFIG $@
```
And `journalctl -u lorawan-server` show that all is good, echo command show the correct variable value
```
Nov 29 14:17:14 dpy-gw01 systemd[1]: Started LoRaWAN Server.
Nov 29 14:17:14 dpy-gw01 lorawan-server[445]: LORAWAN_HOME=/mnt/ramdisk/lorawan-server ROOT=/usr/lib/lorawan-server CONFIG=/usr/lib/lorawan-server/releases/0.4.13/sys.config
lines 68-128/128 (END)
```
but when I `ps -aux`, you can see line 2 that -home is `/var/lib/lorawan-server` 

```
lorawan    445  0.0  0.2   1816  1100 ?        Ss   14:59   0:00 /bin/sh /usr/lib/lorawan-server/bin/lorawan-server
lorawan    459  0.7  4.4  60908 21900 ?        Sl   14:59   0:43 /usr/lib/erlang/erts-9.1/bin/beam.smp -Bd -- -root /usr/lib/erlang -progname erl -- -home /var/lib/lorawan-server -- -noshell -noinput -sname lorawan -pa /u
lorawan    470  0.0  0.2   2576  1116 ?        S    14:59   0:00 /usr/lib/erlang/erts-9.1/bin/epmd -daemon
lorawan    489  0.0  0.2   1720  1068 ?        Ss   14:59   0:00 erl_child_setup 1024
lorawan    669  0.0  0.2   1816  1092 ?        Ss   14:59   0:00 sh -s disksup
```
Any idea of the problem?

Thanks

**Comment by gotthardp** [comment]
Hi. Is there any problem after all? The `-home` parameters of the `beam` process is not related to the content of `LORAWAN_HOME`. In fact, it is an internal argument of the Erlang system, probably indicating the home directory of the process owner.

**Comment by hallard** [comment]
Well, it seems to work, just wondering if it could cause some trouble later ;-)
Thanks
