### ISSUE TITLE
add a new uplink in the handler?

### ISSUE THREAD

**Issue by kazi93** [gotthardp/lorawan-server#245]
@gotthardp @altishchenko  
For example : Tech 
That will look like  --- "Tech": "sub1ghz", ----in JSON format
I guess, compile the source code would require? If yes, please how to add this uplink ?      
Always appreciate your quick response. 
Thank you

**Comment by gotthardp** [comment]
Hello. Just to make sure I understand, want to add a fixed string to the JSON?

**Comment by kazi93** [comment]
@gotthardp Yes, currently there are "deveui, datetime, gateway etc". So it will be for example: 
{
  "data" : "000A02",
  "datetime" : "2017-09-16T21:35:42Z",
  "devaddr" : "F2D52B00",
  **_"networkType": "Lora",_**
  "fcnt" : 5003,
  "fields" : {
    "temperature" : 25.62
  },

**Comment by gotthardp** [comment]
Right now you can do only
{
  "data" : "000A02",
  "datetime" : "2017-09-16T21:35:42Z",
  "devaddr" : "F2D52B00",
  "fcnt" : 5003,
  "fields" : {
    **_"networkType": "Lora",_**
    "temperature" : 25.62
  },

would it be sufficient?

**Comment by kazi93** [comment]
@gotthardp yes, thank you

**Comment by kazi93** [comment]
No. Sorry. I think it is inside the fields. I want this as an unlink field because it exists like that in the existing database.

**Comment by kazi93** [comment]
Currently I am refused by the http server for data validation and failed to store

**Comment by gotthardp** [comment]
Will you please wait a week or two? This will be possible with the new 0.5.0 version, which I am currently working on.

**Comment by kazi93** [comment]
@gotthardp Thank you for your quick response. One week would be just fine. By the way, I wrote you an email.

**Comment by gotthardp** [comment]
You did write me an e-mail? Did I forget about it, or it didn't arrive (yet)?

**Comment by kazi93** [comment]
@gotthardp It is done. I added the field. Thank you.

**Comment by altishchenko** [comment]
Mind to share how you did it?
