### ISSUE TITLE
clean way to run lorawan_server build as startup service

### ISSUE THREAD

**Issue by kazi93** [gotthardp/lorawan-server#249]
@gotthardp @altishchenko 
What is the clean way to run lorawan_server build as startup service that is :
lorawan-server/_build/default/rel/lorawan-server/bin$ sudo ./lorawan-server

Server platform : Ubuntu 16.04 LTS

**Comment by altishchenko** [comment]
@kazi93 for Ubuntu you can generate a .deb package with `make dpkg` and install it as any other usual package. For other situations, where you don't want a package, you can use `rebar3 tar`, which will make a `tar.gz` bundle required to run it. lorawan-server uses, what is called, a 'simple startup' approach and that leaves no other options :) Look at the scripts in the `scripts` directory of the repository.

**Comment by altishchenko** [comment]
And, as a follow up, you are definitely not going to run it from `_build/default/rel/...` etc.

**Comment by kazi93** [comment]
@altishchenko Thanks. Ubuntu it is perfect.
