### ISSUE TITLE
Microchip-Loramote OTAA/ABP

### ISSUE THREAD

**Issue by kazi93** [gotthardp/lorawan-server#252]
@gotthardp 
Anyone configured and connect with Loramote RN2483? I do not see any node creation in the server. Help required!! . I am using LoRa Development Utility as below attached. Do I need to configure MAC channels?? what is the procedure...please ..thanks in advance.. Btw. I have selected Microchip-loramote as Application.

Pressing S2 button says Valid Keys Required. I copied and paste and double checked. It cannot be wrong. !! :(

**Comment by gotthardp** [comment]
Hello. Standard question: what is in the server debug.log?

**Comment by altishchenko** [comment]
And server side device config screenshot, please.

**Comment by kazi93** [comment]
@altishchenko I switched back to ABP for primary test. However, now the error is : 

warning | 2017-12-22 06:21:53 | 2017-12-22 06:21:53 | 1 | server |   | http_error | {404,"/devstat/26011B64"}
-- | -- | -- | -- | -- | -- | -- | --
  | warning | 2017-12-22 06:21:48 | 2017-12-22 06:21:48 | 1 | server |   | http_error | {404,"/devstat/26011B64"}

debug.log

![http_error](https://user-images.githubusercontent.com/18202431/34286522-7392f0f2-e6e1-11e7-95f4-f0f0bcacf1bf.png)

**Comment by gotthardp** [comment]
This warning is not an error. It is shown also in a situation when the device didn't send any frames yet, which is your case (FCnt=0). Once at least one frame is received the warnings will stop.

**Comment by gotthardp** [comment]
the http_error warnings will no longer be shown in the future 0.5.0
