### ISSUE TITLE
Unknown command?

### ISSUE THREAD

**Issue by nuguri618** [gotthardp/lorawan-server#253]
I had some problem when uplink message from mote.
Then I saw this kind of message from lorawan server debug console.
It's problem to read data and port?

![error](https://user-images.githubusercontent.com/17840689/33931285-e6aa12ba-e032-11e7-9b90-0abfb73e54fb.PNG)

**Comment by gotthardp** [comment]
Hello. I suspect it's because your device sends some MAC command that is defined in a new version of the standard that the server doesn't support yet.

**Comment by gotthardp** [comment]
should be fixed in the latest devel branch (to be 0.5.0)
