### ISSUE TITLE
Fixed database name, not followed by hostname

### ISSUE THREAD

**Issue by hallard** [gotthardp/lorawan-server#257]
Hi Petr,

By default the database directory is like `Mnesia.lorawan@*` in the lorawan-server directory. This mean the name depends on device/computer hostname

How it is possible to fix the name instead the @hostname to be able to rename device hostname without incidence?

Thanks

**Comment by gotthardp** [comment]
Hello. In the lorawan-server startup script there is a paramater `-sname lorawan`. Change this to `-name lorawan@whatever` (note the missing *s*: `-name` instead of `-sname`).

**Comment by hallard** [comment]
@gotthardp 
Better than I thought, I can change here afterward, thanks ;-)
