### ISSUE TITLE
Single-Channel "Nano" Gateway Support

### ISSUE THREAD

**Issue by Eric24** [gotthardp/lorawan-server#258]
Does anyone have experience using a single-channel gateway (like pycom.io, etc.) with this server? Of course it's not "true" LoRaWAN (since it can only listen on one channel at a time), but such gateways are compatible with TTN, for example.

Does this server currently support single-channel gateways? If so, what's required to set it up? If not, what limitations prevent it? Also, what needs to be considered for such a gateway (other than the obvious limit to the number of supported devices)?

**Comment by gotthardp** [comment]
People tried. You basically need to convince **both** the device and the server to use this single channel for downlink. On the server side this can be done by switching the "TX Window" for all connected devices to TX2.

**Comment by Eric24** [comment]
Interesting. So exactly how does using TX2 make this work?

**Comment by javierpedrido** [comment]
Hi,

I have a Pycom Lopy acting as a gateway of some Multitech's mDots and xDots and this server works fine. One other thing to consider is that, some end node's firmware do not allow to modify the OTA join messages data rate, that means that only ABP can be used for that nodes.

Regards,
Javier

**Comment by Eric24** [comment]
@javierpedrido : Can you expand on what the issue is with using OTA?

**Comment by javierpedrido** [comment]
Since the gateway is listening to one frequency and data rate and the Ota join message data rate is random, the gateway won't be able to pick it up. The random data rate logic cannot be changed in some node firmwares. When you have a normal gateway it can listen at the same time different frequencies and data rates.

**Comment by Eric24** [comment]
@javierpedrido : Ah, that makes sense (the nodes we're using can be set to a fixed data rate, so that's why I hadn't considered that issue).

**Comment by gotthardp** [comment]
I believe the question was answered. Feel free to reopen if more information is needed.
