### ISSUE TITLE
Support for 919MHz to 923MHz

### ISSUE THREAD

**Issue by shmrymbd** [gotthardp/lorawan-server#26]
Can anyone guide me howto start for support for above freq. Thanks

**Comment by gotthardp** [comment]
Hello. I am about to release a new version, which will make introduction of new regions much easier.
However, there are many region specific parameters, not just the frequency. Is the band you want to support listed somewhere in the LoRaWAN standard, or is this some unofficial band?

**Comment by gotthardp** [comment]
Australia 915-928MHz is supported in the latest version 0.3.0, but not tested. Testers are welcome. Does this meet your needs?

**Comment by shmrymbd** [comment]
hi. our freq in Msia.. 919-923MHz. maybe some minor tweak

**Comment by gotthardp** [comment]
Could you be more specific, please? Does your frequency belong to the AS923ISM Band, as described in Section 2.7 of the Regional Parameters, or is it something else?

**Comment by gotthardp** [comment]
I added support also for South Korean 920-923. It *should* comply with Malaysian 919-923 as well.
Closing this issue for now as I cannot do anything else until the LoRaWAN regional parameters are defined for 919-923.
