### ISSUE TITLE
Server Statistics

### ISSUE THREAD

**Issue by Eric24** [gotthardp/lorawan-server#261]
Are any statistics are kept by the server? For example, messages received/sent by gateway or application. If so, how are they accessed?

**Comment by gotthardp** [comment]
The 0.4 versions collect gateway statistics only: TX times and network delays. The 0.5 version will also collect and display requests per sec and errors per sec. I can collect more things but I was not sure what other statistics would be really useful.
As everything else the stats can be accessed via the REST interface or via web-admin.
