### ISSUE TITLE
dpkg build and running as background daemon issue

### ISSUE THREAD

**Issue by kazi93** [gotthardp/lorawan-server#262]
@altishchenko @gotthardp Server version : 0.4.13 
build from source failed ....to run as a daemon but works with #./lorawan-server
1. git download
2.  make dpkg
3. dpkg -i lorawan-server_*.deb
4. systemctl start lorawan-server
5. below error : systemctl status lorawan-server

![dpkg failed](https://user-images.githubusercontent.com/18202431/34460324-12e06312-ee0b-11e7-9ffd-4be6547bf09e.png)

**Comment by gotthardp** [comment]
Hello (and sorry for the delay). I double checked the package and it shall work.
* Please build the package by `make release dpkg` (I fixed the guideline)
* Check if the `/var/lib/lorawan-server` directory exists and who is its owner
