### ISSUE TITLE
Class C, RXWIN2 not receive data confirmed

### ISSUE THREAD

**Issue by matiasz8** [gotthardp/lorawan-server#267]
Hello, I'm testing the class C for my semtech-mote.

I has configure the node as you can see at the picture. The node has prepare to receive through the "RXWIN1" and "RXWIN2". I has setting the Application as WebSocket and TX Window as Auto.

I have performed the following test:

I's sent packets with the json:
{"devaddr":"00020505", "data":"3531", "port":2, "time":"immediately", "confirmed":true}

What I can see is that the module receives packets as if they were in A mode, that is, once I send from the module a message asks if there are messages to download and brings them. (I's attach a picture about it)

Then, I has changed TX Window to "RX2" and I's tried to receive packets with the same json, but in this case, I's not received anything.

Could you help me, please? The RX2 option, is working right?

Thanks a lot,

Nahuel

I have the release 0.4.13
I have this in the debug file:
2018-01-04 14:05:30.424 [warning] <0.315.0> node 00020505 downlink_lost
2018-01-04 14:05:30.424 [debug] <0.315.0>@lorawan_mac:handle_uplink:481 00020505 retransmitting

![clip2248](https://user-images.githubusercontent.com/22972889/34575318-10d286ee-f159-11e7-8d2e-1299bfe17852.png)
![node-config](https://user-images.githubusercontent.com/22972889/34575319-10ff8054-f159-11e7-99c9-824b17503440.png)

**Comment by gotthardp** [comment]
Hello. Could you please decouple the two issues you may have found: the class C and the confirmation?

1) Class C messages are sent in RX2. No server-side configuration is requires. Just to send the message as you did and await frame in RX2. This works or not?

2) I'd try solving the confirmed class C once we fix the unconfirmed case.

**Comment by matiasz8** [comment]
At the moment, I has not receive any frame in RX2. I'll decouple this issue.

**Comment by gotthardp** [comment]
Hello and sorry for the delay. For me the Class C works. Were you able to succeed here, please?

**Comment by matiasz8** [comment]
Thanks for answer, no problem. I hadn't could transmit any packet by Class C at the moment, but I'll try to test again.

**Comment by gotthardp** [comment]
Thanks. Please try the latest 0.5.x, if possible.

**Comment by matiasz8** [comment]
Ohh, ok, thanks for that.

**Comment by matiasz8** [comment]
Hello, I'm trying to test this again, but in this case, I haven't a WebSocket application to select from the combo box. In this case, need I create an Earlang file or just with create a new connector to websocket server It is done?

**Comment by gotthardp** [comment]
Create a backend handler (this is your application name) and then link it with a device profile *and* your WebSocket Connector.

**Comment by matiasz8** [comment]
Hello again,
I can't create a connector webSocket. I has used the examples:

are them all right?

ws://localhost:8080/ws/events/00020507
ws://127.1.1.1:8080/ws/events/00020507
ws://10.0.0.101:8080/ws/events/00020507

![clip9487](https://user-images.githubusercontent.com/22972889/37485626-ca18880e-286a-11e8-8053-24e7b3aff52b.png)

![clip6456](https://user-images.githubusercontent.com/22972889/37485647-d6b657ee-286a-11e8-8ba2-de95c10f8a49.png)

![clip2364](https://user-images.githubusercontent.com/22972889/37485659-dae1077e-286a-11e8-8f14-ecaa5c5b3762.png)

**Comment by gotthardp** [comment]
Follow the documentation :-) URI shall be 'ws:' only. The rest of the url goes into the topic.

**Comment by gotthardp** [comment]
Make sure there are no Failed flags. When a Failed flag is raised, nothing works.

**Comment by matiasz8** [comment]
MMm, I changed It:
I put into the field "Failed" right now:
 - Nothing (1º time)
 - Badarg (2º time)
 - Network (3º time)
 - topic (4º time)

But, the button show the same behavior.

**Comment by gotthardp** [comment]
The Failed field shall be empty. If the server raises a Failed flag the debug.log contains more details.

**Comment by matiasz8** [comment]
Look at this:
If I empty the values of "Failed", when I return to the list, the fields have two "badarg" in the field.
And then I check the connector again and actually have two "badarg" again.

![1](https://user-images.githubusercontent.com/22972889/37603721-fcfd1f9a-2b6d-11e8-929f-4c1fa8cb12f7.png)
![2](https://user-images.githubusercontent.com/22972889/37603725-fee9b1b0-2b6d-11e8-81d6-cd4a35e3beba.png)
![3](https://user-images.githubusercontent.com/22972889/37603731-00d3928e-2b6e-11e8-8ae0-4a82e4db5876.png)

**Comment by gotthardp** [comment]
For the WS: connector the Publish Uplinks/Events shall start with the backslash (as the documentation says).

**Comment by matiasz8** [comment]
Is it correct this way?
![clip0474](https://user-images.githubusercontent.com/22972889/37607561-1c25ddf4-2b77-11e8-8656-795c4d2ece2c.png)

**Comment by gotthardp** [comment]
Looks better. Remove the Failed flag and try if the server accepts it.

**Comment by gotthardp** [comment]
Any progress?  May I  close the issue?

**Comment by matiasz8** [comment]
Hello again,
I was able to complete the sending of the data from my LoraWan module to the WebSocket demo.html. But I could not reverse it.

I sent this json through the ws.html, but the Dashboard informs me that the Downlink was lost.

![clip4863](https://user-images.githubusercontent.com/22972889/38319801-26b87efe-3809-11e8-9064-ac547733ab9a.png)

![clip7632](https://user-images.githubusercontent.com/22972889/38320017-c8fdd5e2-3809-11e8-9f98-a6e068e1f033.png)

Another thing that happens to me is that when I ask if the module has packages to receive, it returns a data, but when converting it, it does not have a conversion to Ascii.

Do I need to pass it through a converter with a seed for it?

![clip1683](https://user-images.githubusercontent.com/22972889/38320171-3a4b44b4-380a-11e8-980b-7f096307575f.png)

**Comment by matiasz8** [comment]
Hello again, 
I've found a bug, or maybe It's a bad configuration that I've set.

I've been debuging the Package Forwarder, and when I send a packet througth the ws.html the Package forwarder log show me that the packet was reject because a bad frequency.

Look, this is the message that I sent:
![clip9795](https://user-images.githubusercontent.com/22972889/39067779-3f3f078c-44b0-11e8-993a-0ee1c2906a78.png)

And this is the error: the frequency is equal "9", so the pkt fwd say that this value must be between 902000000 to 928000000:
![clip9503](https://user-images.githubusercontent.com/22972889/39067780-3f654dac-44b0-11e8-8e4d-7476d08ce2fc.png)

**Comment by gotthardp** [comment]
Feels like you misconfigured "RX2 Freq" in the Network or Profile settings.

**Comment by matiasz8** [comment]
Hello,

Thanks for that. I fixed that problem, I set wrong my RXWin2 Spread Factor, and the global_conf.json configuration was wrong too.

For the tests, I was need to add the parameter "confirmed":true. Without this parameter the module not recieve the message. So, this is the message that I was sending:

Class C:
{"data":"30", "port":12, "time":"immediately", "confirmed":true}

I'm now at the beginning of the test: I set the TX Windows Auto. 

I send the message through the ws.html. This only arrive if I send another message: just like the behavior of Class A.

The message arrive thougth RXWin1 at the moment. I know that the class c message arrive

 on RXwin2 or RXwin0, but at the moment I can't get that result.


I attach my configurations:

![profile-adr](https://user-images.githubusercontent.com/22972889/39257120-1e8f25d2-4887-11e8-9c90-98a3ff1ed41f.png)

![profile-general](https://user-images.githubusercontent.com/22972889/39257183-462a33de-4887-11e8-9084-0fbb5fff3389.png)

![node-adr](https://user-images.githubusercontent.com/22972889/39257186-49607f22-4887-11e8-95ed-e31a585e2245.png)

the result:

![ws-test](https://user-images.githubusercontent.com/22972889/39257196-51774a2e-4887-11e8-995e-18da5ce8fbbf.png)

![mote-test](https://user-images.githubusercontent.com/22972889/39257199-5382cfe6-4887-11e8-9064-9231e2110c64.png)

**Comment by gotthardp** [comment]
Why is "Used RX2 DR" = SF8 500? This is a non-standard value, which may cause the troubles.

**Comment by matiasz8** [comment]
Mmm, I was checking what packet am I receiving as downlink from packet forwarder.

It's true that when the downlink arrive to the packet forwarder the "datr" received is "SF8BW500"

That data: Used RX2 Freq, where can I set?

My module's setting is 923300000, DR8, that corresponding to SF12/500kHz.

I set the RX2 in the application with SF12/500kHz, as you can see in the previous captures.

This is the capture of my module:

![clip4017](https://user-images.githubusercontent.com/22972889/39316388-6897c706-494f-11e8-9126-87b4bae09352.png)

**Comment by gotthardp** [comment]
What does your network ADR settings say? You should align the RXWIN2 settings in your device with the "Used RX2 DR". It will not work otherwise.

**Comment by matiasz8** [comment]
Great! Yes, my mistake was setting in Network - ADR, the RXWin2 with SF8 500.
Thank for all!

**Comment by gotthardp** [comment]
Cool! We finally made it 😃
