### ISSUE TITLE
TX Windows RX2 not receive package confirmation

### ISSUE THREAD

**Issue by matiasz8** [gotthardp/lorawan-server#268]
Hello, as I said before,

I has configure the node as you can see at the picture. 

I have performed the following test:

I has change TX Window to "RX2" and I's tried to receive the acknowledge from a package sent but nothing happends. 

Thanks

I have the release 0.4.13
I have this in the debug file: 
2018-01-04 15:39:11.914 [warning] <0.291.0> gateway 0000112233445500 {ack_lost,82}
2018-01-04 15:39:20.079 [error] <0.297.0> node 00020505 {fcnt_gap_too_large,4}

![node-config](https://user-images.githubusercontent.com/22972889/34578606-57b913ec-f164-11e7-851d-0c172db26123.png)

**Comment by gotthardp** [comment]
Hello. I set a node to RX2, sent a confirmed downlink (class A) and received an ACK. To me this works.

**Comment by matiasz8** [comment]
Thanks for answer. Ok, I'll try to find if I have some wrong at the module's startup. I tested with Class A and Class C too.

**Comment by matiasz8** [comment]
Hello, thanks for that. I'm testing with 5.3 versión and It's Works.
