### ISSUE TITLE
txframes

### ISSUE THREAD

**Issue by gnob417** [gotthardp/lorawan-server#271]
Hi,
If i want to get DevAddr of stored_frames in table 'txframes', (the oldest stored frame)
how could i do using mnesia and some erlang stuff?

regards

**Comment by gotthardp** [comment]
The web admin request (or HTTP/REST request) `http://server/admin#/rxframes/list?sortField=rxframes_ListView.datetime&sortDir=ASC` will provide you this info.

**Comment by gnob417** [comment]
i mean using mnesia function in source code. 
i want to use the information.

**Comment by gotthardp** [comment]
To get the oldest frame among all devices I'd do
```erlang
mnesia:dirty_read(txframes, lists:min(mnesia:dirty_all_keys(txframes)))
```

**Comment by gotthardp** [comment]
Closing for now. If you need more support re this, feel free to reopen.
