### ISSUE TITLE
TxQ configure

### ISSUE THREAD

**Issue by gnob417** [gotthardp/lorawan-server#282]
Hi, I'm modifying my own donwlink handler function.
the code are below.
but i could not see downlink loggig message on packet forwarder process ( ex. JSON down: rxpk) 
is my server send downlink or am i miss something ?
i checked the logs from server that confirms `send_unicast` is done.

```
handle_downlink_my_own(Link, Time, TxData) ->
    TxQ = #txq{region=Link#link.region, freq=Link#link.last_rxq#rxq.freq, datr=Link#link.last_rxq#rxq.datr, codr=Link#link.last_rxq#rxq.codr},
    send_unicast(Link, TxQ#txq{time=Time}, 0, lorawan_mac_commands:build_fopts(Link), TxData#txdata{confirmed=false}).
```

where can i find that my downlink is really passed through udp frame to packet forwarder?
(maybe lorawan_gw_router.erl? which function i have to debug?)

thanks.

**Comment by gotthardp** [comment]
But I cannot help you debugging your own code. Check who calls handle_downlink_my_own and see if some functions still call the original one.
