### ISSUE TITLE
Time interval

### ISSUE THREAD

**Issue by gnob417** [gotthardp/lorawan-server#286]
Hi, thank you for kind support!

I'm wondering about time interval calculation with poisson distribution in Erlang. 
Is there any method to set time interval (arrival interval) not static, but by poisson distribution? 

I mean, i want to generate packets automatically with non-static interval. (and not just random) 

regards.

**Comment by gotthardp** [comment]
You can always generate your own poisson distribution and calculate next timer delay when the previous timeout expires.
