### ISSUE TITLE
lager

### ISSUE THREAD

**Issue by gnob417** [gotthardp/lorawan-server#287]
Hi,
If i want to make a certain log file (not error.log, debug.log) using lager,
How can i create the format.

I modify lager part of lorawan_server.config file like below.

```
{lager, [
    {colored, true},
    % uncomment to display even a high number of messages per second
    % see https://github.com/erlang-lager/lager#overload-protection
    % {error_logger_hwm, undefined},
    {handlers, [
        % {lager_console_backend, [{level, debug}]},
        {lager_file_backend, [{file, "debug.log"}, {level, debug}]},
        {lager_file_backend, [{file, "error.log"}, {level, error}]},
        {lager_file_backend, [{file, "exper.log"}, {level, exper}]}
    ]},
    {crash_log, "crash.log"}
]},
```

but when i use the code ` lager:exper("DOWNLINK : ~p", [Addr])` , there is no such log and even file(exper.log).

Am i miss something?

**Comment by gotthardp** [comment]
Only a fixed set of levels is supported: debug, info, notice, warning, error, critical, alert, emergency
https://github.com/erlang-lager/lager#features
