### ISSUE TITLE
v0.5.0 websocket and app

### ISSUE THREAD

**Issue by hallard** [gotthardp/lorawan-server#288]
Hi Petr,
I just tried my web app (with websockets) with v0.5.0 but there are some changes that I can't figure out
- before a device could belong to a group and we could connect with websocket to that group of devices `ws://localhost/ws/groups/groupname/json`. Today I can imagine it's related to profile?
- If so, on profile config, on admin application I can just select semtech-mode not websocket ?

Did I missed something ? How can I connect with websocket on a group of devices as before ?

Thanks

**Comment by hallard** [comment]
You're welcome 
Thanks got it, 
Do I need a connector for websocket or handler will do the job?
Anyway there are a lot of new parameters to set and on some may be put in documentation some default "out of the box" (same as default for V4) that works, because on some I have no idea what to put in to get it working
Here what I put for a Network of EU 868, not sure all is good, but your validation could be a good start
**on general**
![image](https://user-images.githubusercontent.com/2471931/35392049-d8546678-01e0-11e8-985d-7237f1b3d080.png)

**On network **
Initial Channels I put => 0-2
**On ADR**
Not sure what put put
![image](https://user-images.githubusercontent.com/2471931/35391964-81a22f68-01e0-11e8-8bd6-0fc28eb27538.png)
Initial RX2 Freq (MHz) => no idea what to put in this one, the other too.

Another strange thing, I created a handler
![image](https://user-images.githubusercontent.com/2471931/35392455-38dcad60-01e2-11e8-9d8e-8a9993bbab56.png)

but it's not showing on application (even semtech-mode has gone ?!?)
![image](https://user-images.githubusercontent.com/2471931/35392530-79f3680c-01e2-11e8-9621-0062a995f486.png)

Anyway I need to get things working today, so don't worry about this for now, I'm going back to v0.4.13 until I have more time to test in real the v0.5.0,
May be I can try v0.4.13, restore with dbimport and then launch the upgrade to v0.5.0 just to see ;-)

**Comment by gotthardp** [comment]
I thought the Network settings could be a pain. I added a new file with some suggestions, so it can work more "out of a box".
https://github.com/gotthardp/lorawan-server/blob/master/doc/Regions.md

**Comment by gotthardp** [comment]
Also, I cannot reproduce your trouble with application not showing in the list. Could you please have a look on the Javascript console in your browser to see if there is some error? (In Firefox it's under Web Developper -- Web Console.) Or perhaps debug.log shows something.

**Comment by aymeri06** [comment]
hi everyone, i have the same problem that hallard, i don't have websocket in choice for application with the new version (5.0) it's bug ?

thanks

**Comment by gotthardp** [comment]
Hello. Please read my answer above. There is no 'websocket' application in 0.5.0. You need to create a websocket handler+connector for "ws:" as described in the documentaton.

**Comment by aymeri06** [comment]
sorry i don't see your response ^^ but thank you it's good

**Comment by gotthardp** [comment]
Clarified.

**Comment by nupik** [comment]
Still can't create WebSocket connection 
![image](https://user-images.githubusercontent.com/18184631/35932292-6284e9fa-0c48-11e8-9e50-152970d8e4d9.png)
![image](https://user-images.githubusercontent.com/18184631/35932329-7576e0b8-0c48-11e8-8dc0-78b76e8c9311.png)
![image](https://user-images.githubusercontent.com/18184631/35932361-81ad5db2-0c48-11e8-942a-e53513f5c340.png)
![image](https://user-images.githubusercontent.com/18184631/35932376-8ae2be2c-0c48-11e8-84d4-d82b953cf275.png)

**Comment by gotthardp** [comment]
And what error are you getting?

**Comment by nupik** [comment]
Just have no connection by URI( /ws/uplink/010A8AA2 )
![image](https://user-images.githubusercontent.com/18184631/35967495-1c5fe13e-0cd2-11e8-90a1-72299b50a333.png)

**Comment by gotthardp** [comment]
Oops. I confirm this is a bug. I just fixed that in the 'main' branch.

**Comment by hallard** [comment]
@gotthardp 
By the way, about websockets, I noticed in latest v0.4.x  that when a websocket client send data (in my case json) and the data is not correct (example unexisting node or bad format) the server disconnect the client. I do not know if it is the expected behavior or not, but this mean client can't do anything until reconnexion (that can be async).
So my question is:
Is it the same way on v0.5.x? and if so would it be possible that the server just discard the data instead of closing websocket?
Thanks

**Comment by gotthardp** [comment]
@hallard yes, this behaviour is also in 0.5.x, but I can consider changing it.

**Comment by nupik** [comment]
Yes, I think better just send error report back. It will be more robust

**Comment by nupik** [comment]
Next step. Question: connection is ok, but I doesn't receive any data by websocket.
![image](https://user-images.githubusercontent.com/18184631/36020527-23efd23e-0d94-11e8-8ac4-8eea4835bd34.png)
![image](https://user-images.githubusercontent.com/18184631/36020550-31aff1d8-0d94-11e8-8b46-d584486167e3.png)
