### ISSUE TITLE
Dashboard page visually jitters as time graph advances

### ISSUE THREAD

**Issue by cmenscher** [gotthardp/lorawan-server#293]
In Chrome 63.0.3239.132 (OSX 10.12.6) all divs with class "panel" on the main Dashboard page move up and down a pixel with every refresh of the advancing time graph.  The issue usually occurs if the window width is half the screen width or less, and can be abated by zooming in and out of the graph, or by widening the window.  But even then it sometimes returns.

**Comment by gotthardp** [comment]
I believe this was fixed by #529 and will be included in v0.6.4.
