### ISSUE TITLE
Send message to device with script python

### ISSUE THREAD

**Issue by aymeri06** [gotthardp/lorawan-server#295]
Hello everyone, i have just question. 
have you a little python script to send a message with data to device LoRa on network.

Thank you so much.

**Comment by gotthardp** [comment]
See the documentation on how to setup an AMQP or MQTT connector and then use Python library for AMQP or MQTT to publish the downlink
https://www.rabbitmq.com/tutorials/tutorial-five-python.html
https://pypi.python.org/pypi/paho-mqtt#publishing

**Comment by aymeri06** [comment]
thanks
