### ISSUE TITLE
JSON message via MQTT

### ISSUE THREAD

**Issue by webfrank** [gotthardp/lorawan-server#296]
Hi,
   with latest docker version 0.5.0 I cannot receive all the selected fields with JSON.
I configured the handler to send devaddr, fcnt, port, data, datetime and all_gw but I receive only all_gw and decoded data.
<img width="938" alt="schermata 2018-01-30 alle 15 06 27" src="https://user-images.githubusercontent.com/4688664/35570387-623ebde2-05cf-11e8-8395-764beed953ea.png">
<img width="518" alt="schermata 2018-01-30 alle 15 08 20" src="https://user-images.githubusercontent.com/4688664/35570413-7064128c-05cf-11e8-84e7-4df52a12eba8.png">

**Comment by webfrank** [comment]
Ok, I found it was changed the parse uplink function, changing it worked.

**Comment by gotthardp** [comment]
Yeah :) You should not even receive the all_gw :) The syntax changed a bit-- the _Port parameter for Uplink changed to Fields and disappeared for Downlink. Also, when adding custom attributes you should amend the Fields by `Fields#{temp => Temp, irms => Irms}`.
