### ISSUE TITLE
Unexpected_data Applictaion error - Please help.

### ISSUE THREAD

**Issue by netuserlv** [gotthardp/lorawan-server#297]
Hey! I`m running the the server and I have connected my gateway to the server and everything is running just fine until I`m sending the data to the application. I know that the application is not configured right for my node. But it is all I have maybe someone could help me configure the application so that It would work for my node. I`m using sodaq mbili board with the rn2483 chip on it. And simply using the ATT_lora_iot examples found on github. I`m really not that knowing that in LORA so thats all that works for me. Maybe someone could help me building the erlang applications for sodaq mbili node and the att_lora_iot examples. I`m using Nemeus pico gateway.

**Comment by gotthardp** [comment]
Hello. And what do you want to do with the data from the device? Display them, store them, process them?

**Comment by netuserlv** [comment]
For now I guess just store them. I think I could figure out the displaying part myself.

**Comment by gotthardp** [comment]
I recommend you to use WebSockets, i.e. connect to the server to receive all uplinks and handle them as you like. You should review the Handlers and Connectors Guide (see /doc) to understand how to do that.

**Comment by netuserlv** [comment]
Ok maybe could You please help me with that.... I configure my connector to 
URL = "ws:"
Publish Uplinks = "/ws/uplink/00441018"
Publish Events = "/ws/events/00441018"

and when i go to the link = "http://localhost:8080/admin/ws.html"
I cant do anything or am I doing something wrong because, what is the path to connect to?

**Comment by gotthardp** [comment]
the path is what you entered: `/ws/uplink/00441018`

**Comment by netuserlv** [comment]
Yeah i tried that, but the connection doesnt do anything :/

**Comment by netuserlv** [comment]
and it shows me in the server http  error "/ws/uplink/00441018" doesnt exist

**Comment by gotthardp** [comment]
you are supposed to enter the URI to the ws.html

**Comment by netuserlv** [comment]
so I have to replace in the connector url "ws:" to "http://localhost:8080/admin/ws.html"

**Comment by gotthardp** [comment]
No. Create a connector, set URL to "ws:", enter the PublishUplinks as you did. Then, use a web browser to open http://localhost:8080/admin/ws.html and THERE enter the Path you used for PublishUplinks.

**Comment by netuserlv** [comment]
Yep, that doesnt work :/ I do all that when I make the connector with those settings as I did, then I go to the ws html page insert the path and press connection nothing happens :/ Btw Maybe I`am sounding a bit ungrateful, but that is not the case, You are the best for helping me and making this server :)

**Comment by netuserlv** [comment]
I`m using windows maybe that is the problem ?

**Comment by gotthardp** [comment]
Send me a screenshot of the Connector and of the ws.html after you clicked "Connect", please

**Comment by netuserlv** [comment]
![1](https://user-images.githubusercontent.com/35964652/35850403-62326688-0b2d-11e8-8b94-867020829e13.jpg)
![2](https://user-images.githubusercontent.com/35964652/35850405-637dd2e8-0b2d-11e8-9bd1-af4d9f5935b2.jpg)
![3](https://user-images.githubusercontent.com/35964652/35850408-64de5478-0b2d-11e8-82e6-3a8741db9918.jpg)

**Comment by gotthardp** [comment]
Did you click "Connection" on ws.html? There is supposed to be some text.

**Comment by netuserlv** [comment]
yep i pressed the connect :/on the ws.html

**Comment by netuserlv** [comment]
tried to change the types to nothing works....

**Comment by gotthardp** [comment]
that appears to be the problem. Would you mind opening a javascript debug console for ws.html?

**Comment by netuserlv** [comment]
![5](https://user-images.githubusercontent.com/35964652/35851018-595feb78-0b2f-11e8-9fb1-14f1a9d23fa9.jpg)

I hope this is the one

**Comment by gotthardp** [comment]
Aaaaaah. The connector has a "Failed" flag set to "topic". You should clear that flag.

**Comment by netuserlv** [comment]
Ammhhh ok. Do that is in the server or in the html file, I kinda don`t know how to do that :D

**Comment by gotthardp** [comment]
in the web-admin for Connector. There is a little cross after the "topic" flag. Click on that and then save the Connector.

**Comment by netuserlv** [comment]
ouhhhhh :D

**Comment by netuserlv** [comment]
Now i get text :D

**Comment by netuserlv** [comment]
I hope I wont have to bother you anymore :) big thanks from Latvia

**Comment by gotthardp** [comment]
As a next step you should change the Publish Uplinks = "/ws/uplink/{devaddr}" (without quotes) so that it works for any DevAddr

**Comment by netuserlv** [comment]
Ill do that :) any other tips?

**Comment by gotthardp** [comment]
No. Try and see :)
