### ISSUE TITLE
How much time?

### ISSUE THREAD

**Issue by gnob417** [gotthardp/lorawan-server#298]
Hi,
How much time is required from the time a packet is received by server(`lorawan_gw_forwarder`) to the time `lorawan_application_websocket` notice that the packet arrived?

it seems there is much latency about 1000ms..? 
am i right?

**Comment by gotthardp** [comment]
In 0.4.x there is a deduplication delay of 150 milliseconds. The server waits this time to receive the same frame from other gateways, so it is forwarded "shortly", i.e. few ms after that.

The 0.5 is a bit more clever and deduplicates only if the external application needs any of the following Fields: "freq", "datr", "codr", "best_gw", "all_gw". If the user did not request any of these fields, the frame is forwarded without waiting, usually in few ms.
