### ISSUE TITLE
Cayenne LPP

### ISSUE THREAD

**Issue by cristianhumelnicu** [gotthardp/lorawan-server#305]
Hi Petr and thank you for your wonderful work!

I think one integration with cayenne lpp format for decoding data, will be very useful for all of us...
In this momentI think  the parser is only for Semtech Nodes and that restricts very much the applicability of the server

Thank you again !
Cristian

**Comment by gotthardp** [comment]
You can always use an external connector and define your own handler functions.
What is Cayenne LPP?

**Comment by cristianhumelnicu** [comment]
Hi Peter ,

You can find  below more info about cayenne lpp 
https://github.com/myDevicesIoT/cayenne-docs/blob/master/docs/LORA.md

thx for answer me!

**Comment by gotthardp** [comment]
So you'd need to auto-parse the Cayenne payload and then send it to some other backend server, or to integrate with the Cayenne platform itself?

**Comment by gotthardp** [comment]
Hello. I made an implementation of the Cayenne parser, including documentation. It is configured via the **Payload** field in **Handler** config. Please check if it's what you expect.

**Comment by cristianhumelnicu** [comment]
Hi Petr , 

Ive look in to files and  yess !!! is seems to be what i need . Thank you a lot for that !

How can I integrate the new payload into loraserver? I installed loraserv on a windows machine as you indicated in the installation instructions.

What do I have to do next? My knowledge of erlang is zero.
Could you compile and put one new tar archive for windows with that function embedded ?
Thank you again!
Cristian

**Comment by gotthardp** [comment]
I made a pre-release of 0.5.1 here: http://swimgate.eu/lorawan-server-0.5.1.tar.gz

Download it, start it and then create a Backend Handler + Connector and set Handler Payload to "Cayenne"

**Comment by cristianhumelnicu** [comment]
Mean while i did install it on linux and rebuild inclusive cayenne lpp 

I try to figure out how to to payload functions for payload from the node 
01 02 014A   0202 4268
01 is port1 02 mean 2 bytes, 14A0 mean 33 in Hex (battery) , 02 mean port 2 , 02 mean 2 bytes, 4268 mean 1700 distance in HEX

Can you help me with that ?

Thank you Petr for all !!!!

**Comment by cristianhumelnicu** [comment]
I figure out  to replace semtech-node with my new applicatione defined in handlers and replace that in my node profiles ... now just try to use cayenne .. 

The functions for decoding is still need it or just select cayenne lpp and that is all ?

**Comment by gotthardp** [comment]
No need to define any decoding function. Just set Cayenne LPP and that's it.

**Comment by cristianhumelnicu** [comment]
Hi Petr
I did download pre-release of 0.5.1 from: http://swimgate.eu/lorawan-server-0.5.1.tar.gz and put it on the Windows ....

Payload to "Cayenne" on Handler is not availble .. yet ... Could you check again pls ?

Thx

**Comment by gotthardp** [comment]
Do you see the Payload field or not? If not, try cleaning the browser cache,

**Comment by cristianhumelnicu** [comment]
I did log in to server from other station and yes ... Now i see it ... 

What should i put at Uplink Fields ? devEUI and Data ? or more ?

**Comment by gotthardp** [comment]
No need to have there anything. Can be left empty.

**Comment by cristianhumelnicu** [comment]
Ok but where will i see data decoded ?

**Comment by cristianhumelnicu** [comment]
I try to send data to Cloudmqtt.com 

Without cayenne payload i recive 

out/0626880A | {"data":"0102014A02024204","devaddr":"0626880A","deveui":"00DA838C603CB283","freq":868.1}
-- | --

And with cayenne payload just 

events/0626880A | {"devaddr":"0626880A","deveui":"00DA838C603CB283"}
-- | --

**Comment by gotthardp** [comment]
This looks weird. You shouldn't be receiving uplinks on "events/0626880A". Is the Payload setting the only change you made?

**Comment by cristianhumelnicu** [comment]
yes...
![20180219_192654](https://user-images.githubusercontent.com/20617255/36390298-4c563208-15ab-11e8-85d9-8e2288aa6477.jpg)

**Comment by gotthardp** [comment]
With this settings you have to set `{devaddr}` as an uplink field.

**Comment by cristianhumelnicu** [comment]
I did ...

![20180219_192737](https://user-images.githubusercontent.com/20617255/36390592-4cf4d65a-15ac-11e8-8ca1-aac982c59e69.jpg)

**Comment by cristianhumelnicu** [comment]
An that is what i got from broker

![20180219_193406 2](https://user-images.githubusercontent.com/20617255/36390713-a7d9a654-15ac-11e8-844c-3fd9b9128d06.jpg)

**Comment by gotthardp** [comment]
Could you set the Payload to Cayenne and share with me the debug.log, please?

**Comment by cristianhumelnicu** [comment]
So i think the connector is ok 

When i put back from Payload Cayenne lpp all that i got is 


/events/0626880A | {"devaddr":"0626880A","deveui":"00DA838C603CB283"}
-- | --


Nothing more ....

**Comment by gotthardp** [comment]
the /events is not related to uplinks

**Comment by cristianhumelnicu** [comment]
debug log ...
[debug.log](https://github.com/gotthardp/lorawan-server/files/1737739/debug.log)

**Comment by cristianhumelnicu** [comment]
I know ... i suppose the /events is not related  with join node

**Comment by gotthardp** [comment]
My fault, sorry. Please 'git pull' or download the updated .tar.gz from the link I shared above and try again.

**Comment by cristianhumelnicu** [comment]
I will try on windows firs ... 
Just to be sure do i shall  downlink  from   http://swimgate.eu/lorawan-server-0.5.1.tar.gz 
Same file ?

**Comment by gotthardp** [comment]
Yes. Same file name, different content (I hope).

**Comment by cristianhumelnicu** [comment]
That is what i got with Payload Cayenne LPP on 

/events/0626880A	{"devaddr":"0626880A","deveui":"00DA838C603CB283"}
out/0626880A	{"data":"0102014A02023FEC","datr":"SF7BW125","devaddr":"0626880A","deveui":"00DA838C603CB283","fcnt":0,"freq":868.1,"lsnr":9.5,"rssi":-33,"field1":3.3,"field2":163.64}

**Comment by gotthardp** [comment]
Which is what you asked for, or? :) see the `field1` and `field2`.

**Comment by cristianhumelnicu** [comment]
yes :) i seen it now 
You are the best! Thank you a lot !

**Comment by gotthardp** [comment]
Cool. I am glad it works.

**Comment by cristianhumelnicu** [comment]
I think u just make a lot of people happy and them do not even know :)

Thank you again ... now im going happy at home !
