### ISSUE TITLE
lorawan-server.bat doestn't work

### ISSUE THREAD

**Issue by chunis** [gotthardp/lorawan-server#31]
Just found out the batch script does not work on my win7. And found the causes:
a. my erl.exe is located under folder "Program Files (x86)/" instead of "Program Files/".
b. my erl.exe has a suffix ".exe" instead of just call "erl". I guess if I make Win7 hides the suffix, maybe it will just be "erl", but not tested yet.

So I just replaced the first section of code with "set ERLDIR="C:\Program Files (x86)\erl8.1\bin\erl.EXE", and it works. Besides, my erl.exe is included in the %PATH%, so I think maybe we don't need to try to find the full path, but use "erl" or "erl.exe" is enough.

**Comment by gotthardp** [comment]
Thanks for reporting this. Some users have different environment and need %PATH%, some don't. It will take some time to cover all options. Reports like the one you made help a lot. Thanks again. I will fix this in a next release.

**Comment by gotthardp** [comment]
I made some changes to the BAT file. If you got a chance, please check whether it works for you now. Thanks.

**Comment by chunis** [comment]
Sorry for my checking late. Just want to confirm that this bug is fixed. Thanks.

**Comment by gotthardp** [comment]
Thank you for the confirmation!
