### ISSUE TITLE
Help with frame parser

### ISSUE THREAD

**Issue by jot4p** [gotthardp/lorawan-server#319]
Hello, 

I need help with frame parser.

my configuration is: 
https://imgur.com/a/ZZfX6 

```
fun(Fields, Payload) ->
  jsx:decode(Payload, [return_maps])
end. 
```

But my frame is partitioned... 

https://imgur.com/a/mRrSZ 

I need help to convert from new to old frame in MQTT. 

My server only send isolated frame (join moment) with "deveui" or "devaddr", but neve send this info with my payload frame. 

Thanks.

**Comment by gotthardp** [comment]
I am not sure I understand. What is "old" and "new" frame?

**Comment by jot4p** [comment]
New is the frame sended from your server .. old is the frame sended directly from my gateway+node red Json parser

**Comment by gotthardp** [comment]
I see. You will need to adapt your application to the new JSON structure. This is beyond the lorawan-server.

**Comment by jot4p** [comment]
But, here for example: https://imgur.com/KDliHht i have the DevAddr, Mac, Signal and frame data in the same line.. it's possible to use all this entries in my handler ?

**Comment by gotthardp** [comment]
I see. If you want those parameters, you need a slightly more complicated fun. Try:
```erlang
fun(Fields, Payload) ->
  maps:merge(Fields, jsx:decode(Payload, [return_maps]))
end. 
```

**Comment by jot4p** [comment]
Works. Thanks.
