### ISSUE TITLE
Improvement request - nodes description

### ISSUE THREAD

**Issue by jot4p** [gotthardp/lorawan-server#325]
Hello, 

It's 'possible to add nodes description in areas like "Nodes List" "Commisioned list" and "received frames" ?

for example "smart parking 1" .. "smart parking 2" .. " or "local x" .. "local y"

**Comment by gotthardp** [comment]
Yes, will do.

**Comment by jot4p** [comment]
thanks.

**Comment by gotthardp** [comment]
Done. Will be in 0.5.4
