### ISSUE TITLE
Send HTTP POST with handler

### ISSUE THREAD

**Issue by jot4p** [gotthardp/lorawan-server#326]
Hi, 

I'm trying to send HTTP post with your handler:

https://imgur.com/a/tAVi8

On my callback server, I get the frame:

127.0.0.1 - - [06/Mar/2018:10:20:23 +0000] "POST /?deveui=0004A30B001XXXX&payload={data} HTTP/1.1" 200 29874 "-" "-"

why data is not set ?

my received frame on server (lorawan):

Received | Application | DevAddr | MAC | U/L RSSI | U/L SNR | FCnt | Confirm | Port | Data
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
2018-03-06 10:30:57 | parking_frame_parser | 01DDA4ED | 00800000A00XXXX | -93 | 8 | 29 |   | 4 | 080A00001C00ECFA4XXXX

**Comment by jot4p** [comment]
Solved... It's necessary add "data" to Uplink Fields of my handler..

**Comment by gotthardp** [comment]
Correct. I love the errors that get solved before I have actually time to look at them. :)
