### ISSUE TITLE
Callback server compatibility

### ISSUE THREAD

**Issue by jot4p** [gotthardp/lorawan-server#333]
Hi,

I opened a new topic because I think many others have this doubt:

What are the steps to get a POST and get data available for a downlink?

For example:
At the windows command prompt:

```
curl -H "Content-Type: application/json" -X POST http://localhost:8080/callback/AAAAAAA -d "{\"data\":\"ABCDEFG\"}"
``` 

will this command send a post to a handler?

it's necessary create a connection with the "received topic" : **/callback/{devaddr}**

And after that ?  I'm wrong ?

Please I need documentation to do this..

**Comment by gotthardp** [comment]
Your example does not have Authentication. The following works for me:

```
curl -v --digest -uadmin:admin -H "Content-Type: application/json" -X POST http://localhost:8080/callback/11223344 -d "{\"data\":\"ABCDEFG\"}"
```

**Comment by jot4p** [comment]
Yes.. I solve the problem. The problem is that user and pw is based on user of server not user of handler.

**Comment by gotthardp** [comment]
I just updated the documentation to make it a bit clearer to other.
