### ISSUE TITLE
How to add network id in uplink field?

### ISSUE THREAD

**Issue by Apaisal** [gotthardp/lorawan-server#334]
Hi @gotthardp 

Could you advise how to add network id in uplink field?

**Comment by gotthardp** [comment]
Hello. This is not possible unfortunatelly.

**Comment by gotthardp** [comment]
Just a question @Apaisal , by "network id" you mean the name of the Network or the NetID parameter? What would you need to add and why?

**Comment by Apaisal** [comment]
Yes, I mean netid. It will represent name of the network.
I just interested multiple gateways in one network. Gateway has limitation
on area but network won't.
You can imagine it as Network Domain with GW group.

For example  ->  A network has 2 GW. First gateway in USA and second GW in
Europe. I called "LoRa Network Domain".

**Comment by gotthardp** [comment]
You know that for the OTAA devices that jpined over my server the upper bits of DevAddr correspond to the netit. That is not enough? You really need the netid?

**Comment by Apaisal** [comment]
I think, OTAA may be possible. But ABP was odd. Deveui insufficient for
huge massive who implement ABP. ABP is locked device to the network and ABP
device to be moved between networks.

**Comment by gotthardp** [comment]
I just added netid to the uplink fields. Will be in 0.5.4.
