### ISSUE TITLE
Unable to modify Gateway settings in Server Admin

### ISSUE THREAD

**Issue by romansoft** [gotthardp/lorawan-server#346]
After making changes to settings fields and pressing Save Changes, an error message appears :Data has changed. Please Reload and repeat the action.". Reloading and repeating causes the same error.

![image](https://user-images.githubusercontent.com/5790506/37877141-256091d0-301c-11e8-92e0-7090274c518c.png)

**Comment by gotthardp** [comment]
What server version are you using?

**Comment by gotthardp** [comment]
Could your gateway be sending stats more often? The server stores stats, so if you edit a gateway info you should do that before it sends new stats. This is a known limitation.

**Comment by romansoft** [comment]
I'm using the gateway PF config settings recommended in the larawan-server documentation. Also, this happens even with gateway being disconnected.

**Comment by gotthardp** [comment]
Yeah, you are right. This is related to the "status" field, which includes a disconnection time, increasing every 20 secs. I made a minor enhancement that could reduce the occurrences to a satisfactory level.
