### ISSUE TITLE
Server/Gateway to node downlink communication

### ISSUE THREAD

**Issue by gmbankar37** [gotthardp/lorawan-server#351]
How can send data from Server/Gateway to the node device( LoRa RAK811 module) connected to a RPi3? I read about it and got to know it should be send from the application server. But I don't see any such feature here. Please help me out. Sorry this is not an issue and I am just inquiring. Thank you.

**Comment by gotthardp** [comment]
Hello. Start with https://github.com/gotthardp/lorawan-server/blob/master/doc/Introduction.md#downlink

**Comment by gmbankar37** [comment]
Hello,
Thank you. for the document provided. I did read the document provided by
you. I wanted to know that can I send a downlink signal from the lorawan
server without the backend server addition?

Gaurav Bankar

**Comment by gotthardp** [comment]
What is your use-case? What do you want to be the trigger of the downlink?

**Comment by gmbankar37** [comment]
My LoRa node is connected to a data monitoring device and I want to send
the data through gateway to a server where I can see the data. For now I
want to send data to node and see if it can receive it and I can see it. I
might want to send a query in future for retrieve a specific data. Also I
haven't done any coding in Erlang so its difficult to modify the already
existing code.
So If I have to develop external application according to my requirement do
I have to write entirely different Erlang code ?

**Comment by gotthardp** [comment]
For such tests I'd recommend to use the web socket demo application (see the Connectors guide).

**Comment by gmbankar37** [comment]
Hey how do I change the band? I changed the network from EU868 tp IN865 but
the node still shows EU868.

**Comment by gotthardp** [comment]
Where does the node show EU868?
The firmware is region specific, i.e. you cannot switch the region as recognized by the end-device from the server side. You need to reconfigure/change your firmware.

**Comment by gmbankar37** [comment]
Hello,
 I am trying to have a websocket server on the lorawan-server. Do I have to
add the demo client page anywhere inside the source file of the
lorawan-server ?
 when I enter this URL ws://server:8080/ws/uplink/<DevAddr> in browser it
shows error as page not found or site cant be reached according to the
screen shot attached.

Thank you,
Gaurav Bankar

**Comment by gotthardp** [comment]
https://github.com/gotthardp/lorawan-server/blob/master/doc/Connectors.md#demo-page

**Comment by gmbankar37** [comment]
I have followed the same link/document you gave me. When I complete
everything setting up the handler and connector I am not able to connect to
the websocket. Also the demo app gives error. Please look at the
screenshots to see if I have made any mistake during setup.

**Comment by gotthardp** [comment]
I don't see any screenshots.

**Comment by gmbankar37** [comment]
![2](https://user-images.githubusercontent.com/37892112/38241736-9c61e424-3750-11e8-9fb7-f920162969d8.JPG)
![3](https://user-images.githubusercontent.com/37892112/38241737-9ca81aa2-3750-11e8-93e9-8b3dff1dfd29.JPG)

**Comment by gmbankar37** [comment]
![1](https://user-images.githubusercontent.com/37892112/38241866-ef784d1a-3750-11e8-82fd-b640511bdb21.JPG)

**Comment by gotthardp** [comment]
Sir, the instructions I sent you say you should enter `http://127.0.0.1:8080/admin/ws.html` and put the `/ws/events/...` URI there.

**Comment by gmbankar37** [comment]
The lorawan-server as websocket says The *Subscribe* and *Received Topic*
fields are not used and can be left empty. But if the received topic is
empty I will not be able to send downlink message. So do I have to make
changes in the demo client or the handler to make it happen?

**Comment by gotthardp** [comment]
For WS there is only one URI: you connect to it, receive uplinks and send downlinks. The MQTT works differntly so it needs also the sub/rec topics; WS doesn't.

**Comment by gmbankar37** [comment]
Hi,
  I was able to send data from demo client.  As my lorawan-server acts as
Websocket it should receive the data. But I am not able to see the data in
the received frames. So the data I am sending through demo client is that
downlink or uplink? Thank you.

**Comment by gmbankar37** [comment]
So where can I see this data ? In the downlink of activated nodes ?

**Comment by gotthardp** [comment]
For class A, before sent, messages are listed on the node page. Otherwise the downlinks are not stored.

**Comment by gotthardp** [comment]
The request to long and display downlinks is now Issue #362.
I believe the other questions were clarified, so I am closing this.
