### ISSUE TITLE
Unexpected mtype 3

### ISSUE THREAD

**Issue by psgenn** [gotthardp/lorawan-server#352]
Hi, I'm trying to send confirmation messages and the server gives an error "Unexpected mtype 3". What am I doing wrong?

`Apr 01 09:13:10 raspberrypi lorawan-server[13150]: 09:13:10.249 [error] <<"11111111">> Unexpected mtype 3
`

![image](https://user-images.githubusercontent.com/16066592/38171843-3d7efdf6-35b2-11e8-8089-4095b3d2eb74.png)
![image](https://user-images.githubusercontent.com/16066592/38171848-4a11d3a4-35b2-11e8-83bb-b8525241bdf4.png)
![image](https://user-images.githubusercontent.com/16066592/38171912-d7a9b758-35b3-11e8-8ca6-413245f836ca.png)

**Comment by gotthardp** [comment]
How do you send the mtype 3 messages?

**Comment by psgenn** [comment]
I do not do anything for this. I'm using the firmware version from the http://www.st.com/content/st_com/en/products/embedded-software/mcus-embedded-software/stm32-embedded-software/stm32cube-expansion-packages/i-cube-lrwan.html

**Comment by gotthardp** [comment]
MType=3 is "unconfirmed downlink". This is sent by the server, so if your device sends MType=3, it is apparently malfunctioning.
