### ISSUE TITLE
Info on erlang fun

### ISSUE THREAD

**Issue by webfrank** [gotthardp/lorawan-server#353]
Hi,
   I'm trying to connect NKE Watteco end devices, one Temp/Hum and one Current. They use a proprietary ZCL protocol and I need to decode the incoming message based on some previous decode byte.
   Could you provide with some sample?

**Comment by gotthardp** [comment]
Hi. Some examples are here:
https://github.com/gotthardp/lorawan-server/blob/master/doc/Handlers.md#parse-uplink

**Comment by webfrank** [comment]
Hi, yes I know the basics of parsing binary data but I would like to implement some logic like if valueA==0x8A parse this way otherwise parse the other way. Is it possible?

**Comment by gotthardp** [comment]
It's always possible, but ZCL is a bit complex, so writing a fun might not be the most convenient option. An alternative would be to add ZCL to the supported protocols, if possible, and implement it natively inside the server just like Cayenne.

**Comment by webfrank** [comment]
Knowing how to do it :) I think I will decode data server side.

**Comment by gotthardp** [comment]
And don't forget that contributions are always welcome ;-)
