### ISSUE TITLE
Profile cannot be saved without providing RX2 Freq

### ISSUE THREAD

**Issue by altishchenko** [gotthardp/lorawan-server#358]
Device profile cannot be saved without specifying the 'Set RX2 Freq'. As it states in the docs the initial settings are inherited from the Network configuration and are provided in the profile to augment a particular set of devices.

Server: Today's master branch self compile.
OS: Ubuntu, MacOS.

**Comment by gotthardp** [comment]
Fixed. Thanks for reporting this.
