### ISSUE TITLE
GMT time on frame

### ISSUE THREAD

**Issue by jot4p** [gotthardp/lorawan-server#359]
Hello, 

My server time is not equal to mqtt frame datetime ... it's possible to be the same ? 

Example, my server time, server time and received frame time is 15h00 and my mqtt datetime is 14h (GMT) not (GMT+1)

**Comment by gotthardp** [comment]
The server operates in UTC. Most of the values shown on the web-admin are converted to local time, but everything in messages remains UTC and has to be converted by the user, if needed.
