### ISSUE TITLE
Refreshing Received Frames

### ISSUE THREAD

**Issue by batulzii** [gotthardp/lorawan-server#36]
Hi Petr,
There are 2 pages, that contains received frames. Received frames displaying correctly, but refresh done manually. Cool, if data refreshed automatically.
Kind Regards!

**Comment by gotthardp** [comment]
It would be cool to auto-refresh the lists, but my current knowledge of Angular and ng-admin is not sufficient to implement it.

**Comment by kazi93** [comment]
@gotthardp I would like to work with it or at least test how it works! :) . I will write you in private for instruction. :)

**Comment by gotthardp** [comment]
I asked for help at http://stackoverflow.com/questions/43171429/automatically-refresh-fields
Feel free to dig into this problem and propose a solution.

**Comment by gotthardp** [comment]
You may want to start with the Dashboard first. I think the auto-refresh would be most useful there.

**Comment by kazi93** [comment]
@gotthardp Could you please share the link or the source code for refreshing "Received Frames"? Many thanks.

**Comment by gotthardp** [comment]
The source is in https://github.com/gotthardp/lorawan-server/blob/master/priv/admin/admin.js, but it does not refresh and I have no clue how to do it in a clean way.

There is a dirty way to reload the entire page every few seconds, but this is **not** the clean way I have in mind.

**Comment by gotthardp** [comment]
With the dashboard timeline I don't think this is needed anymore.
