### ISSUE TITLE
device setting problem(by API) - application setting

### ISSUE THREAD

**Issue by nuguri618** [gotthardp/lorawan-server#360]
Hi,

I try to create device or node on LoRaWAN network server by API.
But Still how to add application by API.

I post new device by postman with this json body

[{'deveui': '100000000000EE04','region':'US902-928','application':'backend',
    'appeui':'0000000000000003', 'appkey':'92DF10F2C45208F050DA785D70075DE6'}]
But only application can't set up on network server.
is it possible by original API? or need some other thing?

**Comment by gotthardp** [comment]
Everything you can do via web-admin can be done via API too.

**Comment by nuguri618** [comment]
my json is incorrect?.. only application can't setting...

**Comment by gotthardp** [comment]
Which server version are you using?

**Comment by nuguri618** [comment]
I use version 0.4.13..

**Comment by gotthardp** [comment]
What exactly do you want to achieve? What are you doing and how does the system react?

**Comment by nuguri618** [comment]
I want to register device by API. but only application cannot setting by API.
I use this Json.
[{'deveui': '100000000000EE03','region':'US902-928','application':'backend',
'appeui':'0000000000000003', 'appkey':'92DF10F2C45208F050DA785D70075DE6'}]

and check on web.
![image](https://user-images.githubusercontent.com/17840689/38409538-c2aa8e1a-39bc-11e8-9a89-9129bb61f6b7.png)

**Comment by nuguri618** [comment]
Thanks.. I got it! It works!
