### ISSUE TITLE
Feature request: Gateway Timestamp

### ISSUE THREAD

**Issue by webfrank** [gotthardp/lorawan-server#372]
From Semtec Packet Forwader protocol the network server will receive three timestamps:
```
 time | string | UTC time of pkt RX, us precision, ISO 8601 'compact' format
 tmms | number | GPS time of pkt RX, number of milliseconds since 06.Jan.1980
 tmst | number | Internal timestamp of "RX finished" event (32b unsigned)
```
but on mqtt payload I have only the first. I would like to receive also tmms (if available) and tmst which is always available.

**Comment by gotthardp** [comment]
I wonder why? The tmst is an internal gateway number used only to schedule downlinks.

**Comment by webfrank** [comment]
Hi, I agrre with you but I was looking for a timestamp useful to 
geolocate a node. Is it possible to have a field with epoch with micro 
seconds as an mqtt field?

I would like to triangulate using RSSI and timestamp of received packet.


Il 16/04/18 17:28, Petr Gotthard ha scritto:

**Comment by gotthardp** [comment]
I added the `tmms` field. Would you be able to test it before I do a release?

**Comment by webfrank** [comment]
Yes, I’ll test soon

Inviato da iPhone

**Comment by gotthardp** [comment]
in 0.5.4

**Comment by webfrank** [comment]
In 0.5.5 Docker is not present

**Comment by gotthardp** [comment]
I see both the `release-0.5.4` and the `latest` tag.
