### ISSUE TITLE
Require lorawan-server version and build revision on header or footer page

### ISSUE THREAD

**Issue by Apaisal** [gotthardp/lorawan-server#373]
Hello  @gotthardp 

I require show lorawan-server version and build revision on header or footer page feature.
I think it convenient for debug when forker send screenshot to create issue ticket. because it's basic information.

**Comment by gotthardp** [comment]
Franky speaking, people often send only a snipplet of a screen, not always the entire screen, so adding a version number wouldn't help. It's displayed in the dashboard, so people can view it if they want.
