### ISSUE TITLE
What sub ID format?

### ISSUE THREAD

**Issue by Apaisal** [gotthardp/lorawan-server#374]
What sub id format?
![0_5_4_whatsubidformatcapture](https://user-images.githubusercontent.com/1174037/38984310-89c2b59e-43f0-11e8-8729-0335153ef8ed.PNG)

I put "0:3" in sub id field and server invalid that format. Then I change it to "00:3", server accepted!!!

**Comment by gotthardp** [comment]
The HexValue must have an even number of hex-digits.
I clarified this in the documentation.
