### ISSUE TITLE
Login server on mobile

### ISSUE THREAD

**Issue by Apaisal** [gotthardp/lorawan-server#375]
![mobile login screenshot_20180419-164443](https://user-images.githubusercontent.com/1174037/38984734-ad3c902a-43f1-11e8-9f13-ce006439bb87.jpg)
Login server on mobile and login popup page still popup.
I tested this issue on samsung galaxy A8 with google chrome app and same result on samsung browser.

**Comment by gotthardp** [comment]
True,

**Comment by gotthardp** [comment]
I made a fix that could help. Would you be able to test the latest master, or you need to wait for a release?

**Comment by Apaisal** [comment]
Thank you. I will test it. What is commit id to valid?

**Comment by gotthardp** [comment]
https://github.com/gotthardp/lorawan-server/commit/99dcb729d3e99a79905918c63dde8f1666867a0f

**Comment by gotthardp** [comment]
I did not forget about this. I just don't know where is the problem. I keep trying.

**Comment by gotthardp** [comment]
@Apaisal, I may have fixed this problem. It would be great if you could pull the latest master and check it out. (I recommend starting it from a new directory so you don't destroy your existing database,)

**Comment by gotthardp** [comment]
I tested this on many devices and I believe it is really fixed now.
