### ISSUE TITLE
no mqtt publish upon u/l receive

### ISSUE THREAD

**Issue by stefanobimbo** [gotthardp/lorawan-server#378]
I configured a connector to publish received u/l messages in an mqtt topic (I use mosquitto), but my subscribers don't receive anything when an u/l message is received (I am sure the message is received because I see it in the Received Frames).
Using moquitto_pub I tried to publish something manually to the same topic and I am sure the mqtt broker is working OK (every subscribed client received it).
I am a bit confused about connector authentication. should I use Username+Password with related fields filled up with something that is not an empty string? Should I configure mosquitto to use the same user/password in its config file?

Is there something I can give you to check my lorawan-server configuration parameters?

thanks

**Comment by gotthardp** [comment]
Any errors in the server log? By default no username/password is required.
You can share with me either the screenshots, or the JSON files http://server/api/handlers and http://server/api/connectors

**Comment by stefanobimbo** [comment]
Nothing in the server log. Looking at the mosquitto log, I don't see connections from server, so I think is can be a configuration problem.
I use a device that joins OTAA to network, but the same problem is for ABP nodes. All configured parameters follows:
![profile](https://user-images.githubusercontent.com/31661872/39175782-791bc104-47ab-11e8-80d2-6bae023aa890.png)
![profile_adr](https://user-images.githubusercontent.com/31661872/39175803-8b9f0818-47ab-11e8-8b1b-e5ef0e79f6a9.png)
![device_commissioned](https://user-images.githubusercontent.com/31661872/39175833-9b3bf36c-47ab-11e8-8a51-38d4c6d473c4.png)
![node_activated](https://user-images.githubusercontent.com/31661872/39175841-9ea02960-47ab-11e8-85d6-2d3ba14b5fdc.png)
![node_activated_adr](https://user-images.githubusercontent.com/31661872/39175844-a18dadfa-47ab-11e8-968a-568e27718745.png)
![node_activated_status](https://user-images.githubusercontent.com/31661872/39175849-a4046600-47ab-11e8-8959-aa3efac087da.png)
![handler](https://user-images.githubusercontent.com/31661872/39175860-ac20ec82-47ab-11e8-81e5-881e320ac039.png)
![connector_general](https://user-images.githubusercontent.com/31661872/39175862-aec7ebe8-47ab-11e8-8e4c-1ce357eb8267.png)
![connector_authentication](https://user-images.githubusercontent.com/31661872/39175870-b104f59a-47ab-11e8-98c8-86a2a3c0d89b.png)
![received_frames](https://user-images.githubusercontent.com/31661872/39175883-b5561d54-47ab-11e8-84b0-36c9050fdd0b.png)

**Comment by stefanobimbo** [comment]
Removing failed flags works OK.
There's only one thing to remark: why could I set flags from web interface?

**Comment by stefanobimbo** [comment]
yes, issue is closed.

many thanks
