### ISSUE TITLE
Use this lorawan server with microchip note

### ISSUE THREAD

**Issue by Gligor721** [gotthardp/lorawan-server#380]
I am using this lorawan server but version 0.4.1 
I want to use the latest version 0.5.3 but I saw that this version uses semtech  note. I am using microchip note.
I can see you have a demo app for microchip note. Can I use this latest version of lorawan server with that microchip note?

Looking forward your response.
Best regards
Gligor

**Comment by gotthardp** [comment]
Hello. The sample applications are just sample applications doing nothing useful. If you build your own data parsing apps you can easily use the standard 0.5.x with your mote. If you want to use the demo microchip app, then you should download the demo app and use that. The server is included in it, so it should be straightforward to use.

**Comment by Gligor721** [comment]
How to solve this error:
12:13:57.574 [error] node 001A2603 {unexpected_data,{frame,1,<<0,26,38,3>>,0,0,0,14,<<>>,1,<<"1">>}}
?
thanks for support

**Comment by Gligor721** [comment]
unexpected_data means the keys are configured well, but you set the application to 'SemtechMote' or 'MicrochipMote' although your device is sending some other data. Change the 'Application' field to 'WebSocket' for example to get rid of this.
I dont have 'WebSocket' to change.I use microchip note.

**Comment by gotthardp** [comment]
What microchip mote application are you using?

**Comment by Gligor721** [comment]
RN2483

**Comment by gotthardp** [comment]
That's a name of the module, not the application running inside.

**Comment by Gligor721** [comment]
http://www.microchip.com/Developmenttools/ProductDetails.aspx?PartNO=dv164140-1

**Comment by Gligor721** [comment]
http://www.microchip.com/DevelopmentTools/ProductDetails.aspx?PartNO=dm164138

**Comment by Gligor721** [comment]
I use websocket as application in lorawan-server 0.4.1 and all is working fine.Now I want to use the latest version of the web server and I install via microchip demo app.But now i get this error!

**Comment by gotthardp** [comment]
You can use websocket also in the latest version. It's still there, only configured differently.

**Comment by Gligor721** [comment]
How to use can you help me with that?

**Comment by gotthardp** [comment]
Create a Handler and then a websocket Connector
https://github.com/gotthardp/lorawan-server/blob/master/doc/Connectors.md#web-sockets

Then reference the Handler in your device Profile.

**Comment by Gligor721** [comment]
14:06:28.546 [debug] DataRate 001ADD59 switched to dr 2
14:06:28.547 [debug] 001ADD59 <- [dev_status_req]
14:06:34.185 [warning] Message not sent to any connector
14:06:34.386 [debug] DataRate 001A57FD switched to dr 2
14:06:34.386 [debug] 001A57FD <- [dev_status_req]
14:06:41.612 [warning] Message not sent to any connector
14:06:41.813 [debug] DataRate 001A1ECC switched to dr 1
14:06:41.813 [debug] 001A1ECC <- [dev_status_req]

**Comment by Gligor721** [comment]
here is the config
![screenshot from 2018-04-30 14-07-57](https://user-images.githubusercontent.com/6072347/39426419-0694dcb8-4c80-11e8-88fe-b4053f8a3f76.png)
![screenshot from 2018-04-30 14-08-16](https://user-images.githubusercontent.com/6072347/39426428-1070c0ee-4c80-11e8-897d-f34fb7d8875d.png)

**Comment by gotthardp** [comment]
Set Publish Uplinks to a URL pattern starting with a slash, e.g. '/ws/uplink/{devaddr}'
To connect to the WebSocket, then open URL to the path you defined, i.e. ws://server:8080/ws/uplink/<DevAddr>.

**Comment by Gligor721** [comment]
How to send message to note via web socket?

**Comment by gotthardp** [comment]
Send a JSON to your web-socket
https://github.com/gotthardp/lorawan-server/blob/master/doc/Handlers.md#downlink

**Comment by Gligor721** [comment]
=CRASH REPORT==== 30-Apr-2018::15:16:22 ===
  crasher:
    initial call: cowboy_clear:connection_process/5
    pid: <0.1232.0>
    registered_name: []
    exception error: no function clause matching 
                     lorawan_connector:decode(<<"www-form">>,
                                              <<" {\"devaddr\":\"001A2603\", \"data\":\"31313131\"}">>) (/home/lorawanserver/Documents/lorawan-server-demoapp-master/_build/default/lib/lorawan_server/src/lorawan_connector.erl, line 177)
      in function  lorawan_connector:decode_and_downlink/3 (/home/lorawanserver/Documents/lorawan-server-demoapp-master/_build/default/lib/lorawan_server/src/lorawan_connector.erl, line 169)
      in call from lorawan_connector_ws:handle_downlink/2 (/home/lorawanserver/Documents/lorawan-server-demoapp-master/_build/default/lib/lorawan_server/src/lorawan_connector_ws.erl, line 103)
      in call from cowboy_websocket:handler_call/6 (/home/lorawanserver/Documents/lorawan-server-demoapp-master/_build/default/lib/cowboy/src/cowboy_websocket.erl, line 385)
      in call from cowboy_http:loop/2 (/home/lorawanserver/Documents/lorawan-server-demoapp-master/_build/default/lib/cowboy/src/cowboy_http.erl, line 201)
    ancestors: [<0.294.0>,<0.293.0>,ranch_sup,<0.98.0>]
    message_queue_len: 0
    messages: []
    links: [<0.294.0>,#Port<0.4772>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 10423
  neighbours:
15:16:22.107 [error] CRASH REPORT Process <0.1232.0> with 0 neighbours crashed with reason: no function clause matching lorawan_connector:decode(<<"www-form">>, <<" {\"devaddr\":\"001A2603\", \"data\":\"31313131\"}">>) line 177
15:16:22.108 [error] Ranch listener http terminated with reason: no function clause matching lorawan_connector:decode(<<"www-form">>, <<" {\"devaddr\":\"001A2603\", \"data\":\"31313131\"}">>) line 177

**Comment by gotthardp** [comment]
Can you switch your Connector to Format JSON (not Web Form)? Downlink via Web Forms are not implemented (hence the error).
