### ISSUE TITLE
access the lorawan gateway GPS position 

### ISSUE THREAD

**Issue by pdl86** [gotthardp/lorawan-server#391]
Hello 

is there a way to access the GPS coordinate of the lorawan gateways ? ( from the lorawan server) 
may be via a specific handler , tied to gaetway ( vs devices) ? 

thanks in advance 
regards
Philippe

**Comment by gotthardp** [comment]
There is a REST API, so you can send a HTTP GET request to retrieve a JSON that includes all gateway data, including the position. This is what you want?
Or you want to get it in the handler data, so your backend application can use the values?

**Comment by gotthardp** [comment]
Closing an inactive issue.
