### ISSUE TITLE
Gateway showing disconnected (RPi3)

### ISSUE THREAD

**Issue by gmbankar37** [gotthardp/lorawan-server#392]
Hello,
 I have my gateway on the host raspberrypi 3 and It is connected to wifi. I have completed all the necessary procedure or changes in the packet forwarder _config.json files.  But my gateway is showing status disconnected. I am not able to connect my gateway to the server. And because my gateway is not online I cant join the node. PLease  help me.

**Comment by gotthardp** [comment]
Are you able to "ping" from the Raspberry to the server IP address you did put to the config.json?

**Comment by gmbankar37** [comment]
Actually I am providing internet to RPi3 through mobile hotspot so the
wlan0 ip address keeps changing. Yeah I am able to ping to the wlan
address.

**Comment by gmbankar37** [comment]
Do my server always have to be connected to the internet? I mean does the
packet forwarder uses TCP to forward the data from gateway to the server?
Thank you.

**Comment by gotthardp** [comment]
UDP is used between the gateway and the server, so both may be disconnected for a while and the connectivity is automatically restored when they come back,

**Comment by gotthardp** [comment]
If you can ping, you correctly configured both IP and also the port number of the server then it shall work.

**Comment by gmbankar37** [comment]
But can we still send packet and receive it when the connectivity is not
there? Do I need to make changes in the global_conf.json file of the packet
forwarder?

**Comment by gmbankar37** [comment]
Hii,
 If I am sending a Modbus frame from node to gateway what should I prefer
internal (In Erlang) or external( handler) application ? How do I modify
the existing semtech-mote application to my requirement? Thank you.

**Comment by gotthardp** [comment]
The benefits of an internal application are described at https://github.com/gotthardp/lorawan-server-demoapp

**Comment by gmbankar37** [comment]
Hii, I am still facing this problem that my gateway shows disconnected. I need to solve this issue so I can do range testing. Please help.

**Comment by gmbankar37** [comment]
I have solved the issue that my gateway is connected now. But I am not able to join my node. It constantly gives me 
at+recv = 6,0,0.
which is Status_RX2_TimeOUT. 
I am following the same procedure which I followed on my RPi 2. But not able to join. 
This status usually means I have configured something wrong. Are my network parameters wrong?

**Comment by gotthardp** [comment]
What was the solution to the previous problem, please?

To fix the join problem, please follow the "No downlink" guide https://github.com/gotthardp/lorawan-server/blob/master/doc/Troubleshooting.md#no-downlink-frames-delivered

**Comment by gmbankar37** [comment]
I had the server and gateway setup on my RPi2 first and it had a mac id. I
used the same mac id as the previous one when I was having different host
(RPi3) to same gateway. This way it worked.

**Comment by gmbankar37** [comment]
Should I change the TX chain to 1 so I will enable the radio_1. And then match my network setting to that of radio_1. So then the frequency setting in radio_1 should match with the initial RX2 freq? Am I correct? 
I am not able to understand this statement "Private networks should use 000000 or 000001" as NetID

**Comment by gotthardp** [comment]
Set the TX chain to whatever radio in your gateway is configured for transmitting. Yes, the config your your radio shall match the server config.

The LoRaWAN specification requires the non-public (i.e. private networks) to use the NetID 000000 or 000001. All other NetIDs are reserved for public networks and allocated by the LoRaWAN alliance.
