### ISSUE TITLE
Unknown frame - add as valid device

### ISSUE THREAD

**Issue by jot4p** [gotthardp/lorawan-server#395]
Hi, 

When I try to install a new device, if my new device is not "commissioned" or "activated" I receive the "Unknown frame" ... it's possible to know more info about this frame ? for example the DevEUI or DevAddr, AppEUI or other ? in order to identify what device is talking..  

thanks.

**Comment by gotthardp** [comment]
"Unknown frame" means the device is sending non-standard frames. This is a protocol violation and since the protocol is not followed there is no way to retrieve any ID from the frame.

**Comment by jot4p** [comment]
ok.. thanks.
