### ISSUE TITLE
How to setup EU868 all 8 Channels 

### ISSUE THREAD

**Issue by hallard** [gotthardp/lorawan-server#399]
Hi there
I need to use all EU868 channels but I don't know how to handle them

My lopy is set as follow and with OTAA
![image](https://user-images.githubusercontent.com/2471931/40498150-8152a992-5f7e-11e8-840e-72ba20589021.png)

Do I need to do anything on server (0.5.4) and if so, how do I add them?

Is it something like that, not sure on value format to put in Min/Max Data Rate
![image](https://user-images.githubusercontent.com/2471931/40498233-bf27f4fc-5f7e-11e8-94f6-bc03a17ba2db.png)

Thanks

**Comment by gotthardp** [comment]
Yes, this is exactly the setting you need to provide. It's even identical to your lopy config! Do I really need to explain that your "dr_min" requals to my "Min Data Rate"?
Note also that you have to set "Initial Channels" to `0-7`.

**Comment by gotthardp** [comment]
Note also that your frequency is in Hz, but my is in MHz. Make sure you use correct units.

**Comment by hallard** [comment]
Correct, got it thanks,
As documentation for data rate state " If not specified, equals to the global value on the ADR tab." and on the ADR tab it's like that 
![image](https://user-images.githubusercontent.com/2471931/40500414-f58eaf80-5f84-11e8-8ed1-d418d2bad700.png)
I was not sure what format to use.
