### ISSUE TITLE
decoding payload 

### ISSUE THREAD

**Issue by cristianhumelnicu** [gotthardp/lorawan-server#400]
Hi Petr,
Could you tell me please , what is equivalent expresion in erlang to js next decoder? 

// Decode decodes an array of bytes into an object.
//  - fPort contains the LoRaWAN fPort number
//  - bytes is an array of bytes, e.g. [225, 230, 255, 0]
// The function must return an object, e.g. {"temperature": 22.5}
function Decode(fPort, bytes) {
  return {};
}

Thank you !

**Comment by gotthardp** [comment]
https://github.com/gotthardp/lorawan-server/blob/master/doc/Handlers.md#parse-uplink
