### ISSUE TITLE
Please help me with setuping lorawan network through windows

### ISSUE THREAD

**Issue by shyam-coder** [gotthardp/lorawan-server#401]
Before submitting a bug report please
 - read the Troubleshooting documentation;
 - make sure you are running the latest stable release;
 - inspect the debug.log to check if there are some warnings or errors reported.

**Comment by shyam-coder** [comment]
I am unable to find the way to set

**Comment by gotthardp** [comment]
If you need more detailed answer, please provide more detailed question.

**Comment by shyam-coder** [comment]
Thank you I will try

**Comment by shyam-coder** [comment]
thank you so much bro

**Comment by shyam-coder** [comment]
my question is Iam currently having a gateway and nodes based on arduino
,so when I see in loraserver.io website it have instructions and links for
ubuntu so I was need of help to do the same setup with windows.

**Comment by shyam-coder** [comment]
gateway based on pic

**Comment by gotthardp** [comment]
loraserver.io is a different server
the instructions on how to install my server on windows are here: https://github.com/gotthardp/lorawan-server/blob/master/doc/Installation.md#using-the-binary-release-on-windows

**Comment by shyam-coder** [comment]
Oh sorry, thanks again.

**Comment by shyam-coder** [comment]
how to install gateway,appserver in windows,server worked well

**Comment by gotthardp** [comment]
I cannot help you with that. Installation of the gateway software depends on the hardware you have. Please contact your gateway supplier.

**Comment by shyam-coder** [comment]
Ok
