### ISSUE TITLE
Server crashed with misconfigured connector

### ISSUE THREAD

**Issue by gmbankar37** [gotthardp/lorawan-server#402]
Before submitting a bug report please
 - read the Troubleshooting documentation;
 - make sure you are running the latest stable release;
 - inspect the debug.log to check if there are some warnings or errors reported.

**Comment by gmbankar37** [comment]
Hello, 
  My server crashed and I am not able to load/start it again. The crash report is as
[crash.log](https://github.com/gotthardp/lorawan-server/files/2046869/crash.log) . Do I need to build the server again?

**Comment by gotthardp** [comment]
You made an error in the configuration. Your "MQTT_PI" has a pattern "out/{00000AB1}", but "00000AB1" is not a valid pattern name. Hence the crash. It shall not be so devastating (I will fix that), but the rootcause is the misconfiguration. You can try stopping the server, deleting the "connectors" database file and restarting the server again.

**Comment by gmbankar37** [comment]
Yes I will do that. So you want me to delete connectors.DCD file. But I followed the document and “out/{devaddr}” is the pattern given and 00000AB1 is my devaddr. Is my devaddr itself incorrect? 
 
Sent from Mail for Windows 10

**Comment by gotthardp** [comment]
Yes, please-- delete the connectors.DCD file
It's a pattern, so you shall use `{devaddr}` as is. The devaddr will be replaced automatically by the server.

**Comment by gotthardp** [comment]
Will be more robust in v0.5.5
