### ISSUE TITLE
Debug log file not updating

### ISSUE THREAD

**Issue by gmbankar37** [gotthardp/lorawan-server#403]
hii,
 My debug log file is not updating though crash and error files are working fine. Here is the code 
in my sys.config file. 
% error logging settings
{lager, [
    {colored, true},
    % uncomment to display even a high number of messages per second
    % see https://github.com/erlang-lager/lager#overload-protection
    % {error_logger_hwm, undefined},
    {handlers, [
        {lager_console_backend, [{level, debug}]},
        {lager_file_backend, [{file, "debug.log"}, {level, debug}]},
        {lager_file_backend, [{file, "error.log"}, {level, error}]}
    ]},
    {crash_log, "crash.log"}
]},
{sasl, [
    {errlog_type, error}
]}].
please help me. Thank you.

**Comment by gotthardp** [comment]
It seems that the process does not have access to that file. Wrong permissions? Disk full?

**Comment by gmbankar37** [comment]
It shows the disk_almost_full. How can I solve this problem?
