### ISSUE TITLE
MQTT connector- node red

### ISSUE THREAD

**Issue by gmbankar37** [gotthardp/lorawan-server#404]
Hi ,
I am trying to send the data coming at my gateway to a modbustcp server through mqtt in node-red. I have configured the handler and connector files. My mqtt broker shows disconnected in node-red. Also I have no idea what the handler is exactly doing. I mean do I keep format as ASCII or write my own parse uplink logic. And from where and how exactly is my handler taking data to send to a outside server. 
![nodered](https://user-images.githubusercontent.com/37892112/40702747-9b69066a-6400-11e8-9cf0-aafa15fc9e79.png)
![handler](https://user-images.githubusercontent.com/37892112/40702764-ae29b862-6400-11e8-8c19-db1a278cd2db.JPG)
![connector](https://user-images.githubusercontent.com/37892112/40702778-b6731db0-6400-11e8-82b0-98903e6f07d7.JPG)

**Comment by gotthardp** [comment]
It depends on what your device is sending. If it's sending ASCII Text, set the Payload to ASCII and leave the Parse Uplink empty. If it's sending some binary structure that you want to decode, leave Payload empty and set some Parse Uplink function.
https://github.com/gotthardp/lorawan-server/blob/master/doc/Handlers.md#administration

**Comment by gmbankar37** [comment]
For my external application to be working do I have to disable my internal
application?

**Comment by gotthardp** [comment]
As long as you assign different names to the different applications all can be enabled.
