### ISSUE TITLE
Ability to set the MQTT QoS

### ISSUE THREAD

**Issue by gotthardp** [gotthardp/lorawan-server#405]
we need to set the MQTT QoS to 1 or 2 when publishing uplink message (and maybe when subscribing to downlink)

**Comment by Quentintin** [comment]
👍 

Currently, MQTT connector publish in QoS 0 ?

**Comment by gotthardp** [comment]
Currently the default value is used; it's not even set. I believe that default is QoS 0.

**Comment by gotthardp** [comment]
Done for 0.6.0
