### ISSUE TITLE
HTTP Connector SSL cihper suite configuration

### ISSUE THREAD

**Issue by pmst** [gotthardp/lorawan-server#407]
I have configured the HTTP connector to point to a server using ssl (https). The remote system (frontend server is caddy) is refusing connection due to the use of a non accepted cipher suite. The error is the following:
> {gun_error,<0.385.0>,{stop,{goaway,0,inadequate_security,<<"Prohibited TLS 1.2 Cipher Suite: c014">>},'Client is going away.'}}

Is there a way to configure the client library cipher suites to use ?

**Comment by gotthardp** [comment]
Configuring individual ciphers is not possible and also not recommended.
What Erlang version are you using? Do you use the pre-compiled server version, or you build your own?

**Comment by pmst** [comment]
I was more thinking of removing a deprecated cipher. My erlang is installed from the package mentioned in the Installation instructions: erlang-solutions_1.0_all.deb, current version is 20.3

**Comment by gotthardp** [comment]
I implemented a new config option `ssl_options` for 0.6.0
