### ISSUE TITLE
2 pages not found on 0.5.4

### ISSUE THREAD

**Issue by hallard** [gotthardp/lorawan-server#409]
I upgraded from 0.5.3 to 0.5.4 on my PiZero and I noticed something strange, even if the server works fine, I got 2 menus that fire a page not found, the others menus are working fine
the menu are "the main page" and "events" 

![image](https://user-images.githubusercontent.com/2471931/40891437-b0c6b86c-6785-11e8-8b2d-a07cce093f53.png)

the other (main page) is this one /admin#/dashboard

Anyone noticed this or it's just my config that have an issue ?

**Comment by gotthardp** [comment]
I experience the "Not Found" error as a temporary state after upgrade while the web-admin was running. The error goes away in about 1 minute. Did your error persist?

**Comment by hallard** [comment]
Well, yes it persist, I think it's more on syntax than on update.
On Publish events from WS connector I changed `/{app}/events` to `ws/{app}/events` and it's gone. looks like expanding the 1st one {app} at 1st level give some trouble (but only on event, works fine on uplink)

**Comment by gotthardp** [comment]
yeah, i know what happended: the `{app}/events` got confused with `api/events`. I made a fix for that. Thanks for reporting this!

**Comment by gotthardp** [comment]
Will be fixed in v0.5.5
