### ISSUE TITLE
Eating up Free Memory

### ISSUE THREAD

**Issue by netuserlv** [gotthardp/lorawan-server#411]
At the beginning I would like to thank the maker of this server, it is really grate so far and all. But I was wondering am I doing something wrong because the server is showing less and less available ram memory? Can there be something done about that, does it save something on it and how can i delete it. Because I am forwarding everything to a node red which is saving the data somewhere else and I kinda don`t know what to do.... 
![inkeddesktop _li](https://user-images.githubusercontent.com/35964652/40963795-1a3e6aa6-68b2-11e8-8deb-1ed6845e07b5.jpg)

**Comment by gotthardp** [comment]
Hello. Thank you! The memory can be consumed by a caching mechanism, so it may eventually get released again. What Erlang version are you using? Could you try upgrading Erlang to see if something changes?

**Comment by cristianhumelnicu** [comment]
Hi Petr ,
I've upgrade erlang and system still eating a lot of memory and that is critical when someone (like me) have lorawan server installed on RPI3

Thx !

**Comment by gotthardp** [comment]
@cristianhumelnicu would you be able to monitor the consumed memory over time (days) and see how it evolves?

**Comment by xypron** [comment]
There was a display issue for free memory that has been fixed by merging #528. So I think this issue can be closed now.

**Comment by gotthardp** [comment]
Right. Thanks!
