### ISSUE TITLE
Get device list via connectors?

### ISSUE THREAD

**Issue by FlaegelEmbed** [gotthardp/lorawan-server#412]
Hi there,

in my application i want to display all devices in the network via ws/http. With no event generated for a device, my application has no data for this device (created in admin page but no uplink data so far).
Is there a possibility to get the information via pattern i.e. /net/<netid>/devices?

**Comment by gotthardp** [comment]
Hello. It's `/api/devices` or `/api/nodes` as described here https://github.com/gotthardp/lorawan-server/blob/master/doc/Administration.md#rest-api

**Comment by FlaegelEmbed** [comment]
Thanks, got it!
