### ISSUE TITLE
Server update

### ISSUE THREAD

**Issue by jot4p** [gotthardp/lorawan-server#414]
Hi, 

I have the version 0.53.. and I need to update for 0.55. 

It's impossible to copy db (system crash) ..

I have >100 nodes ...  I need to create the devices, handlers, connectos, ADR settings  ?

**Comment by gotthardp** [comment]
What db copy you mean and what db crash you experienced?

**Comment by gotthardp** [comment]
Any update? Shall I close this issue?

**Comment by gotthardp** [comment]
And what error do you get?

**Comment by jot4p** [comment]
Ok my problem is based in the problem of my computer name.. I have 1 lorawan in server and other in my personal computer.. but your database is based on computer name. 

I'm trying to create "lorawan-server-beta" in my server but I have this:

> Protocol 'inet_tcp': the name lorawan@ns373704 seems to be in use by another Erlang node

It's possible to use allways the same name ? or control this ?

**Comment by gotthardp** [comment]
The node name is based on the hostname. If you set identical hostnames you get identical database files, but the best (and recommended) way to backup is to use the scripts I provided.

**Comment by jot4p** [comment]
Can you provide the URL ?

**Comment by gotthardp** [comment]
See dbexport and dbimport in https://github.com/gotthardp/lorawan-server/tree/master/scripts

**Comment by jot4p** [comment]
Do you have the same for windows ?

**Comment by gotthardp** [comment]
No.

**Comment by gotthardp** [comment]
The import/export scripts for windows will be in 0.6
