### ISSUE TITLE
Server started not shown on reboot startup

### ISSUE THREAD

**Issue by gmbankar37** [gotthardp/lorawan-server#417]
Hii, 
 I have enabled the service where my server will start automatically on boot up. Though the server starts and nodes can be joined the server join & connected message dont appear on timeline as well as in the events section the date and time is wrongly shown. As the highlighted portion shown on the screen shot the server is started in the morning but it shows the date of yesterday. Dont know its an error from my side or not, just wanted to report this bug. 
![lora_server](https://user-images.githubusercontent.com/37892112/41888079-36f8c644-7921-11e8-9014-891f768a116a.PNG)

**Comment by gotthardp** [comment]
The time shown in the events is 17:27, however the timeline shows 8:59 to 9:09 only. That's why the 17:27 is not shown.
