### ISSUE TITLE
Modificar lorawan-server el campo 'rxframe'

### ISSUE THREAD

**Issue by thegamecena619** [gotthardp/lorawan-server#424]
Hello,

Maybe you can tell me how I can do to create a field similar to this one:

    var rxframes = nga.entity ('rxframes')
        .identifier (nga.field ('frid'))
        .readOnly ();

The objective is to duplicate the 'rxframe' field, that is, obtain a 'rxframe2' and use the variable:

nga.field ('data')
            .template (function (entry) {
                if (entry.values.data)

How could I do it? Thank you very much in advance.

**Comment by gotthardp** [comment]
And why do you do that?

**Comment by thegamecena619** [comment]
is that I need to do a job that modification and I need to have two fields with the same characteristics.

**Comment by gotthardp** [comment]
I still don't understand why do you want to do that modification.

**Comment by thegamecena619** [comment]
![envi](https://user-images.githubusercontent.com/35438194/41936182-02c5c8c8-7952-11e8-9e66-9a8461903743.png)

The idea is to have two fields 'application' and 'application 1'

**Comment by gotthardp** [comment]
I modified https://github.com/gotthardp/lorawan-server-demoapp to show the right way how to do what you are trying to achieve.
