### ISSUE TITLE
Not receiving uplink frames

### ISSUE THREAD

**Issue by gmbankar37** [gotthardp/lorawan-server#439]
I upgraded from 0.5.3 to 0.5.5. I copied the mnesia database folder to have same configuration as before. I am able to join the node to the gateway. When I am sending a frame the gateway is not able to receive it. It shows nothing in received frame but i get an acknowledgment in the terminal that the frame is received. Is the gateway to server connection faulty? but I am getting a join on the timeline.

**Comment by gotthardp** [comment]
what kind of "acknowledgment in the terminal that the frame is received" do you mean?

**Comment by gmbankar37** [comment]
Yes.

**Comment by gmbankar37** [comment]
when I send at+send=1,2,"data" I get at+recv=1,0,0

**Comment by gotthardp** [comment]
What application are you using?

**Comment by gmbankar37** [comment]
I created a new one in handler. Passing the uplink frame as it is. also
have a mqtt connector.

**Comment by gmbankar37** [comment]
Got it working. Dont know the logic behind it but first I tried to send
with semtech-mote application and then I changed it to my handler
application.

**Comment by gotthardp** [comment]
Problem solved, then :)
