### ISSUE TITLE
load balancer

### ISSUE THREAD

**Issue by batulzii** [gotthardp/lorawan-server#441]
Any experience of deploying several servers in cluster? What is recommendation on load balancer .

**Comment by gotthardp** [comment]
Clustering is under development for 0.6.x. You may have seen https://github.com/gotthardp/lorawan-server/blob/master/doc/Cluster.md

Feel free to give it a try and/or ask questions on the mailing list.

**Comment by batulzii** [comment]
Thank you for prompt answer.
