### ISSUE TITLE
Send mac commands to node(s) manually

### ISSUE THREAD

**Issue by ZuratonE** [gotthardp/lorawan-server#446]
I would like to send a specific mac command to my node.
Is it possible some way?

**Comment by gotthardp** [comment]
It depends on what command you want to send.

**Comment by ZuratonE** [comment]
DutyCycleReq

**Comment by gotthardp** [comment]
DutyCycleReq is not implemented yet, but can be done quite easily

**Comment by gotthardp** [comment]
I just implemented the DutyCycleReq MAC. Will be included in release 0.6.0.
