### ISSUE TITLE
FR: allow usage of alternate mapping services apart from GoogleMaps

### ISSUE THREAD

**Issue by altishchenko** [gotthardp/lorawan-server#454]
GoogleMaps are not the only and not really the best mapping service, at least in our country. It would be great to be able to use other mapping services, possibly via [leaflet.js](https://leafletjs.com) library.

**Comment by gotthardp** [comment]
The GoogleMaps was just a first shot, can switch to openstreetmap for example. It seems not so difficult to switch to https://github.com/angular-ui/ui-leaflet, but does this mean you'd need some config option to choose the map source?

**Comment by altishchenko** [comment]
@gotthardp I am not sure, if this is possible... For leaflet tile source is configurable. This requires some carefull consideration. I'll email you my thoughts later (I am digging around).

**Comment by gotthardp** [comment]
I found some time to integrate the Leaflet. It's by default using the openstreetmap.
