### ISSUE TITLE
OTA updates

### ISSUE THREAD

**Issue by Fergalaran** [gotthardp/lorawan-server#461]
Will there be the addition of OTA update support for connected sensors?

**Comment by gotthardp** [comment]
You mean firmware updates? That's not standardized (yet) and the LoRa bandwidth is so limited that I personally think it would be waste of resources to send firmware over LoRa.

**Comment by Fergalaran** [comment]
I agree but i just wanted to see what the direction was in relation to this. The things network have demonstrated the application but i don't see any uptake by end node vendors yet.

**Comment by gotthardp** [comment]
Right. I mostly follow the LoRaWAN standard and the LoRa Mac firmware.
