### ISSUE TITLE
unknown_frame when used with multitech gateway in server-mode

### ISSUE THREAD

**Issue by rnukala** [gotthardp/lorawan-server#465]
Hi ,

I am getting started with this platform, pretty interesting,  I have setup up the server, connected the Multitech gateway in packet forwarder mode. I can see the gateway is connected on the server. Then I have the end lora device setup and can see joining the network (screenshot enclosed). However,  I cant see anything in the "received frames " section, the  keep getting " unknown_error frame" .  

How can I fix this error and where do I see what my sensor(end device) is sending/ the data that server is receving?  I have included server log and server dashboard screenshot.

![debug-open](https://user-images.githubusercontent.com/12168171/44145945-59b60e9a-a085-11e8-9d99-e63f985b8651.PNG)
![error-open](https://user-images.githubusercontent.com/12168171/44145946-59d06eac-a085-11e8-9214-60091a54a297.PNG)
![lorawan-open](https://user-images.githubusercontent.com/12168171/44145947-59e910a6-a085-11e8-8400-4c508a93d9c3.PNG)

Thanks,

**Comment by gotthardp** [comment]
Hello. The frames your device is sending seem not LoRaWAN compliant. The (invalid) frames are shown in the debug log: the string of numbers in `<<>>` brackets are decimal bytes as received.

**Comment by gotthardp** [comment]
How many devices did you start? In LoRaWAN frame the byte 2-5 is a Device Address. In your frames these bytes are always different as if you had many different devices. If this is all sent by a single device, then it's definitely not LoRaWAN.

**Comment by rnukala** [comment]
Thanks for getting back, All the unknown frames are from the same one device.  
lets say the device is sending L.send(21,1) which means the payload is "1" and the values is pushed on port 21 . So when it goes through multitech gateway do you think its not creating a full lora message?

When we use multitech in network server mode we used to get the full frame message like this one
{"ack":false,"adr":true,"appeui":"00-00-00-00-00-00-00-00","chan":5,"cls":0,"codr":"4/5","data":"134UKQ==","datr":"SF11BW125","deveui":"48-83-C7-DF-30-01-1149","freq":"867.5","lsnr":8.5,"mhdr":"403f000000806b00","modu":"LORA","opts":"","port":2,"rfch":1,"rssi":-75,"seqn":107,"size":8,"timestamp":"2018-04-19T09:54:34.113567Z","tmst":2751505260}
 
Is this what you call LoRaWAN compliant?

**Comment by gotthardp** [comment]
LoRaWAN defines the structure of the message (which is encoded in the data field). For example, your `134UKQ==` in Base64 is `d7 7e 14 29` hexadecimal. This is definitely not a LoRaWAN message. See the Section 4 in https://lora-alliance.org/sites/default/files/2018-04/lorawantm_specification_-v1.1.pdf

**Comment by rnukala** [comment]
Hi,

 The data field which you have pointed out is the payload that  our end device is sending (example: temperature value) more details of the fields can be found here. (http://www.multitech.net/developer/software/lora/lora-network-server/mqtt-messages/)

I have also looked into the link shared, I believe the full json message which we have presented as an example  does follow  LoRaWAN message/format (it does have necessary fields).

I was wondering if there is a way to see what the server is receiving from our gateway(packet forwarder) instead of just seeing unknown frame? Could you please may be send us like a valid message which would be accepted as a known frame by  your server.

Thank you so much.

**Comment by gotthardp** [comment]
If the data I have described above is what the device sends, then the device firmware is not adding LoRaWAN headers-- it's sending plain LoRa (so it is received by the gateway), but not LoRaWAN (so it is not accepted by the server). See the Section 4 in https://lora-alliance.org/sites/default/files/2018-04/lorawantm_specification_-v1.1.pdf for a description of a valid LoRaWAN message.

**Comment by rnukala** [comment]
Hi, 

To test further, I  installed another lora server( www.loraserver.io) and was able to receive messages on it with the same gateway setup that I have used it to send it to yours.
The only difference what I found is my end devices only support LoRaWAN MAC version 1.0.0.
I wonder if you have any constraints on MAC version for  the end devices  for them to talk to your server?

Thank you,

**Comment by gotthardp** [comment]
My server supports LoRaWAN MAC 1.0.0 through 1.0.3. Do you want to stick with loraserver.io, or shall we continue investigating this issue?

**Comment by altishchenko** [comment]
@Revathi, would you care to take wireshark dumps (gateway <-> server
message flow) from your newly installed loraserver.io server and from the
lorawan-server? To answer your question here the dumps are critical. In
LoRaWAN the server and the end node are the only ones responsible for the
LoRaWAN MAC layer processing. The gateway has *nothing* to do with it. It
sounds very *strange* that the gateway strips off the MAC layer when
communicating with the lorawan-server and presents the payload only
(according to your own description of the data being received by the
server) and does not in the case of the loraserver.io. Could you have
possibly *mistyped* one of the authentication keys in the lorawan-server
config? Or is the gateway config exactly the same? Or have you, while
moving over to another server, changed something on the node itself?

**Comment by gotthardp** [comment]
Good catch. I just wonder if the loraserver.io really supports this server-mode payload, of whether the multitech gateway got switched to the gateway mode.

**Comment by rnukala** [comment]
Ok,  yes  want to debug  wrt. your server. So what do you suggest I should
be doing ? Is it a setting issue or tweak the msg before it goes through
the packet forwarder. I really appreciate your time and inputs thank you.

**Comment by gotthardp** [comment]
You need to convert your multitech to "Basic Packet Forwarder". Depending on what version you have see either http://www.multitech.net/developer/software/lora/aep-lora-packet-forwarder/ or http://www.multitech.net/developer/software/lora/conduit-mlinux-convert-to-basic-packet-forwarder/.

If it doesn't work even after that, create a [Wireshark](www.wireshark.org) dump with the Gateway to Server communication as suggested by altishchenko above.

**Comment by rnukala** [comment]
Yes all this time the Multitech was set to  packet forwarder mode. I will
look into the Wireshark option and  get back thank you so much again.

**Comment by gotthardp** [comment]
Did you manage to resolve this issue?

**Comment by rnukala** [comment]
Hi,

I ran the server and tested  with different sensor and worked, I can see
the messages coming in. I used the same multitech, in packet forwarder mode,

 so I kind of think it was that particular sensor that kept failing, it had
an early version of loraWan spec 1.0.0 , but I still don't know exact root
cause. But for now I guess this issue can be closed. Let me know your
thoughts,

Thanks again

**Comment by gotthardp** [comment]
If other sensors worked, then I'd say you had a faulty sensor. I will close this issue then. Feel free to open a new one of you encounter some issues.
