### ISSUE TITLE
gateway transmission power 

### ISSUE THREAD

**Issue by gmbankar37** [gotthardp/lorawan-server#467]
hii , I have set the gateway power to 30dBm. I wanted to know how does it exactly affects the gateway when I change it. I mean on the RAK831 gateway board which pins does it affect so it reduces or increases the transmission power?

**Comment by gotthardp** [comment]
Hello. The number just sets the `powe` field in the `txpk` structure sent to the gateway
https://github.com/Lora-net/packet_forwarder/blob/master/PROTOCOL.TXT#L358

The rest repends on the gateway.
