### ISSUE TITLE
No logs created

### ISSUE THREAD

**Issue by gmbankar37** [gotthardp/lorawan-server#469]
hello , 
After updating to latest release 0.5.5 I am not able to see any logs or more correctly they are not created. And how much space does logs take as the host is nearly out of space.

**Comment by gmbankar37** [comment]
The problem for now is not reduction but that they are not starting at all.
Is there a way I can delete the received frames?

**Comment by gotthardp** [comment]
You can delete all rxframes via a console:
 * start the server
 * connect to the cluster via remote shell by `erl -sname test -remsh lorawan@<hostname>`, where hostname is what you can see in the web-admin
 * delete the database table by entering a command `mnesia:delete_table(rxframes)`.
 * restart (stop and start] the server to recreate the database

**Comment by gotthardp** [comment]
And version 0.6.0 will have a "Purge" button to delete all rxframes (and events).
