### ISSUE TITLE
 fcount increases even if bad MIC

### ISSUE THREAD

**Issue by peterbjoerk** [gotthardp/lorawan-server#470]
Possible bug, fcount increases even if bad MIC. If one GW is forwarding package with CRC error ("forward_crc_error":true) then the server increases the fcount before checking MIC resulting in  fcnt_gap_too_large when next "valid" package receives. This can happen if one GW is "misconfigured" (forward CRC error).

**Comment by gotthardp** [comment]
This is a bug indeed. I have just fixed it. Thanks for the report!
