### ISSUE TITLE
websocket connect failed

### ISSUE THREAD

**Issue by ly1243667342** [gotthardp/lorawan-server#474]
I am using the software in version(0.6.0). I can receive data from node and view the data from the website(http://192.168.0.108:8080/admin#/rxframes/list).
![image](https://user-images.githubusercontent.com/34018438/44831598-cc08dd80-ac59-11e8-9abf-3886c912a081.png)

but i can not connect to server by websocket.

the log is below:
ws.html:56 WebSocket connection to 'ws://192.168.0.108:8080/ws/nodes/00513128' failed: Error during WebSocket handshake: Unexpected response code: 404
connect @ ws.html:56
toggle_connection @ ws.html:73
onclick @ ws.html:144
ws.html:56 WebSocket connection to 'ws://192.168.0.108:8080/ws/nodes/00513128' failed: Error during WebSocket handshake: Unexpected response code: 404

what is wrong? thanks !

**Comment by gotthardp** [comment]
How did you configure the connector?

**Comment by ly1243667342** [comment]
Thank you for your timely reply.
this is the configure of connector.
![image](https://user-images.githubusercontent.com/34018438/44886674-67518f80-acfa-11e8-96f8-ca6c73c0ac77.png)

now i can connect to server .but can not receive data via websocket. website(rxframes/list) can recieve data normally.
![image](https://user-images.githubusercontent.com/34018438/44886702-a1229600-acfa-11e8-97d4-c7fefb731322.png)

what is wrong ?

**Comment by gotthardp** [comment]
You don't have Application set. You need to have a Handler of some name and that (Application) Name has to be set both in the Connector as well as in the Device Profile your devices are using.

**Comment by ly1243667342** [comment]
i don know how to set application. i try to set application,but not work!
![image](https://user-images.githubusercontent.com/34018438/45129196-ed674d80-b1b4-11e8-9954-1efe4030a023.png)
![image](https://user-images.githubusercontent.com/34018438/45129209-02dc7780-b1b5-11e8-938c-86645a1de7f9.png)
![image](https://user-images.githubusercontent.com/34018438/45129221-0ec83980-b1b5-11e8-8946-6490fde081b2.png)

the websocket still can not receive data, website can receive data and show data. can you give a workable configure? thank you !

**Comment by gotthardp** [comment]
Set Publish Uplinks to `/ws/uplinks/{devaddr}`. You have to use the template, not the real DevAddr.

**Comment by gotthardp** [comment]
Any update? Shall I close the issue?

**Comment by ly1243667342** [comment]
thank you very much
