### ISSUE TITLE
Interfacing with Orange Live Objects

### ISSUE THREAD

**Issue by NicoHell1** [gotthardp/lorawan-server#477]
Hello @gotthardp, as you asked me, I share the configuration needed to connect to Live Objects platform, I think that you already have the fun expression, I can give it again in this thread if you prefer.

For the Connector, you need this configuration : 
        - URI -> https://liveobjects.orange-business.com
        - Publish Uplinks -> /api/v0/data/bulk
        - Authetification -> Header+Token with 'X-API-Key' for name and the key for password

My device uses the CBOR format ( http://cbor.io/ ) to send frames so I added an Erlang decoder in the source files and used it, it works pretty well.
As you added a Cayenne's LPP decoder I was wondering if that might interest you or not, if so, I can send you the erl file, you can also find it directly on the CBOR website, not sure if you want to use it that way or integrate it directly in your code.

Thank you again for your help :+1:

**Comment by gotthardp** [comment]
Thanks a lot! I added the documentation to the Integration guide and also added CBOR as a natively supported format.

**Comment by NicoHell1** [comment]
No problem, it was a pleasure to work with this project.

For the CBOR decoder, I assume you implemented a generic decoder so it is
very nice. In the future I would say that a possible improvement would be
to allow the user to define like a map or something to define what the keys
in the CBOR-formatted payload means.

In other words, the CBOR format is customizable, the developer can define
the keys which will be decoded. For example, the developer can decide for a
temperature value to have a string key ("temp" for instance with value of
25°C), the payload would be then :
*A16474656D701819*
Decoded as : {"temp": 25}

But the developer can also decide to use int keys and then the decoder as
to be implemented that a certain key corresponds to a certain type of
value. For example, the developer can decide that the hex 0x01 corresponds
to a temperature, so the decoder as to know that, and decode key 0x01 =>
temperature.

I do not know if this feature can be added or if I was clear enough (not
sure about this part ^^).

Anyway, thank you again for your project and all the help you provided !



2018-09-06 12:10 GMT+02:00 Petr Gotthard <notifications@github.com>:

**Comment by gotthardp** [comment]
To be honest, I tried to understand CBOR but it was too complex and I didn't have enough time.

Where does the developer define the keys? In the payload itself? Because the decode function has just one argument, which is the data.

If it's in the payload and the decoder returns a map/dict, then this will get included in the fields. In other words, the Parse Uplink function gets whatever the decoder returns. Is there any way to configure the decoding process?

**Comment by NicoHell1** [comment]
Yes indeed, it is in the payload directly, the decode function decodes
directly the int key. So if I use again the example with the temperature
value, defined by the 0x01 key.

The payload is: A1 01 18 19
This payload is decoded with the function as a JSON: {1: 25}.
Then, I guess you can configure the decoding process with this first
decoded JSON. It can be parsed, and the configuration of the decoder can
decide that the key "1" correspond to a temperature and then transform the
JSON from {1: 25} to {"temp": 25}.

This method should be used in order to reduce the size of the payload (LoRa
compliance + optimization for embedded systems), as you can see with the
int key, the size is significantly smaller than with the ASCII key directly
in the payload.

So maybe I was thinking about a field where the user can define which int
key correspond to what value (so here "1" to "temp") and decode the payload
with the original function + the configuration defined by the user.

I know it can be a bit complex, I personnaly struggled a bit to understand
how it works. I used the playground http://cbor.me/ to test this format
before using it and to understand of a JSON was converted to a CBOR format.

2018-09-06 13:50 GMT+02:00 Petr Gotthard <notifications@github.com>:

**Comment by gotthardp** [comment]
Isn't this replacement something done by the devices, i.e. something not included in the CBOR standard?

**Comment by NicoHell1** [comment]
The CBOR standards lets you free about encoding and decoding, it has to
respect some recommendations though if I undestood (see section 3.7 of RFC
7049 on CBOR).

Indeed it can be done by devices, directly use an UTF-8 key to describe the
values but I guess that in embedded systems and in IoT field such as LoRa,
the problem with UTF-8 keys in the payload directly is that it is much
heavier than just small int keys.

So I was wondering if this solutions of decoding, using first the generic
decoder and then replace the int keys with actual UTF-8 keys to be more
human-readable was possible.

2018-09-06 14:12 GMT+02:00 Petr Gotthard <notifications@github.com>:
