### ISSUE TITLE
websocket new connector 

### ISSUE THREAD

**Issue by gmbankar37** [gotthardp/lorawan-server#483]
Hii, 
As the websocket path for uplinks is defined like /ws/uplinks/{Dev_addr} so when my dev_addr changes do I have to create a new websocket connector?
In short should i have different connector for every unique device (node) ? Or can I make it generic?

**Comment by gotthardp** [comment]
Well, it is generic. The `{devaddr}` is a template. You shall use this text as is. The replacement is done automatically by the server.

**Comment by gmbankar37** [comment]
I have  /ws/uplink/{devaddr} written in publish uplinks and On the demo client I am trying to access ws/uplink/00000AB8. But I am not getting any connection.

**Comment by gmbankar37** [comment]
Got it working thank you.

**Comment by gotthardp** [comment]
How did you solve the problem, please?

**Comment by gmbankar37** [comment]
Oh rookie mistake I just reloaded the server and it started working.

**Comment by gotthardp** [comment]
Cool! Thanks.
