### ISSUE TITLE
Dashboard timeline meaning of different packets received 

### ISSUE THREAD

**Issue by gmbankar37** [gotthardp/lorawan-server#495]
Can you tell what is the meaning of all these coloured packets received in the screenshot attached. Thank you. 
![6](https://user-images.githubusercontent.com/37892112/46533281-a8246180-c8c1-11e8-8381-c05348fec6c8.PNG)

**Comment by gotthardp** [comment]
Good question. I just updated the documentation to say

 * Rolling timeline that displays:
   - **red** error events;
   - **yellow** warning events;
   - **blue** handled uplinks frames;
   - **cyan** sent downlinks frames;
   - **gray** ignored uplinks frames.

**Comment by gmbankar37** [comment]
So what do you mean by ignored uplinks frame? I my case after with every blue frame it shows a gray frame so I thought it might be downlink. So according to my screenshot why are there so many ignored frames?

**Comment by gotthardp** [comment]
Share with me the Frames list. The items of the dashboard are taken from there.

**Comment by gotthardp** [comment]
You forgot the attachment

**Comment by gmbankar37** [comment]
I did attach it. It is an image.

**Comment by gotthardp** [comment]
But I don't see any image :)

**Comment by gmbankar37** [comment]
![7](https://user-images.githubusercontent.com/37892112/46599951-486ac800-cb06-11e8-8e1f-2e6caab9d3b5.PNG)
So what are the unconfirmed downlink frames with no data?

**Comment by gotthardp** [comment]
It looks like a downlink from the server MAC (without application data). Could you please hover the mouse cursor above the arrow on the first line and let me know what text it displays?

**Comment by gmbankar37** [comment]
It displays down. 

![9](https://user-images.githubusercontent.com/37892112/46646206-7b649880-cba6-11e8-9439-e892188546dc.png)

**Comment by gmbankar37** [comment]
What is the condition where we get missed uplink warning?

**Comment by gotthardp** [comment]
Missed uplink is generated when there is a gap in the FCnt sequence.

**Comment by gmbankar37** [comment]
So that frame is not transmitted with that particular FCnt. Say FCnt=30 is transmitted and received and then the next FCnt received is 33. So can i say 31 and 32 are not transmitted or is it just that they are missed by server?

**Comment by gotthardp** [comment]
The missing frames are either not sent or not received. You cannot say more without some RF level debugging.

**Comment by gmbankar37** [comment]
And what would be the reason for missing any frames?

**Comment by gotthardp** [comment]
Usually a RF interference with the environment or other transmissions on the same frequency.

**Comment by gmbankar37** [comment]
Also the channels(i.e. frequencies) i have defined at the node does not
match with the frequencies received. I mean i have defined channel
frequency 866.400 but at the same channel I receive from different
frequency.

**Comment by gotthardp** [comment]
This depends on the gateway.
