### ISSUE TITLE
when FCntUp > 65535 server recieve data error

### ISSUE THREAD

**Issue by ly1243667342** [gotthardp/lorawan-server#500]
i use the new version (0.6.0). 
![image](https://user-images.githubusercontent.com/34018438/46709763-b5ea3600-cc77-11e8-9fdc-2ba01d59de08.png)

![image](https://user-images.githubusercontent.com/34018438/46709784-ce5a5080-cc77-11e8-90b0-9336b12f0f75.png)

why ? thanks .

**Comment by gotthardp** [comment]
I kindly ask you to provide more explanation about this issue. The screenshot of issue 566 doesn't related to this server.

**Comment by ly1243667342** [comment]
thanks, the server is ok
