### ISSUE TITLE
How to make a light-weight(excluding frame data) backup of server?

### ISSUE THREAD

**Issue by kcyung3663** [gotthardp/lorawan-server#503]
Hi all, I am actually trying to ask how to backup all the configuration inputted, system is Linux(Debian 9).

Or another way to ask is, where are all these configuration stored at?

In addition, would it be a possible way out if I git all the files related to lorawan-server?

Thanks.

**Comment by gotthardp** [comment]
Hello. This is exactly what the dbexport script does. It does not backup frames nor events, only the server settings.
