### ISSUE TITLE
WebSocket crash after (downlink)

### ISSUE THREAD

**Issue by JoobyPM** [gotthardp/lorawan-server#504]
Hi all,
Could some on please help me to figure out why WebSocket connectin might closed (after sending the downlink)?
My app sends downlink straight after receiving uplink, and the connecction is closing from «lorawan-server».

It's the second WebSocket connector, with the first on evrething is fine (there are no closure of the connection after imidiate DL).

I've puted 5 sec delay before send the DL and after that connection not closing, but any way it's weird.

Log from my app (java ws client tyrus):
>###20:48:54.986 UL: 1F11100701204900000000F105000019000000C9
###20:48:55.121 DL: 8E03030400DF
[20:48:55.124 lcs-1] tx: {"devaddr":"A0000004","data":"8E03030400DF","time":"immediately","port":1}
[20:48:55.142  tyrus-jdk-client-2]  Close connection, reason: CloseReason[1011]

> public static final CloseReason.CloseCodes UNEXPECTED_CONDITION
> 1011 indicates that a server is terminating the connection because it encountered an unexpected condition that prevented it from fulfilling the request.

From debug.log:
> 2018-10-12 18:48:55.130 [debug] <0.27125.1>@lorawan_connector_ws:terminate:164 WebSocket terminated: {crash,error,{case_clause,{ok,{-576274097825031,#Ref<0.2026398775.1258291201.46550>}}}}
2018-10-12 18:48:55.131 [error] <0.27125.1>@lorawan_connector_ws:handle_downlink:111 CRASH REPORT Process <0.27125.1> with 0 neighbours crashed with reason: no case clause matching {ok,{-576274097825031,#Ref<0.2026398775.1258291201.46550>}} in lorawan_connector_ws:handle_downlink/2 line 111
2018-10-12 18:48:55.133 [error] <0.27125.1>@lorawan_connector_ws:handle_downlink:111 Ranch listener http terminated with reason: no case clause matching {ok,{-576274097825031,#Ref<0.2026398775.1258291201.46550>}} in lorawan_connector_ws:handle_downlink/2 line 111

From crash.log:
> 2018-10-12 18:48:55 =CRASH REPORT====
  crasher:
    initial call: cowboy_clear:connection_process/5
    pid: <0.27125.1>
    registered_name: []
    exception error: {{case_clause,{ok,{-576274097825031,#Ref<0.2026398775.1258291201.46550>}}},[{lorawan_connector_ws,handle_downlink,2,[{file,"/lorawan-server/_build/default/lib/lorawan_server/src/lorawan_connector_ws.erl"},{line,111}]},{cowboy_websocket,handler_call,6,[{file,"/lorawan-server/_build/default/lib/cowboy/src/cowboy_websocket.erl"},{line,454}]},{cowboy_http,loop,2,[{file,"/lorawan-server/_build/default/lib/cowboy/src/cowboy_http.erl"},{line,201}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.355.0>,<0.354.0>,ranch_sup,<0.151.0>]
    message_queue_len: 0
    messages: []
    links: [#Port<0.22689>,<0.355.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 7679
  neighbours:
2018-10-12 18:48:55 =ERROR REPORT====
Ranch listener http had connection process started with cowboy_clear:start_link/4 at <0.27125.1> exit with reason: {{case_clause,{ok,{-576274097825031,#Ref<0.2026398775.1258291201.46550>}}},[{lorawan_connector_ws,handle_downlink,2,[{file,"/lorawan-server/_build/default/lib/lorawan_server/src/lorawan_connector_ws.erl"},{line,111}]},{cowboy_websocket,handler_call,6,[{file,"/lorawan-server/_build/default/lib/cowboy/src/cowboy_websocket.erl"},{line,454}]},{cowboy_http,loop,2,[{file,"/lorawan-server/_build/default/lib/cowboy/src/cowboy_http.erl"},{line,201}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}

- Distribution type: dockerized
- Linux lorawan 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 Linux
- Erlang/OTP 20 [erts-9.3.3.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false] Eshell V9.3.3.3

**Comment by gotthardp** [comment]
Hello. Thanks for a perfect bug report. You likely sent a Class C (with "time":"immediately") to a Class A device that just sent an uplink. Did you? The server delays such transmissions to avoid collisions.
There was a bug (that I just fixed), which caused the crash, but nontheless you shouldn't set "time":"immediately" when responding to a class A uplink.

**Comment by gotthardp** [comment]
There is no such setting in the server. Note that Class C is an extension of the Class A. Sending downlink after an uplink is Class A even if the device supports Class C. The Class C transmission is _only_ when initiated by an external impulse.

**Comment by JoobyPM** [comment]
Thank you for the explanation.

**Comment by gotthardp** [comment]
The problem was fixed in the just released 0.6.2. Please reopen this issue if the problem persist.
