### ISSUE TITLE
lorawan-service.bat

### ISSUE THREAD

**Issue by vinggroupe** [gotthardp/lorawan-server#508]
Hello

the current .bat is not working because all `"` need to be replace by `\"` in FILES like said in the documentation of erlsrv [http://erlang.org/documentation/doc-5.7.1/erts-5.7.1/doc/html/erlsrv.html](url)
here the change that works for me 

```
for /D %%A in ("%ROOT_DIR%\lib\*") do (
    set FILES=!FILES! \"%%A\ebin\"
)
```

**Comment by gotthardp** [comment]
Fixed in 0.6.7, thanks!
