### ISSUE TITLE
Logs show device/node ID's in decimal

### ISSUE THREAD

**Issue by dlarue** [gotthardp/lorawan-server#51]
Input of device/node link settings(IDs, keys, etc ) are in hex but logs show decimal representations. It would be more helpful if the logs also showed the values in hex.

ex:  ERROR: {unknown_devaddr,<<38,1,38,83>>}

**Comment by gotthardp** [comment]
Agreed. Sometimes there is a preceding warning with a decimal representation. Sometimes not.

**Comment by gotthardp** [comment]
Done. I improved error handling and also made sure the logs will be better readable as you suggested.
