### ISSUE TITLE
Fun Handler Guru's help needed

### ISSUE THREAD

**Issue by hallard** [gotthardp/lorawan-server#510]
Hi there,
I'm asking a stupid question, but my lack in ERLang is my main issue
I succeded to parse uplink with fun as follow
```erl
fun(Fields, << Ts:32, Lon:32/signed, Lat:32/signed, Speed, Head, Temp:16, Bat:16/little>>) ->
  Fields#{ ts => Ts, lat => Lat/600000, lon => Lon/600000, bat => Bat*0.006406, temp => Temp}
end.
```

But I need to do some treatment on latest Temp value before sending it, I already made it on nodered but want to put directly on server side, I would like to convert temperature value (latest field above `Temp`) The code is as follow on javascript and I tried several attempts on fun but I'm unable to get it working.

may be something like `temp => fun (Temp) blah blah .end` but I even not sure it's possible.

```javascript
if (Temp> 0x7FF ) { 
    Temp= -(Temp&0x7FF) ;  
}
Temp = (Temp*0.0625)
```

Any help on this point will save my day.

Thanks

**Comment by gotthardp** [comment]
The fun can have multiple commands. So, I'd write something like this:
```erlang
fun(Fields, << Ts:32, Lon:32/signed, Lat:32/signed, Speed, Head, Temp:16, Bat:16/little>>) ->
  Temp2 = 
    if
      Temp > 16#7FF -> -(Temp band 16#7FF);
      true -> Temp
    end,
  Fields#{ ts => Ts, lat => Lat/600000, lon => Lon/600000,
    bat => Bat*0.006406, temp => Temp2*0.0625}
end.
```
