### ISSUE TITLE
Cannot enter gateway location without Google API key

### ISSUE THREAD

**Issue by xypron** [gotthardp/lorawan-server#521]
Why should I want to share any location data with Google?
Please, provide text entry fields for the longitude and latitude as alternative to the entry via the map.

Best regards

Heinrich

**Comment by xypron** [comment]
We could use OpenStreetMap instead of Google Maps. Then we can avoid having to buy a license key. A coding examples can be found in https://medium.com/@balramchavan/using-openstreetmap-inside-angular-v6-3d42cbf03e57

**Comment by gotthardp** [comment]
The issue #454 also proposed that. Yes, we should get rid of google maps.

**Comment by gotthardp** [comment]
I just switched the server to [Leaflet](http://angular-ui.github.io/ui-leaflet/#!/), which by default uses the OpenStreetMap. The Google API key is no longer needed.
