### ISSUE TITLE
AS920-923

### ISSUE THREAD

**Issue by supergnow** [gotthardp/lorawan-server#533]
I have a end node which support AS923. 
I have tested it in TTN with AS920-923 setting. It works fine with uplink and downlink message.
When I switched to Lorawan-server by just changed the host name in the gateway config file and with network set as AS923, lorawan server behave differently. Dash board is displaying uplink_miss and only the unconfirm downlink works. When I tried to do confirmed downlink message, it will turn out to be downlink missed. 
From TTN console, it display it received uplink msg from 922.2, 922.4, 923.2, 923.4. It seems it can receive an uplink msg every 2 minutes but from Loraserver, it rarely received an uplink or sometimes never get one for 20 mins or more. When it got one, missed uplink is also displayed.
Is my setting incorrect? I had followed you default region setting for AS923 in document section.

**Comment by gotthardp** [comment]
When the device cannot hear the downlink the frequencies are likely misaligned between the device and the server config. The TTN may use some default settings, which I am not aware of since I am based in Europe. You will need to dig into the details I am afraid.

**Comment by supergnow** [comment]
It seems to me is the server cannot hear the uplink message. The downlink part is working as expected. Please let me know how can I align the frequencies on server?

**Comment by gotthardp** [comment]
It's the gateway that does "hear" the uplinks, so if the gateway doesn't hear something, it's a gateway failure.

**Comment by supergnow** [comment]
I didn't change anything from gateway's global_conf.json file, only change the server host from TTN to a loraserver installed in my local network inside the local_conf.json file

**Comment by supergnow** [comment]
When I went through the lora regional parameter, in AS923 section, it only mentioned 923.2 and 923.4 these two channels but the TTN global_conf.json has more than that. Do I need to manually add to the channel list in the lorawan server network section?

**Comment by gotthardp** [comment]
In the AS923 band the channels are region-specific, so yes-- if your region allows more than the initial 2 channels, you should add them to the list.
