### ISSUE TITLE
Class A and Class C behaviour 

### ISSUE THREAD

**Issue by gmbankar37** [gotthardp/lorawan-server#537]
I have implemented Class A and Class C devices. But I dont see any difference in the implementation of both. With reduced Latency in Class C should it be helpful to avoid collision? 
Can you please explain the following condition: 
Class A and Class C are sending a frame every one sec and get an acknowledgement from gateway after 3-4 secs. Does the module have a buffer to store uplink frame while waiting for the acknowledge to come in. How will these two devices behave in such situation?

**Comment by gotthardp** [comment]
Class A devices listen for downlink just after an uplink. Class C devices do exactly the same, but *in addition* to that they also listen constantly for "immediate" downlinks. If your Class C devices sends uplink and then awaits ACK, then it behaves like a Class A device-- the implementation is identical.

**Comment by gmbankar37** [comment]
So when and how are "immediate" downlinks generated?

**Comment by gotthardp** [comment]
Via a Backend Connector (see the documetation).
