### ISSUE TITLE
GatewayID as only numbers

### ISSUE THREAD

**Issue by ToniStonde** [gotthardp/lorawan-server#544]
If gatewayID (MAC) is only numbers LoRaWAN gives unknown mac error and displays the address as '0000000000000000' even when MAC is correctly inserted for the gateway.

**Comment by gotthardp** [comment]
Could you send me a screenshot of the MAC being numbers only, please?

**Comment by ToniStonde** [comment]
![image](https://user-images.githubusercontent.com/34884454/49438199-4e0f2200-f7c6-11e8-8cf0-152975aef626.png)

In the gateway itself:

option gateway_ID '3338333041005200'

If I replace any number in that with 1 letter all OK. So im not sure its the cause the lora_pkt_forwarder itself or LoRaWAN but atleast in the device side all seems to be OK.

**Comment by gotthardp** [comment]
That's weird, but possible. Would you please be able to capture the JSON structure sent by the gateway to the server? Either in the gateway's log (if it's logged) or by the Wireshark tool.

**Comment by ToniStonde** [comment]
Well Wireshark only shows the json like this:

{"txpk":{"powe":16,"imme":false,"tmst":2166238616,"codr":"4/5","datr":"SF12BW125","freq":869.525,"modu":"LORA","rfch":0,"ipol":true,"size":13,"data":"YOZfKxIBBgAGcy/RXw=="}}

Do you have your own gateway which you could test in your own env? So just change the GatewayID to only numbers and then restart the service which forwards the packets?

**Comment by ToniStonde** [comment]
Well actually i think the bug is in the lora_pkt_fwd:

"gateway_ID":"333833304b005200"

"gateway_ID":3.3383330410052e+15

After the lora_pkt_fwd parses the configs if only numbers it displays it like that in the bottom. If it has atleast one letter, then OK (like the upper example)

**Comment by gotthardp** [comment]
so, it's a lora_pkt_fwd bug, shall I close this issue?

**Comment by ToniStonde** [comment]
I think so. Sorry for bothering :)

**Comment by gotthardp** [comment]
That's OK :)
