### ISSUE TITLE
Latest version installed but no choice "Custom binary" in handlers

### ISSUE THREAD

**Issue by BouTayehGaby** [gotthardp/lorawan-server#546]
I have installed the most recent lorawan-server on my gateway (v6.0.3).
However, on the webadmin, when creating a handler, there are only two choices for the payload: "ASCII and Cayenne LPP". The "Custom binary" is not available. Any idea why? 

![no_custom_binary](https://user-images.githubusercontent.com/24385183/49449145-8fa9c800-f7da-11e8-82e5-3eb2975d8f60.PNG)

**Comment by BouTayehGaby** [comment]
Thank you, it worked! it was indeed a cashe problem.

**Comment by gotthardp** [comment]
I am glad it works.
