### ISSUE TITLE
DevEUI for ABP devices

### ISSUE THREAD

**Issue by JoobyPM** [gotthardp/lorawan-server#549]
It will be great if its possible to add parameter deveui for ABP devices.
Right now as a quick fix we are using `App Arguments `.

**Comment by altishchenko** [comment]
@JoobyPM You can use commissioned for that. Just fill in the form for DevEUI and link it to your ABP device in the last field. This way you will be able to use {devui} expansion template in your handler.

**Comment by gotthardp** [comment]
Exactly. I really recommend this approach.

**Comment by JoobyPM** [comment]
@altishchenko thank you.
