### ISSUE TITLE
websocket - timestamp

### ISSUE THREAD

**Issue by Marcze** [gotthardp/lorawan-server#55]
It would be beneficial to add timestamp into json structure trasmitted by websockets to clients.
The best if the field is copied from packet_forwarder structure (precision time when rx radio frame is received by a gateway).

**Comment by gotthardp** [comment]
Agreed.

**Comment by gotthardp** [comment]
Well, I believe the latest 'master' branch already includes this timestamp (in the "rxq" sub-structure). Cpuld you confirm? Please note it is included only when the GPS signal is available.

**Comment by Marcze** [comment]
Unfortunately, I don't have GPS in my gateway, moreover it is located
inside a building, can have troubles to get gps fix.

**Comment by gotthardp** [comment]
Without GSP you get only the gateway internal time. For what purpose do you need this?

**Comment by Marcze** [comment]
You can add the best time you have, gps or if not available gateway time.
My gateway time is synched with network time. I need to have measurements
sychronised. With Gps time you can try to do localisation, when more
gateways are available. I put jsons to my application database at different
server, now I add time at database level that is less reliable - network
latency.

**Comment by gotthardp** [comment]
Done. Look for `datetime`.

**Comment by Marcze** [comment]
Hi Peter,

Have troubles to compile sources. See photo below. Pls advise.

Marek



[image: Inline image 1]

**Comment by gotthardp** [comment]
I don't see the photo, but:
 * do you have Erlang 19+? It no longer compiles with Erlang 18. (I have to respect a decision taken by the cowboy server developer.)
 * did you do `make upgrade` before compiling?

**Comment by Marcze** [comment]
Hi, You're right Erlang 19. Best regards, Marek
