### ISSUE TITLE
Release 0.6.4: version number in src/lorawan_server.app.src does not match

### ISSUE THREAD

**Issue by xypron** [gotthardp/lorawan-server#555]
The version number 0.6.3 in src/lorawan_server.app.src should match the release number 0.6.4.
Maybe just bump both to 0.6.5 and drop tag 0.6.4.

**Comment by hallard** [comment]
Makes sense,
I build the latest version on Lorix and Multitech, both says 0.6.3, I know now it's just a matter of number instead of bad version

**Comment by gotthardp** [comment]
Yeah, that was my error. The 0.6.5 has been released (and 0.6.6) is on its way.
