### ISSUE TITLE
REST API /nodes not found

### ISSUE THREAD

**Issue by Kralg** [gotthardp/lorawan-server#56]
I am trying REST API commands and with /nodes I am getting page can't be found. At the moment I have one device activated over OTAA and probably it should be displayed there. In can see it in /devices and links. Or am I using it wrong?

**Comment by gotthardp** [comment]
the `/nodes` is called `/links` on older versions, please try that. sorry for the confusion

**Comment by Kralg** [comment]
I see, thanks.
