### ISSUE TITLE
Download function cannot set devaddr and port

### ISSUE THREAD

**Issue by xypron** [gotthardp/lorawan-server#572]
A handler can be set up to subscribe to a MQTT topic. Currently the device address must be either part of the topic address or must be provided as field *devaddr* in a JSON message.

MQTT messages may be more complex, e.g.

```
{
	"metadata": {
		"timestamp": "2019-01-01T12:00:00Z"
	},
	"desired": {
		"12345678": {
			"tempmin": 51,
			"tempmax": 54,
			"pressmin": 1.6,
			"pressmax": 1.8
		}
	}
}
```
where *12345678* shall be the devaddr.

In the download function we need to be able to set the devaddr, the deveui, the port, and the data. Further we should consider the possibility that one MQTT message has to be translated into multiple LoRaWAN messages sent to different ports or devices.

I suggest to parse the output of the conversion function as follows:

* If the output is a binary, use it as today.
* If the output is a map, check for keys *devaddr*, *deveui*, *port*, *data* and set up the message accordingly.
* If the output is an array of maps, create one message per map.

The function to change is lorawan_application_backend:handle_downlink().

**Comment by gotthardp** [comment]
Yeah, that makes sense.
