### ISSUE TITLE
delayed gateway network delay graph 

### ISSUE THREAD

**Issue by pdl86** [gotthardp/lorawan-server#577]
Hello 

in the gateway status page,  the network ddelay graph is "delayed" by almost 1.5 day .
![image](https://user-images.githubusercontent.com/30148795/50846251-03596a80-136f-11e9-9b8f-4e5c3781b47c.png)

the above screen shot was taken today : Jan 08 at 5:55PM , and the latest network delay displayed is dated back jan 7th 08:32 AM
the  linux machine running the lorawan server has the correct date.

Any idea ? 

regards
Philippe

**Comment by pdl86** [comment]
Hello 

without doing nothing, "suddenly" the Network delay graph catch up somewhat but strangely : 
![image](https://user-images.githubusercontent.com/30148795/50852168-1aa05400-137f-11e9-92b4-19a0e7f70b5d.png)

**Comment by pdl86** [comment]
Note that the Network delay at 60/100 msec is "normal" as this gateway is linked to the server via a low bw/high latency link., but the display of all  delays vertically is not really normal.

**Comment by pdl86** [comment]
It seems that the first issue is related to the fact that the "remote" gateway with the  packet forwarder does not have "joined" devices, and the second graph pops up when a device join the lorawan sevrer ( via the gateway) .

**Comment by gotthardp** [comment]
The delay is calculated upon downlink. If there is no downlink, the delay cannot be calculated. The graph was not delayed, it simply didn't move because there were no downlinks.
