### ISSUE TITLE
Add Basic Auth for REST API

### ISSUE THREAD

**Issue by hallard** [gotthardp/lorawan-server#578]
Peter,
Would it be possible to add basic auth (I'm using SSL) to the REST API
I need to request data from a browser with JQuery (or any js) and Digest Auth lib, but none of them work. I tried and implemented :

 - `https://github.com/inorganik/digest-auth-request`
 - `https://github.com/Kynec/digest-ajax`

Curl with digest is working fine, so the problem is not on the server side but on client side (JS) and also, a lot of people have trouble with this javascript implementation.

Since this kind of problem is also mentioned in #502 and #564 so adding option to switch to basic auth would save some lot of time, including me.
Thanks

**Comment by gotthardp** [comment]
Hello. Yes, I will re-introduce Basic Auth pretty soon. I need it myself.

**Comment by hallard** [comment]
Waiting this to be implemented, is there any way to disable authentication? 
I know it's not secure but It's for testing on local net only.
thanks

**Comment by gotthardp** [comment]
Are you able to git pull and test the latest HEAD, please? It's easier to implement it than to disable it :)

**Comment by hallard** [comment]
Yes I'm able but the final target is a multitech conduit so need to recompile whole image. Is it done in 0.6.5 version ?

**Comment by gotthardp** [comment]
Yes, it is in the 0.6.5 I released few hours ago.

**Comment by hallard** [comment]
Awesome, thanks, how do we enable it ?

**Comment by gotthardp** [comment]
No configuration. Just send the Basic Authentication header in your request.
