### ISSUE TITLE
uplink fail (re-up)

### ISSUE THREAD

**Issue by BouTayehGaby** [gotthardp/lorawan-server#584]
hello!

Why my gateway is failing to upload data to the app server (red arrow, when I hover the mouse over it, it says "re-up")? I checked the configuration of my handler and my connector it seems correct. I tried to use postman to simulate and uplink to my app server, and the app server is working just fine.
Another unrelated question, what is the field "confirmed"?
![re-up](https://user-images.githubusercontent.com/24385183/51526321-613b8700-1e32-11e9-8149-5212869ff47e.PNG)

Thank you

**Comment by gotthardp** [comment]
Hello. Re-Up means "repeated uplink". All your uplink frames have FCnt=0, so the server considers them as a retransmissions of one uplink frame.
"Confirmed" means "Confirmed uplink", i.e. request for ACK (see LoRaWAN standard for more details.)

**Comment by BouTayehGaby** [comment]
In fact, they all have Fcnt 0 since In my code I am sending only one frame and then the sensor stops, there is no loop. (just for testing). You can see in the figure below that these frames are different (they have different payloads)
![question](https://user-images.githubusercontent.com/24385183/51991691-eadefa80-24ab-11e9-8500-55e728040348.PNG)

What could possibly cause a fail in uplink? The other Application (Pysens Sensor, seen in the figure) is able to transmit the data to the app server without any problem, however, the GPSsensorHandler fails to do so, although the data is being sent to the same web application.

**Comment by BouTayehGaby** [comment]
I put the code in a loop and tried to send multiple frames successively, it Worked! Am I missing something?  Why would it work for multiple transmissions but not for a single one?

**Comment by altishchenko** [comment]
@BouTayehGaby Hello, your gateway has nothing to do with the FCnt counter, that is your device that is sending the data uplinks and not increasing the Up counter, hence the server ignores the data as ducplicate. You can check if that is the correct data by disabling the FCnt check in your device's Profile.

**Comment by gotthardp** [comment]
Yeah. The server ignores retransmitted frames, so if the FCnt is the same it does not sent anything to backend. Try setting the "FCnt check" in your device profile to "Disabled".

**Comment by BouTayehGaby** [comment]
Thank you. Problem Solved, you may close this issue.
