### ISSUE TITLE
too many bad_mic

### ISSUE THREAD

**Issue by gmbankar37** [gotthardp/lorawan-server#589]
Hii, 
 I have more than 5 devices. I have kept  the app_eui and app_key of every node as same. I am joining them to the server by otaa. I am randomly receiving bad_mic even after I get some packets. So after sometime the node suddenly starts sending bad_mic. I tried to tackle the problem using the troubleshoot doc but the problem is too frequent. What would be the reason?

**Comment by gotthardp** [comment]
How long is "after some time"? The bad_mic could be sent after 65535 uplinks when "reset on zero" is set. Also, bad_mic could be sent when the OTAA Join is received and handled by two servers.
