### ISSUE TITLE
dbexport ERROR

### ISSUE THREAD

**Issue by bashhole** [gotthardp/lorawan-server#592]
Hello how do I export?

root@a9270261552:/usr/lib/lorawan-server/bin# ./dbexport 
http://localhost:8080/api/users:
2019-02-05 12:54:30 ОШИБКА 404: Not Found.
http://localhost:8080/api/gateways:
2019-02-05 12:54:30 ОШИБКА 404: Not Found.
http://localhost:8080/api/networks:
2019-02-05 12:54:30 ОШИБКА 404: Not Found.
http://localhost:8080/api/multicast_channels:
2019-02-05 12:54:30 ОШИБКА 404: Not Found.
http://localhost:8080/api/profiles:
2019-02-05 12:54:30 ОШИБКА 404: Not Found.
http://localhost:8080/api/devices:
2019-02-05 12:54:30 ERROR 404: Not Found.
http://localhost:8080/api/nodes:
2019-02-05 12:54:30 ERROR 404: Not Found.
http://localhost:8080/api/ignored_nodes:
2019-02-05 12:54:30 ERROR 404: Not Found.
http://localhost:8080/api/handlers:
2019-02-05 12:54:30 ERROR 404: Not Found.
http://localhost:8080/api/connectors:
2019-02-05 12:54:30 ERROR 404: Not Found.

**Comment by gotthardp** [comment]
Which server version are are you running?
Could you please post few last lines from the server log showing the error message?

**Comment by bashhole** [comment]
Version 0.5.5 
/var/log/lorawan-server/error.log Nothing not say from dxexport

**Comment by bashhole** [comment]
./dbexport creates a backup folder and creates json files inside, but they are empty

**Comment by gotthardp** [comment]
Is there *any* error in the log file? There must be at lest the 404 Not Found error. If there is *no* error, then there is some other server listening on the port 8080.

**Comment by bashhole** [comment]
i get http://185.127.25.13:8080 or http://localhost:8080
output from web
" Cannot GET /"

**Comment by gotthardp** [comment]
What does `netstat -tlp` print for port 8080. I am pretty sure there is something else listening, or the server installation is broken.

**Comment by bashhole** [comment]
I figured it out myself, just went to the page and copied the json
