### ISSUE TITLE
WebSocket handle pong

### ISSUE THREAD

**Issue by hallard** [gotthardp/lorawan-server#598]
We can keep websocket connector alive sending 'ping' but looks like the server does not answer 'pong' to ping command so it can be difficult sometimes to handle disconnected. 
Would it be a request feature ?

**Comment by gotthardp** [comment]
I guess this is a bug. The server shall respond to ping frames. Are you sure it does not?

**Comment by hallard** [comment]
I tried in my code, no success, so tried with chrome websocket extension
It receive server data but does not seems to answer to ping

![image](https://user-images.githubusercontent.com/2471931/52950429-6a5f3b80-337f-11e9-838c-227f409f9a27.png)

**Comment by hallard** [comment]
Works my fault
don't send text string like `ws_client.send('ping');`
but with ping command
`ws_client.ping('ping');`
