### ISSUE TITLE
bad_appeui 

### ISSUE THREAD

**Issue by jot4p** [gotthardp/lorawan-server#602]
Hi, 

I installed "bosch parking sensors" and registered on the commissioned list of devices:

![image](https://user-images.githubusercontent.com/15892047/53160025-f612db00-35be-11e9-8bdb-0631b0071d60.png)

I receive:
![image](https://user-images.githubusercontent.com/15892047/53108181-789f8a00-352e-11e9-823e-496f98fb46d7.png)

![image](https://user-images.githubusercontent.com/15892047/53159921-c368e280-35be-11e9-8160-07ca28323eaa.png)

What is the problem? 

I only have DEVICE EUI from node.

Thanks

**Comment by jot4p** [comment]
If I introduce the AppKey and AppEUI the problem is the same for all devices..

**Comment by gotthardp** [comment]
Bad AppEUI is just a check. Did you try to set the AppEUI indicated by the error message?

**Comment by jot4p** [comment]
No..  because bosch says that AppEUI is FCD6BD0000190000..

**Comment by gotthardp** [comment]
But this is the same number, just with a reverse byte order. Sometimes the hex-strings are reversed.

**Comment by jot4p** [comment]
problem solved xD

**Comment by dp512** [comment]
> problem solved xD

I have exactly same issue "bad_appeui" with Bosch parking sensors. How did u resolve the issue?

**Comment by altishchenko** [comment]
> > problem solved xD
> 
> I have exactly same "bad_appeui"-issue with Bosch parking sensors. How did u resolved it?

He reversed the bytes in the AppEUI config parameter :)
FC.D6.BD.00.00.19.00.00 became 00.00.19.00.00.BD.D6.FC
This happens between different node libraries and manufactures.
