### ISSUE TITLE
Add GW position on uplink fields handler

### ISSUE THREAD

**Issue by hallard** [gotthardp/lorawan-server#610]
Hi Petr,
Would it be possible when available to add fields for gateway GPS position on best_gw and all_gw fields such as when querying `/api/gateways` ?
```
      "gpsalt":91,
      "gpspos":{  
         "lat":46.65747,
         "lon":0.36514
      },
```

Thanks

**Comment by Apaisal** [comment]
I agree! I think It is necessary for geolocation feature.

**Comment by pdl86** [comment]
I agree to and in fact that what I was looking for in #391.

**Comment by gotthardp** [comment]
Hello. I implemented the two new fields. Will you please test it before I make a release?

**Comment by hallard** [comment]
@Petr 
Sure, any chance to add #612 so I can test both on the same time because each time I need to rebuild firmware and flash GW ?

**Comment by gotthardp** [comment]
Implementing extra buttons is quite complicated, so that one will not be as easy as this.

**Comment by pdl86** [comment]
Hello

working with Charles, as stated testing is not so easy do to time to
rebuild.
Is there a chance that you fix aslo #582 (devices description)  and #599
( Gateway description)

regards
Philippe

Le 15/03/2019 à 16:11, Petr Gotthard a écrit :

**Comment by gotthardp** [comment]
@hallard, did you also test this? Is everything OK so I can make a release?

**Comment by hallard** [comment]
Sorry,
yes it works, sorry for the delay

**Comment by javobarra** [comment]
Hi Pietr! Is it possible to make independent mqtt message with Gateway parameters?? Or the only way to send Gateway parameters is when receive a node message?
i created a handler and connector for send via mqtt only Gateway parameters. But i think this is not possible to do it

Thanks
