### ISSUE TITLE
Read binary values from a frame (erlang fun)

### ISSUE THREAD

**Issue by elisascheer** [gotthardp/lorawan-server#611]
Hi,

I'm trying to decode frames sent by devices using the function fun() as it is describes in https://github.com/gotthardp/lorawan-server/blob/master/doc/Handlers.md#parse-uplink. 
But I am facing an issue, for example one device sends this kind of frame : 

40 AB 00F1 0002 0001 0000 9C

40 means it's a data frame and I am able to handle this with 

fun(Fields, <<16#40, Status, Tor1:16, Tor2:16, Tor3:16, Tor4:16, Details>>)->
#{status => Status, tor1 => Tor1, tor2 => Tor2, tor3 => Tor3, tor4 => Tor4, details => Details}
 end.

But what I want to be able to do is getting the Details field 0x9C and convert it to 10011100 so that I can compare states of TOR. Do you know how I can do that using fun ? I am a beginner in this language.

**Comment by gotthardp** [comment]
Hello. Do you know you can handle individual bits? I.e. do:
```erlang
fun(Fields, <<16#40, Status, Tor1:16, Tor2:16, Tor3:16, Tor4:16, D7:1, D6:1, D5:1, D4:1, D3:1, D2:1, D1:1, D0:1 >>)->
#{status => Status, tor1 => Tor1, tor2 => Tor2, tor3 => Tor3, tor4 => Tor4}
end.
```
Or you want to achieve something else?

**Comment by elisascheer** [comment]
Yes that was I wanted to achieve, thank you!
