### ISSUE TITLE
Unable to update device desc field with API

### ISSUE THREAD

**Issue by hallard** [gotthardp/lorawan-server#613]
@gotthardp 

I'm trying to update device desc filed using api and ajax. I can query API without any problem to get device information but as soon as I try to update `desc` field I've got an error

Here the code (authentication is working and setup another place on my html page)

```js
// Set default request parameters for lorawan server 
$.ajax({ type: 'PUT',
		async : true,
		url: "/api/devices/" + deveui,
		dataType: "json",
		contentType: "application/json",
		data : { desc: "testtest" },
		success : function(dat) { 
			console.log(dat); 
		},
});
```

here is the console log

![image](https://user-images.githubusercontent.com/2471931/54448321-ba95a780-474b-11e9-8fd9-36a8609044ac.png)

And the server log
```
2019-03-15 16:58:06.357 [error] <0.13128.3> device 0001B7834167656E unknown_deveui
2019-03-15 16:58:20.116 [debug] <0.13137.3>@lorawan_admin_db_record:handle_write:157 Bad JSON in HTTP request
2019-03-15 16:58:20.120 [warning] <0.13136.3> server {http_error,{400,"/api/devices/0080000004012A78",<<>>,"192.168.1.53"}}

```

I also tried 
```
	data : JSON.stringify({ desc: dat.desc }),
```
![image](https://user-images.githubusercontent.com/2471931/54448726-b027dd80-474c-11e9-9066-c1c47eaa6e68.png)

Any idea ?

**Comment by gotthardp** [comment]
And the log in the latter case contains something?

In general, when updating an entry you have to provide ALL fields. Partial updates are not supported.

**Comment by hallard** [comment]
Yeah that's what I suspected, unfortunately, I've not all the field on my form and my html table due to some optimization so I can't update all. Never mind, I will remove this feature on my app.

**Comment by gotthardp** [comment]
Not so fast :) Update of individual fields can be enabled for selected fields. I believe it is useless for all fields, so I enable it only when needed. So if, you need I can add a few for your app.

**Comment by hallard** [comment]
Awesome, here we just need the desc field, but may be the appargs could be an option also.

**Comment by gotthardp** [comment]
only for devices or also for nodes and gateways?

**Comment by gotthardp** [comment]
The latest HEAD supports a request for an individual field, e.g.
http://localhost/api/devices/3333333666666DDD/appargs
allows you to retrieve or modify "appargs" parameter.

It works for all parameters, but for "nodes" and "devices" only.

**Comment by hallard** [comment]
Awesome,
will try it out tomorrow we don't need that for GW.

**Comment by hallard** [comment]
Compiled image, tested, works for desc field , not tested for appaprgs;-)

Thanks
