### ISSUE TITLE
API - Create new commissioned device

### ISSUE THREAD

**Issue by jot4p** [gotthardp/lorawan-server#618]
Hi, 

![image](https://user-images.githubusercontent.com/15892047/55069695-8e97f180-507c-11e9-845e-e3421325c9ca.png)

What is the complete command to put information via API and create a new commissioned device ?

**Comment by gotthardp** [comment]
Well, do `HTTP GET /api/devices/xzy` and you will see a JSON structure that is corresponding to the web admin fields. Create a JSON with the mandatory fields and do `HTTP POST /api/devices`.

**Comment by jot4p** [comment]
{
"appeui":"XXXXXXXXXXXXXX",
"appkey":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"deveui":"XXXXXXXXXXXXXXXXX",
"node":"E0E0E0E0",
"profile":"device_profile"
} 

ok, like that.

**Comment by gotthardp** [comment]
OK like this
Even the "node" is not needed. If not provided it is generated upon join.
