### ISSUE TITLE
Event=delivered for confirmed downlink 

### ISSUE THREAD

**Issue by stefanobimbo** [gotthardp/lorawan-server#628]
I use version 0.6.7
I experience some strange behaviors with confirmed downlink messages.
When the cloud application sends a confirmed downlink message to an end-node, then it receives the event "delivered" even if the end node hasn't received the message (the application interfacing the end-node LoRa module, that is Telit RE866A1-EU, doesn't receive anything on the serial line).

I would like to know if the network server sends to the application the event="delivered" ONLY when it receives back an ACK from the end-node to the confirmed downlink message previously sent, or if there are other conditions for the event "delivered".

Is there a way to set the log to be more verbose, to follow all the confirmed downlink message processing?

**Comment by gotthardp** [comment]
Hello. Yes, the "Delivered" event is sent if and only if the ACK from the device was received. There are no additional logs to follow the delivery.
