### ISSUE TITLE
event=lost

### ISSUE THREAD

**Issue by stefanobimbo** [gotthardp/lorawan-server#630]
I use ver=0.6.7

I would like to know what event="lost" means and when that event is sent in response to a confirmed downlink request. Is there a sort of timeout in the network server?

**Comment by gotthardp** [comment]
There is the "D/L Expires" setting:
https://github.com/gotthardp/lorawan-server/blob/master/doc/Handlers.md#administration

The event "lost" is sent when a new downlink supersedes the previous one.
