### ISSUE TITLE
[Enhancement] Semtech LNS protocol

### ISSUE THREAD

**Issue by xypron** [gotthardp/lorawan-server#631]
Are there any plans to support the Semtech LNS protocol (https://doc.sm.tc/station/tcproto.html)?

**Comment by gotthardp** [comment]
So far no plans. The protocol seems to be developed (the sm.tc domain is owned) by Trackio GmbH, so Semtech is not(?) involved. Once this software attracts some users we could implement it.

**Comment by xypron** [comment]
This is the the announcement by Semtech
https://www.semtech.com/company/press/semtech-announces-open-source-software-for-lora-based-gateways-at-the-things-conference

It pointed me to https://github.com/lorabasics/basicstation, which in turn links to https://doc.sm.tc/station.

https://github.com/lorabasics/basicstation/blob/master/LICENSE indicates Semtech as copyright owner.

**Comment by gotthardp** [comment]
Alright, this changes everything. I will implement that.

**Comment by gotthardp** [comment]
Done. Will be in v0.7.0
