### ISSUE TITLE
How many devices ?

### ISSUE THREAD

**Issue by Ilheu** [gotthardp/lorawan-server#636]
Hi, 
I would like to implement your lorawan-server in my project, which consists of sending several sensor telemetry to the Azure Iot Hub. Can your solution handle many devices (thousands) ? 
(I know that this is not a issue, but I have no permission to acess  lorawan-server mailing list that you mention).

**Comment by gotthardp** [comment]
Hello. The server itself can easily handle thousands on devices. However, you may find the web-admin features insufficient for handling such amount of devices.

**Comment by Ilheu** [comment]
Hello,
Thanks for the answer !
Can you clarify a question for me? How do I generate Device DevEUI for each
device, in other Network Servers, these keys are generated by them.


Em sáb, 11 de mai de 2019 às 10:44, Petr Gotthard <notifications@github.com>
escreveu:

**Comment by gotthardp** [comment]
DevEUI is (also in this server) auto-generated upon device Join.

**Comment by Ilheu** [comment]
Oh ok, thank you for your feedback !
Can you explain me what is the best workflow ( or creation order) in order
to configure the server ? I already understood that I need to create a
group before the devices, but before that I should create a network, is
that right ? Do you have any order ? At least for an simple example with 10
devices in one network/group ...
Greetings !

Em ter, 14 de mai de 2019 às 17:14, Paulo Ilheu <p.ilheu93@gmail.com>
escreveu:

**Comment by gotthardp** [comment]
The Configuration Guide shows that order
https://github.com/gotthardp/lorawan-server/blob/master/doc/Configuration.md#run-time-parameters

**Comment by Ilheu** [comment]
I think that you already noticed it, I get this error, is there any
solution to solve it ?


[image: image.png]

Em qua, 15 de mai de 2019 às 10:05, Petr Gotthard <notifications@github.com>
escreveu:

**Comment by gotthardp** [comment]
I don§t see the screenshot

**Comment by Ilheu** [comment]
Sorry ...

Em qua, 15 de mai de 2019 às 12:45, Petr Gotthard <notifications@github.com>
escreveu:

**Comment by Ilheu** [comment]
![error](https://user-images.githubusercontent.com/8053606/57785289-5da57600-7729-11e9-9846-7bedbfa43411.PNG)

**Comment by gotthardp** [comment]
I guess it is because you didn't set the **Google API Key**
https://github.com/gotthardp/lorawan-server/blob/v0.6.7/doc/Server.md#configuration

**Comment by Ilheu** [comment]
I already connected one gateway, but how can I generate devices' NwkSKey and AppSKey ?

**Comment by gotthardp** [comment]
These are created by the device manufacturer.

**Comment by Ilheu** [comment]
I can get the APPEUI and DEVEUI trough the device's Lora Module (in this case rn2483), but I think that the AppKey should be generated by the server ... 

"AppKey: The AppKey is the data encryption key used to "encode" the messages between the end nodes and the Application Server. The AppKey is typically a random generated number who is programmed into the end nodes and also communicated to the Application server (so that it can decode the messages). " said in https://www.centennialsoftwaresolutions.com/blog/deveui-appeui-joineui-and-appkey

**Comment by gotthardp** [comment]
AppKey is a unique key that is generated by whoever flashes the firmware to the device. Server just stores and uses this value.

**Comment by Ilheu** [comment]
But in The Things Network, it is generated by the server ... 
![image](https://user-images.githubusercontent.com/8053606/57864315-9447c300-77f3-11e9-99b5-9e14e35e2270.png)

**Comment by gotthardp** [comment]
It's a different implementation. :-) Some people buy an off-the-shelf device and cannot change the AppKey, so there definitely must be an option to set whatever AppKey is hardcoded in the device.

What exactly is your issue? You can use whatever is in the device, or you can generate your own number. It can be any number, so you're free to use e.g. https://www.browserling.com/tools/random-hex to generate a list of 32-digit numbers.

**Comment by gotthardp** [comment]
People that have many devices are very often using the HTTP API to configure their devices, so they are generating the AppKey via their script, e.g. by `tr -dc 'A-F0-9' < /dev/urandom | head -c32`.

**Comment by Ilheu** [comment]
We made our device, but if it can be a random generated one that's ok ... We are trying to join our device in the network server, but we are always receiving denied message. And some times I get http_errors , like this image : 
![image](https://user-images.githubusercontent.com/8053606/57872007-a5e49700-7802-11e9-94f1-5ee36f794289.png)

I think I configured everything like your documentation says, I configured an Commissied device like the image below : 

![image](https://user-images.githubusercontent.com/8053606/57872331-5d79a900-7803-11e9-976d-4551100795c0.png)

Do I need to create an Activated node too ?!

**Comment by gotthardp** [comment]
Have a look on the Event List to see some details for that error. Those errors are generated by the web-admin when you try to access the resource that doesnt exist. Its not related to device to server communication.

**Comment by gotthardp** [comment]
When you are using OTAA (your devices send Join), then the Activated node is auto-created. Having a Commisioned device like you have should be enough.

**Comment by gotthardp** [comment]
You should see at least a "Join" frame from the device. When you don't see really anything, then the device didn't send anything, the GW didn't receive it or didn't send it to the server.

**Comment by Ilheu** [comment]
Than you for your help ! I think it might be a problem in the gateway, we are receiveing the same error connecting to TTN !

**Comment by Ilheu** [comment]
Sorry to be annoying, but can you help me to debug this ? I can connect with the same device and gateway to the TTN, but can't connect your network server  ... 
Is there any way to check if the gateway is receiving any package ?

**Comment by gotthardp** [comment]
No problem :)
1) Does the server say "connected" in the timeline when you start the gateway? The gateway shall have a green "check".
2) The gateway has its own logs. Are there any errors/undelivered frames logged?

**Comment by Ilheu** [comment]
1. 
![image](https://user-images.githubusercontent.com/8053606/57921073-69fa1200-7894-11e9-96fa-408e0c89d272.png)

2. Are you talking about the status tab or in the gateway interface ?
![image](https://user-images.githubusercontent.com/8053606/57921133-89913a80-7894-11e9-8e21-9ef02e1be0c2.png)

I using a Dragino, I don't know if it has any issue with your network server ...

**Comment by gotthardp** [comment]
This looks good. You should really check the gateway and server logs to see if the frame was received and what happened afterwards.

**Comment by Ilheu** [comment]
Finally found the logs ...

![image](https://user-images.githubusercontent.com/8053606/57940969-8b272680-78c5-11e9-9a64-37d327f41ae4.png)

**Comment by gotthardp** [comment]
Yeah, "RF packets received by concentrator: 0" Is there anywhere some higher number? If not, then the gateway is not receiving anything (and thus cannot send it to the server). Not sure why it works with TTN though.

**Comment by Ilheu** [comment]
I'm receiving ...

![image](https://user-images.githubusercontent.com/8053606/57943305-9ed58b80-78cb-11e9-9627-6a5fd6898e19.png)

**Comment by gotthardp** [comment]
Alright, good. Then there should be something in the server logs. Could you check that, please?

**Comment by Ilheu** [comment]
Finally we did it ! Thank You so much ! 
![image](https://user-images.githubusercontent.com/8053606/57944780-f544c900-78cf-11e9-837a-a41af95a5826.png)

**Comment by gotthardp** [comment]
Cool! I am glad it works.
