### ISSUE TITLE
Can't join LAIRD Lora module to  Lorawan Server

### ISSUE THREAD

**Issue by Matavulj** [gotthardp/lorawan-server#638]
Dear Gotthard,
I tried to connect  LAIRD Development kit (DVK-RM186) with LAIR gateway RG186  to Loriot Lorawan server and everything was OK. I can see sent text data. After that I tried the same with your Lorawan server  but without succeed.   Gateway connects to Lorawan server but module can't join to network. I can see some crash in Logs. I installed Windows version v0.6.7 and Erlang 19. 
Please help, I don't know why server crashed. I send you some pictures (adjustments) and logs in attachment. See time 19.05.2019 at 10:15
Matavulj
[crash.log](https://github.com/gotthardp/lorawan-server/files/3194905/crash.log)
[debug.log](https://github.com/gotthardp/lorawan-server/files/3194906/debug.log)
![EditDevice_LoraServer](https://user-images.githubusercontent.com/50793510/57979919-3a7a0f80-7a24-11e9-9bea-3db658e49060.png)
![EditProfiles](https://user-images.githubusercontent.com/50793510/57979920-3a7a0f80-7a24-11e9-93ef-9c83abe6ef03.png)
![EditProfiles_ADR](https://user-images.githubusercontent.com/50793510/57979921-3b12a600-7a24-11e9-81ae-9804d030a895.png)
[error.log](https://github.com/gotthardp/lorawan-server/files/3194907/error.log)
![Gateway_Advanced](https://user-images.githubusercontent.com/50793510/57979922-3bab3c80-7a24-11e9-8c52-32febe783e14.png)
![Gateway_Forwarder](https://user-images.githubusercontent.com/50793510/57979923-3bab3c80-7a24-11e9-8f8c-8de523964f69.png)
![GatewayAdvanced](https://user-images.githubusercontent.com/50793510/57979924-3c43d300-7a24-11e9-8ebc-4954e3b8cb75.png)
![GatewayForwarder](https://user-images.githubusercontent.com/50793510/57979925-3c43d300-7a24-11e9-9c63-7b26089c5aa7.png)
![GatewayLog](https://user-images.githubusercontent.com/50793510/57979926-3c43d300-7a24-11e9-935c-d16c485e5e1f.png)
![GatewayPacketDetail](https://user-images.githubusercontent.com/50793510/57979927-3cdc6980-7a24-11e9-9afb-8c17ede67231.png)
![LoraServerDashBoard](https://user-images.githubusercontent.com/50793510/57979928-3cdc6980-7a24-11e9-8643-f0cdc9c9bfb8.png)
![Network_ADR](https://user-images.githubusercontent.com/50793510/57979929-3d750000-7a24-11e9-88cf-381270299fad.png)
![Network_General](https://user-images.githubusercontent.com/50793510/57979930-3d750000-7a24-11e9-85e0-2fcc5a6c6a9e.png)
![UwTerminal](https://user-images.githubusercontent.com/50793510/57979931-3e0d9680-7a24-11e9-97c8-7fd756920235.png)

**Comment by gotthardp** [comment]
Please send me the crash logs.

**Comment by Matavulj** [comment]
Petr,
Thanks for quick answer. You have crash.log in the beginning of  this issue, billow my signature and the first picture.

**Comment by Matavulj** [comment]
I send you error.log also in this attachment. You have also **debug.log**    with **crash.log** in the beginning of this issue.
[error.log](https://github.com/gotthardp/lorawan-server/files/3195472/error.log)

**Comment by gotthardp** [comment]
This seems to be Erlang issue. You have Erlang/OTP 19.0, right? Please try upgrading to 19.1 (or later).

**Comment by Matavulj** [comment]
Hi Petr,
 I installed Erlang 22 and now everything is OK. I can see data at Frames form.
Thanks a lot.

**Comment by gotthardp** [comment]
Cool :)
