### ISSUE TITLE
ABP messages

### ISSUE THREAD

**Issue by Ilheu** [gotthardp/lorawan-server#639]
After the device joined via OTAA, the server does not receive any message from the node. After OTAA the devices goes to sleep and then wakes up. Since the device has already joined via OTAA it uses ABP to join and send a message from the sensor. 

The gateway does not receive all sended messages, just some. I'm trying to send message each minute.

![Screen Shot 2019-05-20 at 11 41 34](https://user-images.githubusercontent.com/8053606/58016410-7204bc80-7af5-11e9-88ab-e1137266edd9.png)

I'm always receiving this message, but it is empty : 

![image](https://user-images.githubusercontent.com/8053606/58016491-a8423c00-7af5-11e9-9ace-7b96d68aaf19.png)

**Comment by gotthardp** [comment]
What exactly is the issue, please? "the server does not receive any message from the node" or "gateway does not receive all sended messages, just some"?

**Comment by Ilheu** [comment]
The server is not receiving any ABP message, but receives OTAA joins ...

**Comment by gotthardp** [comment]
That may be a Network configuration issue.

**Comment by Ilheu** [comment]
Is it possible to use a Initial Duty Cycle which is not in your options , for example, 0.33 % ?

**Comment by gotthardp** [comment]
No, it has a to be a 2^x fraction. This is a protocol limitation, not a server constraints.

**Comment by Ilheu** [comment]
We are receiving already ABP messages, but we get the error "not_semtech_mote" with the message. In the device profile I only have semtech-mote option.  We are using Microchip's RN2483 module. Can we fix this error, or it is not important ?

Btw, how can I transfer my lorawan-server to another computer, I'm using a Windows pc, and I want to transfer the server configuration to linux, is it possible ?

**Comment by gotthardp** [comment]
For the "not semtech mote" error, please see https://github.com/gotthardp/lorawan-server/blob/master/doc/Troubleshooting.md#not_semtech_mote

To transfer the config, please use the Export/Import scripts https://github.com/gotthardp/lorawan-server/blob/master/doc/Administration.md#backup-and-restore

**Comment by Ilheu** [comment]
I did bin/dbexport but the created file is empty ...

**Comment by gotthardp** [comment]
Any error in the log?

**Comment by Ilheu** [comment]
I'm using windows 10, the cmd window dissapears ...

**Comment by gotthardp** [comment]
I meant server log.
You can also open the window using `cmd` then `cd` to the right directory and run the script.

**Comment by Ilheu** [comment]
I already had success in the import ! Thank you ! But I still get the "not semtech mote" error.  Do I need to add an aplication for my semtech-mote ?

**Comment by gotthardp** [comment]
What application is running on your RN2483? The "semtech-mote" is a demo app from https://github.com/Lora-net/LoRaMac-node/blob/master/src/apps/LoRaMac/classA/LoRaMote/main.c#L207

If you are running somethng else you need to define a custom app. (It is safe to ignore the error but the server will not do anything useful.)

**Comment by Ilheu** [comment]
What you mean with "but the server will not do anything useful." ?!

**Comment by gotthardp** [comment]
You want to handle the application payload somehow, right? To do that you need to define an application.

**Comment by Ilheu** [comment]
Yes I need to handle application payload ! I've been reading your documentation, and I have to implement a microchip-mote application for Microchip LoRa(TM) Technology Mote, which is available at https://github.com/gotthardp/lorawan-server-demoapp. But I don't know/understand what I have to do .... Is there any tutorial ?, I just want to read the messages' data in IotHub ...

**Comment by gotthardp** [comment]
You can also send the payload to some external server via MQTT etc.

**Comment by Ilheu** [comment]
I just want to save the messages in azure iotHub ...

**Comment by gotthardp** [comment]
Then you don't need to develop anything. Just follow the https://github.com/gotthardp/lorawan-server/blob/master/doc/Integration.md#microsoft-azure-iot-hub

**Comment by Ilheu** [comment]
My connector has status: failed .... 

My node is : 

![image](https://user-images.githubusercontent.com/8053606/58177991-43c1e100-7c9d-11e9-94f7-35e335ce3b20.png)

My connector general:

![image](https://user-images.githubusercontent.com/8053606/58178142-84215f00-7c9d-11e9-8c26-a5a838af1136.png)

My connector Auth: 

![image](https://user-images.githubusercontent.com/8053606/58178193-a2875a80-7c9d-11e9-88a5-0c900ca388b8.png)

**Comment by gotthardp** [comment]
It's the `Failed` flags. You can delete them by hand as it may be caused due to some previous activity. If they appear again you should check the logs and fix the problem before deleting the flag again.

**Comment by Ilheu** [comment]
I deleted the flags, but I'm not receiving anything in azure iothub ... 

 - is devaddr in the "devices/{devaddr}/messages/events/", the node DevAddr ?

**Comment by gotthardp** [comment]
Yes.

**Comment by Ilheu** [comment]
Do you have any idea why I am not receiving the messages ?

**Comment by Ilheu** [comment]
Do I need a handler ?

**Comment by gotthardp** [comment]
Of course :)

**Comment by Ilheu** [comment]
oh ok ... it is not mentioned in https://github.com/gotthardp/lorawan-server/blob/master/doc/Integration.md#microsoft-azure-iot-hub ...

**Comment by Ilheu** [comment]
I just want to send a JSON to Azure Iot Hub, what language are you using in Parse Uplink, Parse Event and Build Downlink fields ? Do I need to use them if yes, is there any documentation how to do it ?

![image](https://user-images.githubusercontent.com/8053606/58183742-bd5ecc80-7ca7-11e9-81ab-0aa8f8592385.png)

**Comment by Ilheu** [comment]
Can I test the handler ? Or just when I receive messages ?

**Comment by Ilheu** [comment]
The documentation of Azure IotHub integration is updated ?

**Comment by gotthardp** [comment]
The documentation should be up to date. The handler funs should be written in Erlang, as documented here: https://github.com/gotthardp/lorawan-server/blob/master/doc/Handlers.md#parse-uplink

There is not direct debug functionality, but you can use an online tool as explained in https://github.com/gotthardp/lorawan-server/issues/625

**Comment by Ilheu** [comment]
I read that I don't need a parse uplink ... So I don't get why it is not connecting with my iotHub, can you check the pictures above ?

**Comment by gotthardp** [comment]
I cannot see anything suspicious there. Have a look into the server and iotHub logs.

**Comment by Ilheu** [comment]
When you say server logs, you mean the events tab ?

**Comment by gotthardp** [comment]
I meant the text file with detailed logs: https://github.com/gotthardp/lorawan-server/blob/master/doc/Troubleshooting.md#troubleshooting-instructions

The iotHub might also have some debugging log showing what went wrong.

**Comment by Ilheu** [comment]
I don't see anything unusual in the server logs :


<<"87945D">>
2019-05-23 10:41:40.244 [debug] <0.2922.2>@lorawan_handler:join:114 Join-Accept in RX1: {rxq,868.3,<<"SF9BW125">>,<<"4/5">>,{{2019,5,23},{9,41,38.916699}},undefined,3816871322,-58,7.8}
2019-05-23 10:42:10.185 [info] <0.2954.2> device 0004A30B00E8AB91 {join,<<"ABC13456">>}
2019-05-23 10:42:10.186 [warning] <0.2954.2> node ABC13456 {repeated_reset,7}
2019-05-23 10:42:10.189 [debug] <0.2954.2>@lorawan_mac:encode_accept:441 Join-Accept <<"ABC13456">>, netid <<0,0,0>>, cflist [], rx1droff 0, rx2dr 3, appkey <<"C82DB0DC7CA167475F8E382B33D668A9">>, appnce <<"884A6D">>
2019-05-23 10:42:10.189 [debug] <0.2954.2>@lorawan_handler:join:114 Join-Accept in RX1: {rxq,868.3,<<"SF9BW125">>,<<"4/5">>,{{2019,5,23},{9,42,8.948648}},undefined,3846903271,-59,7.8}
2019-05-23 10:49:18.343 [debug] <0.3296.2>@lorawan_mac_commands:store_actual_adr:147 DataRate ABC13456 switched to dr 3
2019-05-23 10:49:18.344 [debug] <0.3296.2>@lorawan_mac_commands:build_fopts:77 ABC13456 <- [dev_status_req]
2019-05-23 10:49:18.345 [error] <0.3296.2> node ABC13456 {not_semtech_mote,{1,<<"993">>}}

Have you ever used Azure Iot Hub ?
I'm not receiving anything ....

![image](https://user-images.githubusercontent.com/8053606/58243927-83de9d80-7d49-11e9-8814-eb44430202e0.png)

**Comment by Ilheu** [comment]
I solved it, I had to change the application in the device profile to my handler ...

**Comment by gotthardp** [comment]
Cool. Shall I close the issue then?
