### ISSUE TITLE
message not publish to out/{deveui} topic

### ISSUE THREAD

**Issue by elisascheer** [gotthardp/lorawan-server#640]
Hi,

I declare an Application as follow : 
![Annotation 2019-05-22 121545](https://user-images.githubusercontent.com/25613727/58167040-62b77780-7c8b-11e9-9d65-35dc3250a627.png)

and I declared the associated profile as follow : 

![Annotation 2019-05-22 121646](https://user-images.githubusercontent.com/25613727/58167095-7b279200-7c8b-11e9-9d5f-d79e472b9ab2.png)

I declared my device which uses the Temperature profile created and I created my mqtt connector : 

![Annotation 2019-05-22 121754](https://user-images.githubusercontent.com/25613727/58167195-af02b780-7c8b-11e9-9473-905f5beb531e.png)

But when I subscribe to the topic
`mosquitto_sub -h 127.0.0.1 -p 1883 -t 'out/343531314F377213' -u myuser -P mypass`

nothing published and frames are received : 

![Annotation 2019-05-22 122347](https://user-images.githubusercontent.com/25613727/58167554-7b745d00-7c8c-11e9-9166-fc4f69b5c815.png)

**Comment by elisascheer** [comment]
In the debug.log there is this line :
![Annotation 2019-05-22 125357](https://user-images.githubusercontent.com/25613727/58169310-b7112600-7c90-11e9-8b22-fe8176aedac2.png)

**Comment by gotthardp** [comment]
Which server version are you using. There used to be a bug in the template handling.

**Comment by elisascheer** [comment]
I am running 0.6.6

**Comment by gotthardp** [comment]
I see now where the problem is: you have to pass the `deveui` through your parsing function. Instead of `#{fields...}` do `Fields#{fields...}` (prepend Fields) in all parts of your parsing fun.

**Comment by elisascheer** [comment]
Thanks it worked! :)
