### ISSUE TITLE
Multiple messages

### ISSUE THREAD

**Issue by Ilheu** [gotthardp/lorawan-server#643]
Hi, 
Suddently, I start receiving in my IotHub multiple messages from each end device, when a single node sends a message. But in the messages sent, the devaddr is from the real one. Some of the nodes are not working anymore, so they can't be sending data ...

More simply, I receive a message from device 1, and it sends 10 identical messages to the IotHub for each existing device ...

**Comment by gotthardp** [comment]
It's likely due to a connector misconfiguration.

**Comment by Ilheu** [comment]
I have 10 connectors, with the same handler. 

![image](https://user-images.githubusercontent.com/8053606/60032213-01c1fb80-969e-11e9-8373-0a82d9fb46a2.png)

![image](https://user-images.githubusercontent.com/8053606/60032250-130b0800-969e-11e9-9dd9-b2bc5e0e3760.png)

![image](https://user-images.githubusercontent.com/8053606/60032480-8d3b8c80-969e-11e9-9b76-4f49bb47fdef.png)

I think it is alright ...

**Comment by gotthardp** [comment]
Yes, that is as expected. With 10 connectors you get 10 messages. What is the issue?

**Comment by Ilheu** [comment]
I receive a message from ONE device, and send TEN messages with the same content and devadrr, but from each device ... So, the device 1 send me a message, and for example, the device 7 sends it too the same message ...
Like this ...
![image](https://user-images.githubusercontent.com/8053606/60035010-bdd1f500-96a3-11e9-93cc-36e3c88f32bc.png)

**Comment by gotthardp** [comment]
Isn't the DevAddr fixed for each connector? I see connector1 is linked with `ABC13456`. You should use the template `{DevAddr}` instead.

**Comment by Ilheu** [comment]
You right !! Thank you !!!
