### ISSUE TITLE
OTAA activation : issue with join-accept

### ISSUE THREAD

**Issue by quentinchanu** [gotthardp/lorawan-server#644]
Hello and thanks for your work,

I have trouble activating my node (lopy4) with OTAA on your server, (but it's working with TTN)

The warning i get in the dashboard is 'repeated reset'. 

Indeed at the first uplink of my node the server activated it correctly and sended the downlink join-accept but it looks like my node doesn't understand it because he keep sending join-request.
So now i am stuck in a loop with my node sending join-request and the server showing warnings repeated-reset.

Important fact : my gateway forward the downlink packet join-accept to my node ! Here is the terminal of my gateway and the debug.log file 

![Capture du 2019-06-25 13-39-17](https://user-images.githubusercontent.com/50479964/60095405-c5020d00-974e-11e9-90ce-a126c3e69f13.png)

![Capture du 2019-06-25 13-41-06](https://user-images.githubusercontent.com/50479964/60095463-e7942600-974e-11e9-8f68-a8c8a632a693.png)

I hope you can help me and I suppose I have not done mistake on my settings parameters but feel free to ask and i will answer you ! I was thinking of an hypothesis maybe the node cannot decode the downlink or maybe it's not encode properly ? Where can be my mistake ?

**Comment by gotthardp** [comment]
I suspect the issue is related to the downlink frequency. Did you correctly set the Region and the RX2 Freq?

**Comment by quentinchanu** [comment]
Yes i think that my settings are correct : 

![Capture du 2019-06-25 15-33-54](https://user-images.githubusercontent.com/50479964/60102839-c1768200-975e-11e9-864e-7e0aa9f54e5c.png)

**Comment by gotthardp** [comment]
`868,1` is not inline with the recommended defaults. Are you aware of this?
https://github.com/gotthardp/lorawan-server/blob/master/doc/Regions.md

**Comment by quentinchanu** [comment]
I just changed the Rx2 frequency and Rx2 DR to respect the recommended defaults and it's still not working. Is the join-accept supposed to always go through RX2 and never through RX1 ?
Where can the problem come from now ?
On the side of my server the node is activated but on the side of the node he is still sending join-request because it doesnt receive any join-accept.

**Comment by gotthardp** [comment]
It's very likely caused by a misalignment of RF settings (DR, freq, timing) of the device, the gateway and the server. I can only recommend you to re-review the configuration again.

**Comment by quentinchanu** [comment]
Yes you were right I didn't know that the Rx1 and Rx2 for join accept messages was not the same delay as classic downlink ! I fixed it and now its working ! I just have one more question and then you can close the issue : where can we set the CFlist to manage which channel to send, i found it was in the release 0.5.0 but i don't find where ? (tell me if you prefer me to open a new issue for this question)
Thanks again !

**Comment by gotthardp** [comment]
It's in the network configuration, last tab

**Comment by quentinchanu** [comment]
Last question : in the hypothesis I would like to use a single channel gateway can it be set to only one channel ? (I know that the specification is saying that you have to use at least the 3 first channels : 0-2)

**Comment by gotthardp** [comment]
There were some attempts to do that. You'd need to set the device (profile) to either RX1 or RX2 window only. The channel list is rather a device config; the server has not much to do with that.

**Comment by quentinchanu** [comment]
Thanks !
