### ISSUE TITLE
ERROR: bad_mic

### ISSUE THREAD

**Issue by RCOdev** [gotthardp/lorawan-server#65]
Hi,

I set up the LoRaWAN server with a Lorank8 gateway and a LoRa end-node (ATIM module). With ABP mode, I create the Link manually and everything is good. With another end-node, I would like to try the OTAA mode but I got this error in log : lorawan_handler:rxpk:21 ERROR: bad_mic
So no Link is automatically created...

I don't understand because with OTAA mode there is no session (Link) predefined so it can't be a mic error... Am I right?

Do you know why I get this error?

Thanks!

**Comment by gotthardp** [comment]
Check for bad_mic error in the [Troubleshooting Guide](https://github.com/gotthardp/lorawan-server/blob/master/doc/Troubleshooting.md) please.

**Comment by gotthardp** [comment]
Were you able to fix this issue?

**Comment by RCOdev** [comment]
Hi,
thank you for the link. I found my mistake, my AppKey was wrong. I used LSB first and reversed all bytes but it was not necessary.

Everything works, thanks!
