### ISSUE TITLE
How to connect my site with lorawan websocket?

### ISSUE THREAD

**Issue by Papa005** [gotthardp/lorawan-server#665]
Hello! I need to make a site where it will be displayed, what is sent to the lorawan server by the device. How to do it?
![2019-08-23 (2)](https://user-images.githubusercontent.com/36376329/63584752-44bd2400-c5a6-11e9-980d-3c2a9efc3455.png)
I already wrote this in script.js file
`let socket = new WebSocket("ws://5.134.219.10:48080/ws/event");`
what's after?

**Comment by gotthardp** [comment]
Have a look at https://github.com/gotthardp/lorawan-server/blob/master/priv/admin/ws.html

**Comment by Papa005** [comment]
I want to do something like this 
[https://github.com/gotthardp/lorawan-server/issues/474](url)
watch his site

**Comment by Papa005** [comment]
> Have a look at https://github.com/gotthardp/lorawan-server/blob/master/priv/admin/ws.html

ok

**Comment by Papa005** [comment]
Can you help me how to use it?
My connectors settings is:
![2019-08-23 (3)](https://user-images.githubusercontent.com/36376329/63585565-1b04fc80-c5a8-11e9-869d-71b6c93fa6c5.png)
And.. Sorry for my English))

**Comment by Papa005** [comment]
i mean how to use your script.

**Comment by gotthardp** [comment]
Have you read https://github.com/gotthardp/lorawan-server/blob/master/doc/Connectors.md#web-sockets?

**Comment by Papa005** [comment]
Ok, thanks. I will read. And where can i take this file? 
`<script src="/admin/jquery.min.js"></script>`

**Comment by gotthardp** [comment]
Aaah. Try `<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>` instead, or simply download it from there. Or anywhere. It's a standard jquery package.

**Comment by gotthardp** [comment]
Or you can use any websocket example, e.g. this: https://www.npmjs.com/package/jquery-simple-websocket

**Comment by Papa005** [comment]
So, i have button, which send pocket like this to server. 
![2019-08-23 (5)](https://user-images.githubusercontent.com/36376329/63588104-573b5b80-c5ae-11e9-89a6-3739232db7e5.png)


> 025BD30A3BA501 

Last numeral is type of depression. (1 - once, 2 - long press, 3 - double press).
I need simple site, which will show when i press and type of depression. 
What comand do i need?
Thank you)
Or send me some instruction of this.
My site is  [https://websockettest1.000webhostapp.com/](url)

**Comment by gotthardp** [comment]
Well, this is a standard JavaScript coding question. I suggest you check stackoverflow or any other coding site.

**Comment by Papa005** [comment]
Hello! I wrote to stackoverflow, but i didn't took answer. I think, only you can help me. So i have a little progress. Code HTML has: 
`<script src="script.js"></script>`
script.js code:
`let socket = new WebSocket("ws://5.134.219.10:48080/ws/nodes/FF09E1E2");`
`ws.onopen = function() { alert("Connection opened...") };`
And in 

> Events 

![2019-08-26 (2)](https://user-images.githubusercontent.com/36376329/63675365-51818800-c7f1-11e9-9ddf-616f27f645f2.png)
There is my button:
![2019-08-26 (3)](https://user-images.githubusercontent.com/36376329/63675467-8ee61580-c7f1-11e9-92b2-a14259dce471.png)

**Comment by Papa005** [comment]
Also i checked this code: 
`let socket = new WebSocket("ws://5.134.219.10:48080/ws/uplink");`
`socket.onopen = function(e) {
  alert("[open] Connected");
};`
And it worked, because when i opened my site, i took js messege 

> [open] Connected

But, how to tale info about connection of my button?

**Comment by Papa005** [comment]
Now, i checked this code, 
`let socket = new WebSocket("ws://5.134.219.10:48080/ws/uplink");`
`socket.onopen = function(e) {`
  `alert("[open] Connected");`
  `alert("Sending messege");`
  `socket.send("Hello");`
`};`

And i took it:
![2019-08-26 (5)](https://user-images.githubusercontent.com/36376329/63677304-59dbc200-c7f5-11e9-9b54-de79a08206be.png)
How i understood, i need to send some json command to the server, but what command?

**Comment by Papa005** [comment]
May be i need to do anything here?
![2019-08-26 (7)](https://user-images.githubusercontent.com/36376329/63679313-bd67ee80-c7f9-11e9-823f-be5bfa7c0043.png)

**Comment by Papa005** [comment]
I DID IT. EEEEE. VERY THANK YOU!! 
![2019-08-26 (9)](https://user-images.githubusercontent.com/36376329/63679890-12f0cb00-c7fb-11e9-8439-37b426ab3a9d.png)
Now i need to write this in html.

**Comment by gotthardp** [comment]
Cool. I am glad it works.
