### ISSUE TITLE
MQQT uri not accepted

### ISSUE THREAD

**Issue by berrySkies** [gotthardp/lorawan-server#666]
Firstly thank you for your product.

Trying to create a new connector to an existing MQQT server in the web admin interface. "mqqt" is not accepted in the URI field (i.e. trying to enter mqqt://host:1883). Message received is "invalid form" and the URI field is highlighted in red. 

I'm using docker image:latest.

Also cannot find mailing list in google groups. Groups reports that if list exists I will need invite from owner. Is the mailing list still used?

**Comment by gotthardp** [comment]
Hello. `mqqt` is not supported. If you mean `mqtt` please send me exactly what URI is not accepted.

**Comment by berrySkies** [comment]
OMG! Sorry I can't believe did this. Been using MQTT for years.

**Comment by gotthardp** [comment]
That's OK :-)
