### ISSUE TITLE
handle_downlink bad argument passing

### ISSUE THREAD

**Issue by gollem14** [gotthardp/lorawan-server#67]
On Apr 12, 2017 you changed in lorawan_mac.erl in function handle_downlink:
TxQ = lorawan_mac_region:rx2_rf(Link#link.region, Link#link.last_rxq), 
to
TxQ = lorawan_mac_region:rx2_rf(Link, Link#link.last_rxq),

but function rx2_rf (in lorawan_mac_region.erl) still need Region, not Link as first parameter.

**Comment by gotthardp** [comment]
Thanks for such a great bug report. You are right. I just pushed a bugfix.

**Comment by gollem14** [comment]
From me, thanks a lot for your work. Your lorawan server is excellent job.

**Comment by gotthardp** [comment]
Thanks. :)
