### ISSUE TITLE
Disable payload encryption/decryption / empty AppSKey

### ISSUE THREAD

**Issue by Nemrtvej** [gotthardp/lorawan-server#670]
I am kind of new to LoRa / LoRaWAN and have a silly question.

Is there any way how to configure Device in lorawan-server in a way that the AppSKey is not defined and there will be no attempt to decrypt the actual payload by lorawan-server?

I'd like to setup a LoRaWAN network for 3rd party customers and be able to guarantee the privacy of their data.

I know there are two ways how to register devices: OTAA and ABP. In order to register Device via OTAA, the server needs to know the AppKey and therefore can calculate the AppSKey.

However while using the ABP (albeit impractical) it should be possible to use only NwkSKey to obtain the message and pass the payload to client server where he can decrypt the data payload via AppSKey.

Is this workflow even possible?

Is it possible to achieve it in lorawan-server? 

Thank you.

**Comment by gotthardp** [comment]
LoRaWAN 1.1 allows such flows, but my server is designed to be compact. The target user group are **not** network operators (there are other solutions for them). My target group are service providers that operate **both** the server as well as the applications, so your use-case is not addressed.
