### ISSUE TITLE
Login with non-default user - http 403 error 

### ISSUE THREAD

**Issue by Kralg** [gotthardp/lorawan-server#671]
Hello,

With v.0.6.7 I create another user and if I try to connect with it from another browser, I get error 403. Is it necessary to make some additional configurations to make it working? Server has: one device, a gateway, several frames from the end device.

![user_Ad1](https://user-images.githubusercontent.com/26962388/64556020-411bf200-d347-11e9-8f0f-dc667aab7e38.png)

**Comment by altishchenko** [comment]
Don't see any login attempts in your events log. Can you try clearing the browser cache?

**Comment by gotthardp** [comment]
What *scopes* do the users have?

**Comment by Kralg** [comment]
If I use admin scope then I get a window below with an error message. 

![Capture123](https://user-images.githubusercontent.com/26962388/64608214-d6b09380-d3d2-11e9-99a3-262fdeb53d16.PNG)

![Untitled12](https://user-images.githubusercontent.com/26962388/64608079-8afdea00-d3d2-11e9-8bb2-6c39d7ab7623.png)

**Comment by gotthardp** [comment]
That's quite understandable. The user has a permission to view the web-admin pages, but has no permission to view any data. You should add more scopes depending on what data shall be accessible. Note also that the dashboard (visible bu default after login) displays an overview of everything, so the display the dashboard you need read access to all data types.

**Comment by altishchenko** [comment]
Try adding server:read, network:read and device:read to the user and see if it will help. web-admin is just web interface access, but REST requests behind are :read controlled.

**Comment by Kralg** [comment]
Thank you! Now it is clear and works. 
Just some funny error persists with 403 when user does not have a scope to read. Maybe it is usual, but some kind of notification - limited scope/rights, would be handy. 
I am wondering in case of older versions of server (without scopes for users) is it possible to disable web-admin view without disabling REST?

**Comment by gotthardp** [comment]
Older versions cannot disable web-admin only. It's either all or nothing.
