### ISSUE TITLE
HTTP downlink WebSocket fails with 500

### ISSUE THREAD

**Issue by pboettch** [gotthardp/lorawan-server#672]
Using 0.6.7 I created a WebSocket connection to test download packets:

![image](https://user-images.githubusercontent.com/442684/64616330-aa017980-d3dc-11e9-869a-128f911a648f.png)

I made my device join with and after getting its device address I ran (copied from the connection-documentation):

`curl -v -uadmin:admin -H "Content-Type: application/json" -X POST http://meli-1:8080/in/578F4A58  -d '{"data":"ABCDEF"}'`

The server returns:

```
*   Trying 192.168.1.60:8080...
* TCP_NODELAY set
* Connected to meli-1 (192.168.1.60) port 8080 (#0)
* Server auth using Basic with user 'admin'
> POST /in/578F4A58 HTTP/1.1
> Host: meli-1:8080
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.65.3
> Accept: */*
> Content-Type: application/json
> Content-Length: 17
> 
* upload completely sent off: 17 out of 17 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< content-length: 0
< 
* Connection #0 to host meli-1 left intact
```

In the debug.log I can read:
```
2019-09-10 15:00:32.054 [error] <0.597.0>@lorawan_application_backend:handle_downlink:196 CRASH REPORT Process <0.597.0> with 0 neighbours crashed with reason: no match of right hand value [] in lorawan_application_backend:handle_downlink/2 line 196
2019-09-10 15:00:32.077 [error] <0.597.0>@lorawan_application_backend:handle_downlink:196 Cowboy stream 1 with ranch listener http and connection process <0.596.0> had its request process exit with reason: no match of right hand value [] in lorawan_application_backend:handle_downlink/2 line 196
```

And it generates this crash report:

```
2019-09-10 15:15:40 =CRASH REPORT====
  crasher:
    initial call: cowboy_stream_h:request_process/3
    pid: <0.790.0>
    registered_name: []
    exception error: {{badmatch,[]},[{lorawan_application_backend,handle_downlink,2,[{file,"/home/user/devel/stimio/meli-yocto/build/tmp/work/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/lorawan-server/0.6.7-r0/git/src/lorawan_application_backend.erl"},{line,196}]},{lorawan_connector_http_in,handle_downlink,2,[{file,"/home/user/devel/stimio/meli-yocto/build/tmp/work/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/lorawan-server/0.6.7-r0/git/src/lorawan_connector_http_in.erl"},{line,43}]},{cowboy_rest,call,3,[{file,"/home/user/devel/stimio/meli-yocto/build/tmp/work/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/lorawan-server/0.6.7-r0/git/_build/default/lib/cowboy/src/cowboy_rest.erl"},{line,1187}]},{cowboy_rest,process_content_type,3,[{file,"/home/user/devel/stimio/meli-yocto/build/tmp/work/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/lorawan-server/0.6.7-r0/git/_build/default/lib/cowboy/src/cowboy_rest.erl"},{line,990}]},{cowboy_rest,upgrade,4,[{file,"/home/user/devel/stimio/meli-yocto/build/tmp/work/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/lorawan-server/0.6.7-r0/git/_build/default/lib/cowboy/src/cowboy_rest.erl"},{line,264}]},{cowboy_stream_h,execute,3,[{file,"/home/user/devel/stimio/meli-yocto/build/tmp/work/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/lorawan-server/0.6.7-r0/git/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},{line,293}]},{cowboy_stream_h,request_process,3,[{file,"/home/user/devel/stimio/meli-yocto/build/tmp/work/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/lorawan-server/0.6.7-r0/git/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},{line,271}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.789.0>,<0.323.0>,<0.322.0>,ranch_sup,<0.273.0>]
    message_queue_len: 0
    messages: []
    links: [<0.789.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 1922
  neighbours:
2019-09-10 15:15:40 =ERROR REPORT====
Ranch listener http, connection process <0.789.0>, stream 1 had its request process <0.790.0> exit with reason {badmatch,[]} and stacktrace [{lorawan_application_backend,handle_downlink,2,[{file,"/home/user/devel/stimio/meli-yocto/build/tmp/work/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/lorawan-server/0.6.7-r0/git/src/lorawan_application_backend.erl"},{line,196}]},{lorawan_connector_http_in,handle_downlink,2,[{file,"/home/user/devel/stimio/meli-yocto/build/tmp/work/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/lorawan-server/0.6.7-r0/git/src/lorawan_connector_http_in.erl"},{line,43}]},{cowboy_rest,call,3,[{file,"/home/user/devel/stimio/meli-yocto/build/tmp/work/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/lorawan-server/0.6.7-r0/git/_build/default/lib/cowboy/src/cowboy_rest.erl"},{line,1187}]},{cowboy_rest,process_content_type,3,[{file,"/home/user/devel/stimio/meli-yocto/build/tmp/work/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/lorawan-server/0.6.7-r0/git/_build/default/lib/cowboy/src/cowboy_rest.erl"},{line,990}]},{cowboy_rest,upgrade,4,[{file,"/home/user/devel/stimio/meli-yocto/build/tmp/work/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/lorawan-server/0.6.7-r0/git/_build/default/lib/cowboy/src/cowboy_rest.erl"},{line,264}]},{cowboy_stream_h,execute,3,[{file,"/home/user/devel/stimio/meli-yocto/build/tmp/work/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/lorawan-server/0.6.7-r0/git/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},{line,293}]},{cowboy_stream_h,request_process,3,[{file,"/home/user/devel/stimio/meli-yocto/build/tmp/work/cortexa7hf-neon-vfpv4-phytec-linux-gnueabi/lorawan-server/0.6.7-r0/git/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},{line,271}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]
```

What is my mistake?

If I send invalid JSON I get `400 Bad Request`.

**Comment by gotthardp** [comment]
The **Application** field in your connector is empty. It's must point to some application.

**Comment by pboettch** [comment]
I see... it's not yet clear to me what I have to do to create a handler for my test-case.

**Comment by pboettch** [comment]
It's not clear to me what I need to put in **Build Downlinl** if I just what to send the data I receive via my POST-request as bytes to the device.

**Comment by pboettch** [comment]
I created the following application: 

![image](https://user-images.githubusercontent.com/442684/64625451-82b2a880-d3ec-11e9-9f5a-c853a2484738.png)

And when doing curl with the right devaddr `curl -v -uadmin:admin -H "Content-Type: application/json" -X POST http://meli-1:8080/in/560F4CA4 -d '{"data":"deadbeef"}'` it returns:

```
* upload completely sent off: 19 out of 19 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< content-type: text/html
< date: Tue, 10 Sep 2019 14:59:34 GMT
< server: Cowboy
< 
* Connection #0 to host meli-1 left intact
```
No error and no messages in the debug.log . But no frames seem to be sent - at least my device does not receive anything.

**Comment by altishchenko** [comment]
First, you should specify 'port' attribute in your POST ("port":1). Use the number your device uses to send uplinks. Second, if it is a Class A device, you should wait for an uplink to happen, then the server will be able to send data back to it. If it is a Class C device, you should also specify "time":"immediately" in your POSTed JSON.

**Comment by pboettch** [comment]
I added the port-field to my JSON. I can see the packets I send with curl listed being queued when looking at the activated device page:

![image](https://user-images.githubusercontent.com/442684/64650271-12714a80-d41f-11e9-8c7e-02c6c0b229d5.png)

My device is sending uplinks regularly but the downlink-packets are not sent.

**Comment by gotthardp** [comment]
You mean the downlinks are not removed from the queue, they never appear in gateway's txpk or just that the downlink is never *received*?

**Comment by pboettch** [comment]
Never removed from the queue and never appear in the packet-forwarder's log.

**Comment by gotthardp** [comment]
What is on your Frames page, please? What frames related to this device you see?

**Comment by pboettch** [comment]
I forced the download to go out by adding `"time":"immediately"` to my JSON message.

![image](https://user-images.githubusercontent.com/442684/64650904-911ab780-d420-11e9-90f1-5565b4089013.png)

Then I can the txpkt in the packet-forwarder. And there is crying about the frequency. Which is set to 400 MHz. Out of range of course. I will check with my colleagues what's going on.

**Comment by gotthardp** [comment]
Your application must not be semtech-mote. That one does not support custom downlinks. You need to have a custom handler and link it to the devices and the connector.

Also, immediate transmission is class C. Have a look at your netwok config and the Regions.md with recommended settings.

**Comment by pboettch** [comment]
Once I changed the application in the device packets are going out and the packet-forwarder is using the right frequency. (I still don't see the incoming packet in my device, but this is probably a bug).

Thanks for helping out. It's quite hard to get the elements together.

**Comment by pboettch** [comment]
Never mind, the device is receiving the message. :1st_place_medal: Thanks again.
