### ISSUE TITLE
http_custom_web option 

### ISSUE THREAD

**Issue by Kralg** [gotthardp/lorawan-server#673]
Hello,

Can you elaborate on this http_custom_web option? Can you describe how to use it? Is there any template like the one for ws? 
I saw this in sys.conf, however it would be good to get some more info:
{http_custom_web, [
    % enable this to serve additional web-pages
    %    {"/www", file, <<"/var/www/html/index.html">>, [{<<"anonymous">>, '*'}]},
    %    {"/www/[...]", dir, <<"/var/www/html">>, [{<<"anonymous">>, '*'}]}
    ]},

**Comment by gotthardp** [comment]
That is useful when you want to use the lorawan-server as a (pretty simple) http server, serving some custom web pages, static data or such stuff. Its static files or a directory.

It it of any use for you? Shall it write some docs for it?

**Comment by Kralg** [comment]
I have a question with the configurations:
 {http_custom_web, [
    % enable this to serve additional web-pages
        {"/", file, <<"/var/www/html/index.html">>, [{<<"anonymous">>, '*'}]},
        {"/[...]", dir, <<"/var/www/html">>, [{<<"anonymous">>, '*'}]}
    ]},
If I open ip:8080 then admin dashboard opens, but if I type ip:8080/index.html, then custom index.html opens. Is there a way to make index to load first and if typed ip:8080/admin, then admin? Or am I missing something?
Th index file is very simple: 
<!doctype html>
<html>
  <head>
    <title>This is the title!</title>
  </head>
  <body>
    <p>Anything <strong>body</strong> tag $
  </body>
</html>


I am using 0.6.7 server version.

**Comment by gotthardp** [comment]
Hello. It shall work as you expect. The behaviour you are observing may be due to a browser cache.
