### ISSUE TITLE
Error too early

### ISSUE THREAD

**Issue by dynawink** [gotthardp/lorawan-server#675]
In the dashboard of our LoRaWAN I see a red bubble appearing with the text 'too_early'. What is the meaning of the message? I could not find the text 'too_early' in the lorawan-server code. From where does it originate?

Cf. https://gist.github.com/dynawink/94d74ba521cb96a9971e120a0a695f99

**Comment by gotthardp** [comment]
Hello. It comes from the packet_forwarder (the gateway). It might be due to https://github.com/Lora-net/packet_forwarder/issues/47, so it could effectively mean "too late".

**Comment by dynawink** [comment]
Thanks for the link. It would be helpful to add this information to https://github.com/gotthardp/lorawan-server/blob/master/doc/Administration.md . The comments in https://github.com/Lora-net/packet_forwarder/blob/master/lora_pkt_fwd/src/jitqueue.c#L224 could serve as template.

**Comment by JohanVikman** [comment]
I made a PR https://github.com/gotthardp/lorawan-server/pull/677

@dynawink does this look like something you would have wanted?

**Comment by gotthardp** [comment]
Fixed by #677.
