### ISSUE TITLE
Many many "ack lost" I have set push timeout in gateway to 500ms.. 

### ISSUE THREAD

**Issue by hjojohan** [gotthardp/lorawan-server#680]
Please tell me what could be wrong and how to improve my system.  I am using multitech AEP indoor GW with push timeout set to 500ms in the config-file. The gateway is placed in the same room as 200 lorawan asset tags, range is no more than 50 meter.  

![image](https://user-images.githubusercontent.com/6337514/66419969-5139f680-ea05-11e9-8dd5-23957de9c943.png)

**Comment by cocoaway** [comment]
Hi,
gateway (as I can see in your picture) is spotting  a red "!"
Have many gateways are connected to NS ?

**Comment by jot4p** [comment]
This ack_lost maybe it's packages that aren't yours. Or you don't have the devices registered

**Comment by jot4p** [comment]
I have ignored "TRUE" but I receive the ack_lost packets 

![image](https://user-images.githubusercontent.com/15892047/68114489-06b97600-feee-11e9-8dc5-005cdd154287.png)
