### ISSUE TITLE
About tx_freq_min/tx_freq_max

### ISSUE THREAD

**Issue by YonglunHo** [gotthardp/lorawan-server#685]
global_conf.json

![1573530777(1)](https://user-images.githubusercontent.com/52147048/68640875-02bbd280-0544-11ea-8d68-0b77c2456024.png)
ERROR
![1573531056(1)](https://user-images.githubusercontent.com/52147048/68640889-09e2e080-0544-11ea-96de-d5da8c563059.png)

**Comment by gotthardp** [comment]
??

**Comment by YonglunHo** [comment]
tx_freq_min:510000000,tx_freq_max:0
How should I set it?
![68640889-09e2e080-0544-11ea-96de-d5da8c563059](https://user-images.githubusercontent.com/52147048/68721269-d019e480-05ec-11ea-9f49-ed3fbe630b29.png)

**Comment by gotthardp** [comment]
In my server, the frequencies are represented by channels. If you want to constrain the frequencies, set a limited set of channels:
https://github.com/gotthardp/lorawan-server/blob/master/doc/Infrastructure.md#channels
https://github.com/gotthardp/lorawan-server/blob/master/doc/Devices.md#adaptive-data-rate-adr

**Comment by YonglunHo** [comment]
Use TTN is OK.But lorawan-server Not working
TTN
![1573780404(1)](https://user-images.githubusercontent.com/52147048/68909094-338c4980-0788-11ea-8240-cd00bc361566.png)
lorawan-server
![1573780473(1)](https://user-images.githubusercontent.com/52147048/68909160-60d8f780-0788-11ea-8a67-280186cc6e68.png)

**Comment by gotthardp** [comment]
I see. Its due to a misconfiguration.

**Comment by YonglunHo** [comment]
Thank you for replying,
 I don't know my server is set up wrong.
![image](https://user-images.githubusercontent.com/52147048/68925004-0312d280-07bd-11ea-9dd6-2641843f6510.png)
![image](https://user-images.githubusercontent.com/52147048/68925008-05752c80-07bd-11ea-9f36-40a8a5e8bd5f.png)
![image](https://user-images.githubusercontent.com/52147048/68925012-0ad27700-07bd-11ea-8bb8-4c77ed73a5e7.png)
![微信图片_20191115153227](https://user-images.githubusercontent.com/52147048/68925051-26d61880-07bd-11ea-977b-d249f7749aae.png)
![微信图片_201911151532271](https://user-images.githubusercontent.com/52147048/68925052-26d61880-07bd-11ea-9a0d-7cf755a86a6c.png)
![微信图片_201911151532272](https://user-images.githubusercontent.com/52147048/68925053-26d61880-07bd-11ea-88e8-c1c5e4972040.png)
![微信图片_201911151532273](https://user-images.githubusercontent.com/52147048/68925054-276eaf00-07bd-11ea-9d06-a8a5dd153196.png)
![微信图片_201911151532274](https://user-images.githubusercontent.com/52147048/68925055-276eaf00-07bd-11ea-9b22-56b3b68cb557.png)
![微信图片_201911151532275](https://user-images.githubusercontent.com/52147048/68925057-28074580-07bd-11ea-95e3-c78ed387e520.png)
![微信图片_201911151532276](https://user-images.githubusercontent.com/52147048/68925058-28074580-07bd-11ea-9ca1-ada7c5a7c2a5.png)

**Comment by YonglunHo** [comment]
I changed my Settings, but the system prompted not_semtech_mote
![image](https://user-images.githubusercontent.com/52147048/68926242-06f42400-07c0-11ea-8ed4-4dba83857898.png)

**Comment by YonglunHo** [comment]
I set Handlers. Sometimes it works. But more often than not, it's CRC_FAIL: 100.00%
Is it because of network --> channles? I set Initial Channels 0-95
##### 2019-11-18 02:56:50 GMT #####
### [UPSTREAM] ###
# RF packets received by concentrator: 15
# CRC_OK: 0.00%, CRC_FAIL: 100.00%, NO_CRC: 0.00%
# RF packets forwarded: 0 (0 bytes)
# PUSH_DATA datagrams sent: 1 (114 bytes)
# PUSH_DATA acknowledged: 100.00%
### [DOWNSTREAM] ###
# PULL_DATA sent: 3 (100.00% acknowledged)
# PULL_RESP(onse) datagrams received: 0 (0 bytes)
# RF packets sent to concentrator: 0 (0 bytes)
# TX errors: 0
# TX rejected (collision packet): 0.00% (req:2, rej:0)
# TX rejected (collision beacon): 0.00% (req:2, rej:0)
# TX rejected (too late): 0.00% (req:2, rej:0)
# TX rejected (too early): 0.00% (req:2, rej:0)
# BEACON queued: 0
# BEACON sent so far: 0
# BEACON rejected: 0
### [JIT] ###
# SX1301 time (PPS): 602444852
src/jitqueue.c:448:jit_print_queue(): INFO: [jit] queue is empty
### [GPS] ###
# GPS sync is disabled
##### END #####
