### ISSUE TITLE
Clarafication on Multicast comfiguration

### ISSUE THREAD

**Issue by hamersin** [gotthardp/lorawan-server#688]
I am attempting to configure the Lorawan-server to multi-cast out to a number of end nodes that I have configured to listen to a second address (0x11111111) 

I am trying to follow your instructions, but I am missing something in the configuration. (Unfortunately the documentation on configuring the Infrastructure references a document that appears to no longer exists. (https://github.com/gotthardp/lorawan-server/blob/master/doc/Communication.md))

What I have done is to configure the Multicast ID, with the same Profile, NwkSKey and AppSKey that the end nodes I am trying to reach are using. Basic testing shows the Network Server claiming that it is sending the message, but I never receive anything from my end nodes.

Does the Communication,md go into more details of how the LoraWAN-server is handling multi-cast message request?

Thanks

**Comment by gotthardp** [comment]
Hello. Sorry for the dead link. I already fixed that-- the text went to the Introduction.md, but I am not sure if it will help you much. It's just a basic intro.

I guess you know the multicast is using different NwkSKey and AppSKey and the downlink must be Class C, i.e. with the `immediately` flag, right?
Another catch is the FCnt and the "bug" in the LoRaWAN standard reported in the Issue https://github.com/gotthardp/lorawan-server/issues/509. I am not sure what else could be a problem.
