### ISSUE TITLE
ADR logic

### ISSUE THREAD

**Issue by nekta-support** [gotthardp/lorawan-server#707]
Describe the logic of ADR or provide a link to the documentation.
What parameters does the server focus on when it changes speed and power?
At what values of these parameters does the speed and power change?

**Comment by altishchenko** [comment]
The algorithm is based pretty closely on the original recommendation by
Semtech and takes into account SNR (averaged) and RSSI indications for a
particular node. Roughly, AvgSNR is used to drive the datarate per MaxSNR
specified for each DR, AvgRSSI is used to drive TxPower of the device.
As for the SNR - there is a standard table of the 'worst sustainable'
levels for every DR, like -20dB for DR0.
For RSSI, the server tries to increase the TxPower if AvgRSSI value falls
below -102dbm and lowers it back if AvgRSSI becomes better than -96.

Alexander Tishchenko
M: +7 (916) 704-61-57
E: atishch@gmail.com



чт, 27 февр. 2020 г. в 15:44, nekta-support <notifications@github.com>:
