### ISSUE TITLE
tx_freq

### ISSUE THREAD

**Issue by swapmicro** [gotthardp/lorawan-server#750]
Hello There,
Recently I am trying to implement with sx1262 with US915 with the frequency of 914300000 with ABP mode at that time on the server I facing a tx_freq issue in the event log how can I solve this issue please guide me to solve this issue.
here I attaching my event window
![log1](https://user-images.githubusercontent.com/15924872/94816996-2b79de80-041a-11eb-8d30-9c3d56494008.png)

**Comment by Apaisal** [comment]
Please see network setting in infrastructure document and match them with your gateway frequencies setting at

https://github.com/gotthardp/lorawan-server/blob/master/doc/Infrastructure.md

Yours sincerely 
Anol P. <anol.p@emone.co.th>

**Comment by swapmicro** [comment]
Hello there,
Thanks for the replay but I am facing the same error. 
Here I attached my Network configuration setting please guide me if I am wrong.
Thanks 
Swapnil 
![log1](https://user-images.githubusercontent.com/15924872/94983829-faa5c080-0563-11eb-89ac-5b1dc94055ea.png)
![log2](https://user-images.githubusercontent.com/15924872/94983830-fbd6ed80-0563-11eb-92ef-c58caca0fe81.png)
![log3](https://user-images.githubusercontent.com/15924872/94983831-fbd6ed80-0563-11eb-9e7a-b2ea2c006c2b.png)
![log4](https://user-images.githubusercontent.com/15924872/94983832-fc6f8400-0563-11eb-8c99-653fe71e20a9.png)

**Comment by altishchenko** [comment]
Hello, I am not sure how this works for US bands, but for EU you *must* list all the extra channels by hand on the channels tab. Default channels shall not be listed. I know, this inconvenient, but... Consider this:
![chans](https://user-images.githubusercontent.com/19464159/95001748-9de2ee00-05d5-11eb-9c36-bc0874ab14c0.PNG)

etc. ...

**Comment by swapmicro** [comment]
Hello There,
Thanks For the replay, I got the downlink and tx_err also solve by doing the settings in the network tab. Here I am posting my settings for US Frequency.
![image](https://user-images.githubusercontent.com/15924872/95076088-f11c8400-072e-11eb-8055-d99152d31bfb.png)
![image](https://user-images.githubusercontent.com/15924872/95076111-fa0d5580-072e-11eb-8c44-d7d1fcc283ec.png)
![Uploading image.png…]()
