### ISSUE TITLE
Down link Data queue issue

### ISSUE THREAD

**Issue by swapmicro** [gotthardp/lorawan-server#751]
Hello There,
When I trying to send multiple data frem to my single node at that time my node accepts the single frame. Other Frames are sending to the node as an empty frame here I am sending my node logs as well as server node queue
![image](https://user-images.githubusercontent.com/15924872/95085425-d6510c00-073c-11eb-8d5c-992047580def.png)
![image](https://user-images.githubusercontent.com/15924872/95085576-09939b00-073d-11eb-961e-61e5f9488c6a.png)
Please guide me to solve this problem.

**Comment by altishchenko** [comment]
According to your screenshot, you can notice that the frames following your first received data frame are destined for port 0, which is an indication of ADR message exchange in action. Do you have ADR support switched on in your device's library? (LoRaMac-node, as I can guess). Bear in mind, ADR exchange may take considerable time. Does the **second queued frame** disappear from the server when the first one is successfully transmitted?

```
                /* Should be somewhere in your device's DEVICE_START section */
                mibReq.Type = MIB_ADR;
                mibReq.Param.AdrEnable = LORAWAN_ADR_ON;
                LoRaMacMibSetRequestConfirm(&mibReq);
```

**Comment by swapmicro** [comment]
Hello There, 
Thanks for the replay.
Yes, After the receiving  1 frame. In semtec stack, code uses the **LORA_TxNeeded** function to get other pending frames.
![image](https://user-images.githubusercontent.com/15924872/95169124-01d10680-07d0-11eb-8151-1096e623d706.png)

**Comment by swapmicro** [comment]
Hello There,
Yes In my device library ADR support is enabled.
If I have more then 1 frame is in the queue at that time my stack will use the  **LORA_TxNeeded** function to provide uplink as soon as possible at that time pending frames are sent from the server but I didn't get the data.
![image](https://user-images.githubusercontent.com/15924872/95171080-034ffe00-07d3-11eb-9961-bf2b210ef7aa.png)

**Comment by altishchenko** [comment]
@swapmicro Hello, sorry for the delay, I was unavailable. Does this call to TxNeeded() really happen? I am not sure at this moment, that this server will set this indication in the downlink even if it has some data pending. Also, this call may happen, if the library stack **has some ADR data** to be sent back to the server asap. Did you try it with the latest version of the server, top of master branch, just to confirm? You can get the docker image from docker hub to save the hassle on compile.

**Comment by swapmicro** [comment]
Hello there,
Thanks for the reply.
Yes, when more than 1 frames are available in the activated (nodes) tab at that time **TxNeeded()**  called by the stack.
yes, I am using the latest copy of the server. 
Thanks 
Swapnil

**Comment by altishchenko** [comment]
Hmm, ran out of ideas really... Can you possibly provide a fresh server debug.log with multiple downlink frames being queued/transmitted? Also, can you share an example of your downlink JSON?

**Comment by swapmicro** [comment]
Hello There,
Thanks for the reply. Here  I am sharing my server fresh screen short.
![screencapture-192-168-1-205-9090-admin-2020-10-14-11_25_26](https://user-images.githubusercontent.com/15924872/95949491-70d1df00-0e10-11eb-8f1d-bb705057e8a2.png)
![screencapture-192-168-1-205-9090-admin-2020-10-14-11_26_31](https://user-images.githubusercontent.com/15924872/95949502-74656600-0e10-11eb-9205-aa094b2c5c81.png)
![screencapture-192-168-1-205-9090-admin-2020-10-14-11_27_24](https://user-images.githubusercontent.com/15924872/95949513-792a1a00-0e10-11eb-8cd5-c457da1527a7.png)
![image](https://user-images.githubusercontent.com/15924872/95949525-7e876480-0e10-11eb-8426-12051938406c.png)
Can you please guide me where can I found server debug,log file in rspbian.
my downlink json is 
{"devaddr":"0190A703","data":"4142434445464748494a4b4c4d4e4f505152535455565758595a313233343536373839306162636465666768696a6b6c6d6e6f707172737475767778797a"}
Thanks 
swapnil

**Comment by altishchenko** [comment]
@swapmicro You can find your debug.log in /var/log/lorawan-server/.
For the downlink to reach the target device properly you should specify a `port` field in your JSON. Like this: `{ "port": 2, ... }`

**Comment by swapmicro** [comment]
hello there,
Thanks for the reply.
adding  **"port":2** in my json my problem us solve.
Thanks 
Swapnil
