### ISSUE TITLE
AWS IOT CORE integration

### ISSUE THREAD

**Issue by swapmicro** [gotthardp/lorawan-server#752]
hello there,
I have to send my application data to the AWS IoT core. please guide me on how can I  send my data to that.
Thanks 
swapnil

**Comment by altishchenko** [comment]
Did you have a look into the Integration.md document?

**Comment by swapmicro** [comment]
Hello,
Thanks for your reply, I follow the steps defined in the Integration.md document. 
but didn't get the output on AWS IOT Core
Thanks 
swapnil

**Comment by altishchenko** [comment]
Sorry, can't help you here - never used it myself, just know that there was something on AWS in the docs.

**Comment by swapmicro** [comment]
Hello there,
Can you please create a short video for AWS IoT Core integration for learning purposes?
Thanks 
Swapnil
