### ISSUE TITLE
Problems with downlinks

### ISSUE THREAD

**Issue by jot4p** [gotthardp/lorawan-server#769]
Hi, 

I don't see any downlink in my dashboard interface:

![image](https://user-images.githubusercontent.com/15892047/114090752-bd721080-98af-11eb-8f1f-ddc43c8fff2f.png)

I have 1 multitech with packet forawarder:

![image](https://user-images.githubusercontent.com/15892047/114090846-dd093900-98af-11eb-8fb6-5bd660d2c26b.png)

What is the solution? Any error on my lowaran server configuration ?

**Comment by jot4p** [comment]
Hi, 

Solved, update to 0.6.7

**Comment by altishchenko** [comment]
@jot4p Can you, please, close the issue? Looks like Petr is out on vacations or something.
