### ISSUE TITLE
Question: Battery as % in uplink

### ISSUE THREAD

**Issue by glennvdv** [gotthardp/lorawan-server#773]
I'm trying to send the battery as % through the parse uplink function. But i can't seem to get it working, how do i access battery in the erlang function? My current function is:
fun(Fields,<<Header,Status,Casing_Status,Unused,DQ_Enabled,Counting:16,Temp:16>>)->
Fields#{status => Status, casing_status => Casing_Status,counting=>Counting,temperature=>Temp}
end.
I would like to send batteryLevel => battery / 255 *100

**Comment by altishchenko** [comment]
For this, your Handler's Uplink fields should contain the word 'battery', then you can access the LoRa value from inside your function with:
```
LoRaBattery = maps:get(battery, Fields, 0),
```

Bear in mind, that dividing by 255 is not really correct. According to the standard, 0 - connected to external power supply, 255 - unable to measure. That leaves you with [1-254] = [0-100]%

**Comment by glennvdv** [comment]
thx it's working. And thx for mentioning the standard, i did not know about the 0 and 255
