### ISSUE TITLE
server not starting: init terminating in do_boot

### ISSUE THREAD

**Issue by Graandr** [gotthardp/lorawan-server#776]
after following the installation the service doesn't start with following log:
{"init terminating in do_boot",{undef,[{lorawan_app,start,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

lorawan-server: 0.6.7
os: centos

attached the dumb file
[erl_crash.zip](https://github.com/gotthardp/lorawan-server/files/6583588/erl_crash.zip)

as I'm new to the project, I hope the needed information is given and some may help me.

**Comment by altishchenko** [comment]
1. What is the version of Erlang/OTP you are using?
2. How do you start this server?
3. Have you any debug/error/info log from the server startup? The crash dump doesn't help a lot, unfortunately..

**Comment by Graandr** [comment]
Hi,
ad1) Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]
ad2) systemctl start lorawan-server (same resualt by starting directly lorawan-server)
ad3) only in /var/log/messages the following lines:
systemd: Started LoRaWAN Server.
lorawan-server: {"init terminating in do_boot",{undef,[{lorawan_app,start,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
lorawan-server: Crash dump was written to: erl_crash.dump
lorawan-server: init terminating in do_boot ()
systemd: lorawan-server.service: main process exited, code=exited, status=1/FAILURE
systemd: Unit lorawan-server.service entered failed state.
systemd: lorawan-server.service failed.

hope that helps

**Comment by altishchenko** [comment]
Minimal Erlang OTP version required is Erlang/OTP **21**, and by the looks of the output you are running ancient R16B. Consider running the server in a docker container, if there is no appropriate Erlang version for your OS.

**Comment by Graandr** [comment]
thanks a lot for the hit. I've to apologize that I've fully overseen the version. Not the server is running. Thx a lot

**Comment by altishchenko** [comment]
@Graandr Great! Can you please close this issue?
