### ISSUE TITLE
how to convert hex data to ascii

### ISSUE THREAD

**Issue by YousseMes** [gotthardp/lorawan-server#78]
please can you explain me how to convert data to ascii
![capture](https://cloud.githubusercontent.com/assets/28385566/25695035/cc80b884-30b1-11e7-9e77-215d0cdab7cf.JPG)

**Comment by gotthardp** [comment]
For example, you can use a tool like http://www.unit-conversion.info/texttools/hexadecimal/

**Comment by YousseMes** [comment]
but if i want to see data in application as ascii format ?

**Comment by gotthardp** [comment]
You cannot. The data may not be 7-bit ASCII.

**Comment by kazi93** [comment]
@YousseMes Hi! Have you managed to read data on a visualization tool e.g freeboard,thingspeak?

**Comment by YousseMes** [comment]
No I didn't can you explain how please ?

**Comment by gotthardp** [comment]
The list of received frames is not intended to display the payload. I assume that the data decoded by the server will be sent to some backend system and the visualization will be done there,

**Comment by gotthardp** [comment]
I made an update for the coming 0.4.0 release, which should meet your needs: If you put your mouse cursor above the *Data* field, it will display printable ASCII characters in that string.
