### ISSUE TITLE
how can i change default admin password of lorawan-server 

### ISSUE THREAD

**Issue by pragnesh036** [gotthardp/lorawan-server#786]
I change my admin password for security purposes,
my default id password is admin  I change the password on "/usr/lib/lorawan-server/releases/0.6.7/sys.confi" after reboot the server password is do not updated it works on the old password
please guide me

**Comment by altishchenko** [comment]
The server admin password in stored in the database on the first run. To change the password after the server has started, you should edit the user admin under the Server -> Users menu on the left of your screen.
