### ISSUE TITLE
OTAA join procedure

### ISSUE THREAD

**Issue by TheStudent227** [gotthardp/lorawan-server#802]
Hello, I would like to ask for help with lorawan network server. I am doing the project on CoDeSys for controller in ST, which should emulate the network server. The end device is premade, but I have troubles finding the network server code which responsible for OTAA join procedure, in this project, which will handle the request from LoRa sensor. Could someone point on this code in this project ? Or have some example, ideally in C, ST ?

Apologizing for possible off-topic

**Comment by altishchenko** [comment]
If you need to figure out the logic, you can start with src/lorawan_mac.erl file, line 33. The word 'Join' will guide you through the process. There is another network server, called chirpstack, which is also available on GitHub.

The LoRaWAN standard is very straightforward, you can get the specification at [Lora-Alliance](https://lora-alliance.org/resource_hub/lorawan-104-specification-package/). There is no black magic in the protocol and it is very simple to code.

**Comment by TheStudent227** [comment]
> If you need to figure out the logic, you can start with src/lorawan_mac.erl file, line 33. The word 'Join' will guide you through the process. There is another network server, called chirpstack, which is also available on GitHub.
> 
> The LoRaWAN standard is very straightforward, you can get the specification at [Lora-Alliance](https://lora-alliance.org/resource_hub/lorawan-104-specification-package/). There is no black magic in the protocol and it is very simple to code.

Thank you for help :)

**Comment by altishchenko** [comment]
Hi! Can you close the issue, please?
