### ISSUE TITLE
How should I set the confirmed downlink message?

### ISSUE THREAD

**Issue by Ryoyo123** [gotthardp/lorawan-server#803]
Hi
 I want to send confirmed data via downlink to make sure ACK is returned. 

 The End node has installed　STMicro AT-Slave program . The gateway is in packet forwarder mode. 

 The uplink data path is end node-> packet forwarder GW-> LNS (gotthardo lorawan-server)-> MQTT broker-> Node-RED. 

>  Is there an API that sends confirmed data from LNS to end node by downlink? 
>  Could you advise me how to set it?

**Comment by altishchenko** [comment]
There is a special section in [Handlers](https://github.com/gotthardp/lorawan-server/blob/master/doc/Handlers.md) concerning downlinks, confirmed downlinks, confirmed downlinks with receipt.
Read the docs first, please!

**Comment by Ryoyo123** [comment]
Hi,
Thank you for your advice.

I read "Backend Handlers". 
Should I set "D / L Expires" to "Never" to set the downlink packet to confirmed data?

Or, how should I set "confirmed": true in "Build Downlink"?

**Comment by altishchenko** [comment]
Hi! Did this solve your problem? Can you close the issue, please?
