### ISSUE TITLE
Gateway connected but error on uplink

### ISSUE THREAD

**Issue by horvatmiha** [gotthardp/lorawan-server#804]
Hi,
I have an issue sending uplink from device. I am using OTAA. Gateway is Dragino LPS8. It is connected successfully. Network settings are the same as in Default Regional Configuration.

This is error in error.log:
`2021-10-27 21:14:11.665 [error] <0.126.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[<0.890.0>,{cast,{frame,{<<168,64,65,30,176,20,65,80>>,{rxq,868.3,<<"SF12BW125">>,<<"4/5">>,{{2021,10,27},{19,14,12.0924}},undefined,842401132,-13,9.0},undefined},<<0,50,70,82,65,68,178,24,0,15,25,2,0,0,178,24,0,204,22,9,249,35,111>>}},{idle,undefined},error,{badmatch,{aborted,{undef,[{crypto,block_encrypt,[aes_ecb,<<222,84,115,255,111,191,77,69,157,168,131,198,213,24,97,164>>,<<0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0>>],[]},{aes_cmac,generate_subkeys,1,[{file,"/home/travis/b..."},...]},...]}}},...]},...}}`

Any help would be great.
Thanks in advance.

**Comment by altishchenko** [comment]
Yes, this one is simpler.
You configured you device as a Semtech Mote, which is not the case, you must create your own Handler and Connector for your device.

**Comment by altishchenko** [comment]
Hi! Does the problem remain? If it works for you, can you close the issue?

**Comment by horvatmiha** [comment]
Exactly! I've created my own Handler and Connector and now communication works like a charm!
I am still having some troubles parsing data to Connectors, but this is not matter of this issue.
I am closing this issue.
@altishchenko thank you so much for your time and help!
