### ISSUE TITLE
Need instruction to install Erlang OTP 21/ 22/ 23.

### ISSUE THREAD

**Issue by bennycyau** [gotthardp/lorawan-server#805]
With Ubuntu 20.04, current instruction for "Installation" is out-of-date.  The stated Erlang packages WILL install OTP 24, which is incompatible with neither 0.6.7 nor 0.7.0 binaries (nor with the Docker versions).  Need instruction as to how to install compatible OTP 21,22,23. (I tried Erlang Solutions and got bunch of missing dependencies.)
Thanks.

**Comment by altishchenko** [comment]
Hi! Did it work for you? Can you close the issue, if there are no problems?

**Comment by bennycyau** [comment]
Thanks for the quick response.  I plan to try it and get back to this board.  Last time I tried using 0.6.7 with OTP21 docker image, but could not send MQTT to my Thingsboard server (which worked well with the normal 0.6.7 installation before the OTP 24 issue.)  Similar issue with MQTT to TB using the 0.7.0 image.  Well, I shall try again using your instruction.

**Comment by bennycyau** [comment]
Actually, I meant to ask: is the 0.7.0 Stable docker version at the same test level as the 0.6.7 yet?

**Comment by bennycyau** [comment]
OK, I tried the Docker version of 0.6.7 again.  Noticed it was built with the OTP 20 when runing "Docker Exec -it /bin/sh lorawan", then "erl".  
I recall trying this against my Thingsboard and not getting MQTT through.  Also tried previously the Docker  0.6.7 image purpose built using OTP21 (bind?), and got same result of not reaching TB via MQTT.   I do not know how to run the Docker 0.6.7 image using the downloaded Erlang Solution OTP23 image.  Is there a way to combine these two?

**Comment by altishchenko** [comment]
Ok, do you have an error or debug log of your setup not reaching TB?

**Comment by altishchenko** [comment]
And show me your mqtt config too, please.

**Comment by bennycyau** [comment]
debug.log
![16364539126102](https://user-images.githubusercontent.com/42236060/140908727-69c4c088-4641-4f66-9059-136126a7dd8d.png)
![16364541685402](https://user-images.githubusercontent.com/42236060/140909163-d3cb659a-1711-45ee-b169-313880ea207e.png)

![16364541816423](https://user-images.githubusercontent.com/42236060/140909172-5e20f804-5fe8-4169-a8c3-4bb624a2b198.png)
![16364541948514](https://user-images.githubusercontent.com/42236060/140909196-ebc62e91-c3e2-462b-b491-0876218eff48.png)
----------------------------------
No MQTT broker installed except the Thingboard built-in one at 1883.  I used the DevAddr as the Token on the corresponding TB device.  NOTE: this setup worked fine previously using plain installed OTP21/23 & 0.6.7.

Thank you.

**Comment by altishchenko** [comment]
Hi! This one is pretty much straightforward. It doesn't work, because you are trying to access your thingsboard on a *localhost*, which for the docker container is the container itself, **not** your host machine - this is standard docker, not the server to blame.
You can try connecting to your thingsboard server if you specify your host machine's IP address explicitly in the connector's MQTT URL.

**Comment by altishchenko** [comment]
The best way, in my opinion, is as we do things here in my company - we run a network of docker containers, every piece of software lives in its own container and has local IP access to other containers inside the docker network, nothing lives on the host machine altogether, but services *provided* by the containers are exposed to the host machine, so you can do things like `dbexport` or other network maintenance, like checking mongodb (in its container) with the mongo cli client from the host machine.

In your case, you should create one new docker network (of type bridge, don't use default!), create one container for the thingsboard with some name (let's say `thingsboard`) and one container for the server (let's say `lorawan`), the run them both on that new docker network. In the connector setup for the lorawan server you would then specify `mqtt://thingsboard:1883`.

**Comment by bennycyau** [comment]
Thanks for your help and advice.  The system is now working fine following your instruction, even though the OTP within 0.6.7(2 years ago) is version 20.
I need to learn more about Docker usage.
