### ISSUE TITLE
OTAA device missing data in "Received Frames" window.

### ISSUE THREAD

**Issue by kazi93** [gotthardp/lorawan-server#81]
@gotthardp Hi! I have two devices added as ABP. I have added two OTAA devices too in my single channel gw (Dragino lora hat + rpi3) which does not support downlinks. However, I am receiveing frames for the ABP devices and there is no data for the OTAA devices. :(

I followed the below procedure. 
=> Create a group "test1"
=> Add device in the devices windows (with corresponding DEV EUI, Group and AppKey). 
=> Which automatically added the device in the Nodes window and assigned a node ID.
=> Nothings appears in "FCnt Up" or	"FCnt Down" fields nor in Received Frames window. :(
=> What am I missing here.
=> Happy weekend!

Gateway terminal output for OTAA device : 
`rxpk update: {"rxpk":[{"tmst":3777168283,"chan":0,"rfch":0,"freq":868.100000,"stat":1,"modu":"LORA","datr":"SF7BW125","codr":"4/5","lsnr":9,"rssi":-157,"size":23,"data":"AAAAAAAAAAAAjAgD/v9YF6hkWr13qj4="}]}
rxpk update: {"rxpk":[{"tmst":292138012,"chan":0,"rfch":0,"freq":868.100000,"stat":1,"modu":"LORA","datr":"SF7BW125","codr":"4/5","lsnr":10,"rssi":-62,"size":23,"data":"AAAAAAAAAAAAjAgD/v9YF6gTGRdKyxQ="}]}`

Gateway terminal output for ABP devices : 
`rxpk update: {"rxpk":[{"tmst":3856499572,"chan":0,"rfch":0,"freq":868.100000,"stat":1,"modu":"LORA","datr":"SF7BW125","codr":"4/5","lsnr":9,"rssi":-45,"size":18,"data":"QGQbASaAKAIBjmiyO+j+Cr9p"}]}
Packet RSSI: -53, RSSI: -103, SNR: 9, Length: 15
rxpk update: {"rxpk":[{"tmst":3875145659,"chan":0,"rfch":0,"freq":868.100000,"stat":1,"modu":"LORA","datr":"SF7BW125","codr":"4/5","lsnr":9,"rssi":-53,"size":15,"data":"QHgXASaA3RwBaDZQymv/"}]}`

**Comment by gotthardp** [comment]
Hello. If a gateway does not support downlinks I don't think it can support OTAA. The OTAA procedure requires a response to be sent from the server to the device. Or am I missing something?
