### ISSUE TITLE
Handlers shall allow enabling/disabling JSON elements

### ISSUE THREAD

**Issue by gotthardp** [gotthardp/lorawan-server#86]
Couple of JSON improvements:

Handler admin shall have checkboxes to enable/disable individual JSON elements. Requested by @Sviests in issue #79.

Handler shall (optionally) include DevEUI and gateway MAC in the JSON uplink data. Requested by @matiasz8 in issue #60 and by @DigitalPigeon in #92.

**Comment by Sviests** [comment]
Great news! Can`t wait for this to be implemented. Thanks!!

**Comment by DigitalPigeon** [comment]
As per my second comment in #92, could we also optionally include the mac (devEUI) in the JSON as well please?

**Comment by gotthardp** [comment]
@DigitalPigeon Yes. Will do.

**Comment by gotthardp** [comment]
I just implemented everything. Available now in the `master` branch. By the end of next week will be released as v0.4.5. Please give it a try!

**Comment by gotthardp** [comment]
Done in 0.4.5.
