### ISSUE TITLE
lorawan-daemon crashing

### ISSUE THREAD

**Issue by Sviests** [gotthardp/lorawan-server#93]
I am unable to launch the lorawan-daemon. I`ve been trying to add the lorawan-server.service  which uses the daemon and I`m always getting this crash. This happens when I launch the daemon manually also.

{{case_clause,{'EXIT',{function_clause,[{application_controller,'-check_conf/0-fun-0-',[[],[]],[{file,"application_controller.erl"},{line,1809}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{application_controller,check_conf,0,[{file,"application_controller.erl"},{line,1808}]},{application_controller,init,2,[{file,"application_controller.erl"},{line,485}]}]}}},[{application_controller,init,2,[{file,"application_controller.erl"},{line,485}]}]}
{"could not start kernel pid",application_controller,"{{case_clause,{'EXIT',{function_clause,[{application_controller,'-check_conf/0-fun-0-',[[],[]],[{file,\"application_controller.erl\"},{line,1809}]},{lists,foldl,3,[{file,\"lists.erl\"},{line,1263}]},{application_controller,check_conf,0,[{file,\"application_controller.erl\"},{line,1808}]},{application_controller,init,2,[{file,\"application_controller.erl\"},{line,485}]}]}}},[{application_controller,init,2,[{file,\"application_controller.erl\"},{line,485}]}]}"}
could not start kernel pid (application_controller) ({{case_clause,{'EXIT',{function_clause,[{application_controller,'-check_conf/0-fun-0-',[[],[]],[{file,"application_controller.erl"},{line,1809}]},{

**Comment by gotthardp** [comment]
What erlang version do you have?

**Comment by Sviests** [comment]
I have erlang version 19, which is needed for the current version of cowlib to build.

**Comment by gotthardp** [comment]
And you removed any traces of old releases? The thing is this appears to be an installation issue. The code crashing is not mine.

**Comment by Sviests** [comment]
I did have a problem with removing the old erlang packages. I will check again if I have removed everything properly. Thanks for the tip!

**Comment by Sviests** [comment]
After a full reinstall of all erlang packages it worked. Thanks for the help!

**Comment by gotthardp** [comment]
Cool. I am glad it works!
