### ISSUE TITLE
Scrip to decrypt Hex frames on the server

### ISSUE THREAD

**Issue by kazi93** [gotthardp/lorawan-server#95]
Hi currently i am decrypting the Hex frame by using the following:
http://string-functions.com/hex-string.aspx

For example: I am receiving 6869 in the Loraserver which is equivalent to "Hi". Is there any script that will convert multiple hex readings (from multiple nodes) and post it on the visualisation tool ( for example feeboard.io or initialstate or kibana or thingspeak ? ) ?

**Comment by gotthardp** [comment]
Such conversion is the purpose of Handlers. If you choose one (preferably open source and visually pleasing) I can help you with the integration.

**Comment by gotthardp** [comment]
Do you require further assistance on this?

**Comment by kazi93** [comment]
@gotthardp I have decided to go with ThingSpeak as we can use "MATLAB Analysis and Visualisation". Your guidance will be much appreciated. Thank you :)

Sensor node -> LoRaWAN gateway -> Lorawan-server -> ThingSpeak ?

**Comment by gotthardp** [comment]
Hello. It took some time, but I finally made something that *may* work. Please, try to follow the https://github.com/gotthardp/lorawan-server/blob/master/doc/Integration.md#mathworks-thingspeak guide, test and let me know the issues.

**Comment by kazi93** [comment]
@gotthardp Could you please take a look at the below settings on thingspeak and the loraserver. I must made some terrible mistake. I can see nothing on the visualisation tool.

<img width="583" alt="screen shot 2017-07-27 at 15 41 59" src="https://user-images.githubusercontent.com/18202431/28673446-d09107d0-72e2-11e7-8767-5b35cde1db92.png">
<img width="773" alt="screen shot 2017-07-27 at 15 42 16" src="https://user-images.githubusercontent.com/18202431/28673452-d4ad9450-72e2-11e7-943d-ad6013372475.png">
<img width="820" alt="screen shot 2017-07-27 at 15 42 34" src="https://user-images.githubusercontent.com/18202431/28673453-d4cb8d66-72e2-11e7-92ce-65a5c75afb84.png">

**Comment by kazi93** [comment]
@gotthardp I guess, I should explain a little bit more. Sensor with group name "arduino" configured with ABP method and the esm5k is configured with OTAA method. Sensor arduino only sending "Hi" and sensor esm5k is sending temperature value. Please guide me to config in thingspeak.com.  Let me know if you need more information. Thanks

**Comment by gotthardp** [comment]
Could you please let me know what is the server doing? Is there something in the logs? Is the server sending some HTTP request (you can check this via tcpdump or tshark)?

**Comment by kazi93** [comment]
Hi @gotthardp I have attached the pcap file. I am also trying to understand the file. Thank you
[file.pcap.zip](https://github.com/gotthardp/lorawan-server/files/1183007/file.pcap.zip)

**Comment by kazi93** [comment]
Little more info: 
root@vps433520:~# docker container ls
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                            NAMES
6eb9acad6429        gotthardp/lorawan-server:latest   "/bin/sh -c bin/lo..."   2 weeks ago         Up 2 weeks          0.0.0.0:1680->1680/udp, 0.0.0.0:8080->8080/tcp   lorawan

**Comment by kazi93** [comment]
However, I cannot find "Mnesia database and server logs" which I defined as /opt during configuration :(

**Comment by gotthardp** [comment]
Well, the .pcap file is empty. There is not much to understand about it. How did you create it?

**Comment by kazi93** [comment]
I captured it from the ubuntu terminal however the loraserver is running inside the docker. The server is receiving frames from 3 nodes and hosted in the VPS cloud. Is that a problem?

**Comment by gotthardp** [comment]
This doesn't seem to be a problem. I suspect you set a wrong interface for `sudo tcpdump -i eth0 -w file.pcap`. Shouldn't you use something else than eth0?

**Comment by kazi93** [comment]
@gotthardp Yes, you were right. As it is installed in docker therefore I have captured both docker0 and esn3 interface. Thanks again.
[docker0.pcap.zip](https://github.com/gotthardp/lorawan-server/files/1184955/docker0.pcap.zip)
[ens3.pcap.zip](https://github.com/gotthardp/lorawan-server/files/1184956/ens3.pcap.zip)

**Comment by gotthardp** [comment]
No MQTT communication in there, so we will need to find the server log. What was the `docker run` command you used to start the server?

**Comment by kazi93** [comment]
@gotthardp 
$ docker run lorawan
I have used the below documentation to install docker.

@https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04

**Comment by gotthardp** [comment]
I didn't find anything wrong in the configs you posted, but I see an error in how you run the docker: the `/path/to/local` shall point to your directory, so if you want to have logs in `/opt/lorawan` do `--volume /opt/lorawan:/storage`. The `/storage` has to be untouched.

**Comment by kazi93** [comment]
@gotthardp Do I need to reinstall it? or I can run the modified command again? Please suggest bit briefly. Thank you

**Comment by gotthardp** [comment]
I am not a docker expert, but I believe you have to stop and remove the old image and then start it using the new command. Unfortunately all your config in that image will be lost.

**Comment by kazi93** [comment]
@gotthardp reinstall the loraserver, receiving frames in the server too. Now, I have the log and Mnesia database too in the desired local folder. Thank you. Please take a look at the attached *pcap file. Please take a look at my arduino handler, am I doing some missconfig ?? I am only expecting a string from the arduino which is "Hi"
[Archive.zip](https://github.com/gotthardp/lorawan-server/files/1185138/Archive.zip)

**Comment by gotthardp** [comment]
Could you please share also the debug.log?

**Comment by kazi93** [comment]
@gotthardp Yes. Thank you
[Archive 2.zip](https://github.com/gotthardp/lorawan-server/files/1185156/Archive.2.zip)

**Comment by gotthardp** [comment]
The data you send don't match the Parse Uplink function you specified: the function expects the first byte in the application data indicates length of the frame. If this is not true you should modify the function, for example to:
```erlang
fun(_Port, Data) ->
  #{data => binary_to_list(Data)}
end.
```

**Comment by kazi93** [comment]
@gotthardp Thank you. I am just expecting "Hi" from the lorawan arduino node. Please have a look and suggest accordingly. I have already changed the above code, not helpful yet. 
<img width="746" alt="screen shot 2017-07-29 at 21 25 26" src="https://user-images.githubusercontent.com/18202431/28747689-528a9fe4-74a5-11e7-82bc-23fd123cea8a.png">
<img width="509" alt="screen shot 2017-07-29 at 21 25 49" src="https://user-images.githubusercontent.com/18202431/28747690-528bc9c8-74a5-11e7-8f45-919cd3d47d86.png">
<img width="1012" alt="screen shot 2017-07-29 at 21 26 14" src="https://user-images.githubusercontent.com/18202431/28747691-528cf79e-74a5-11e7-9a9d-dac6e7da6e91.png">
<img width="486" alt="screen shot 2017-07-29 at 21 27 48" src="https://user-images.githubusercontent.com/18202431/28747692-528fff02-74a5-11e7-9e50-b7d2a417db52.png">
<img width="992" alt="screen shot 2017-07-29 at 21 29 28" src="https://user-images.githubusercontent.com/18202431/28747693-5292eed8-74a5-11e7-90de-1571095f5265.png">
<img width="1118" alt="screen shot 2017-07-29 at 21 29 56" src="https://user-images.githubusercontent.com/18202431/28747694-52941d30-74a5-11e7-8804-cce629656e7f.png">

**Comment by gotthardp** [comment]
Please post the PCAP and server logs too. :-)

**Comment by kazi93** [comment]
@gotthardp I have been trying it since yesterday. It won't work! I must have been doing something wrong. As you can see I am just sending a string "Hi", I would like to print it in thingspeak. Thank you. Another sensor is also sending temperature and humidity data, if this is a success that supposed to work too. Thanks again for your kind support.  :)

**Comment by gotthardp** [comment]
Don't give up :) The Received Frames page shows "hello" as payload, so we are almost there. We fixed the parsing function, but there is apparently (at least) one more issue. The PCAP and debug.log will help finding the problem.

**Comment by kazi93** [comment]
@gotthardp Thank you. Yes, payload is "hello". :) I have attached both interface file docker0 and ens3 both. 
[debug.log.zip](https://github.com/gotthardp/lorawan-server/files/1185196/debug.log.zip)
[docker2.pcap.zip](https://github.com/gotthardp/lorawan-server/files/1185197/docker2.pcap.zip)
[ens4.pcap.zip](https://github.com/gotthardp/lorawan-server/files/1185198/ens4.pcap.zip)

**Comment by gotthardp** [comment]
Thanks. Now the ThingSpeak is refusing the connection. Could you please try switching to plain "mqtt"?

**Comment by kazi93** [comment]
@gotthardp Now switched to "mqtt://mqtt.thingspeak.com", however, no output. What should be in the thingspeak channel settings >>field 1, field 2, ....?
[ens5.pcap.zip](https://github.com/gotthardp/lorawan-server/files/1185236/ens5.pcap.zip)

**Comment by gotthardp** [comment]
I can see the MQTT Publish now. It contains "data=hello", so I recommend adding a field1 "data" and deleting every other fields (for now).

**Comment by kazi93** [comment]
@gotthardp I can see little update. Entries : 72 :) however, cannot see "Hello" yet. :) Changed the Field 1 : >> "data". Any suggestion? Almost there :P
<img width="1129" alt="screen shot 2017-07-29 at 23 09 36" src="https://user-images.githubusercontent.com/18202431/28748248-3b79addc-74b3-11e7-80e3-2d505a4debfd.png">

**Comment by gotthardp** [comment]
Are you sure that ThingSpeak handles also text data? The displayed chart with x-y axes looks like a numerical value was expect.

**Comment by kazi93** [comment]
@gotthardp I will do some research on this. However, I have another sensor that is OTTA configured and sending temp and humid as you can see below. It publish numerical values. :). Let us try. Many thanks for your kind support. I have changed the Field 1 >> Data too. But output is also null. :(
<img width="1002" alt="screen shot 2017-07-29 at 23 21 14" src="https://user-images.githubusercontent.com/18202431/28748323-09ad4104-74b5-11e7-8af5-2d35a659c3fc.png">
<img width="578" alt="screen shot 2017-07-29 at 23 24 44" src="https://user-images.githubusercontent.com/18202431/28748332-28dfba7a-74b5-11e7-9d60-9e983a91186d.png">

**Comment by gotthardp** [comment]
But you need to adapt also the Parse Uplink function so it sends some numerical data. You can follow the [Instructions](https://github.com/gotthardp/lorawan-server/blob/master/doc/Backends.md#parse-uplink) or describe the format here and I will suggest the parsing function.

**Comment by kazi93** [comment]
@gotthardp Thanks again for your kind support. I just went through the sensor documentation. It says something like below: Please help, cannot wait to see it is working with thingspeak :)

<img width="990" alt="screen shot 2017-07-29 at 23 50 50" src="https://user-images.githubusercontent.com/18202431/28748473-3b2e3ad6-74b9-11e7-9412-e9c67d322334.png">
<img width="998" alt="screen shot 2017-07-29 at 23 51 12" src="https://user-images.githubusercontent.com/18202431/28748474-3b31dd94-74b9-11e7-937b-dc4c2d4ea6d3.png">
<img width="964" alt="screen shot 2017-07-29 at 23 52 05" src="https://user-images.githubusercontent.com/18202431/28748475-3b33dca2-74b9-11e7-811f-ac98ba197b6c.png">

**Comment by gotthardp** [comment]
But how does `21BF120213` match the above description? Could you please help me decoding this?

**Comment by kazi93** [comment]
@gotthardp I will try to decode it but I am not an expert :( I think we only need to use the parsing function that should do the job. :) Btw. I have sent couple of email in your "@centrum.cz" address. Please inbox me. Many thanks :)

**Comment by gotthardp** [comment]
I can suggest the Erlang function for Uplink Parsing, but you need to figure out what means each byte in the message. Just read the device documentation and tell me the meaning of each byte in `21BF120213`, which is the message I see in Received Frames.

**Comment by kazi93** [comment]
I think it is written above shared documentation. Length is also defined. So, GPS and TEMP data.
<img width="445" alt="screen shot 2017-07-30 at 00 48 24" src="https://user-images.githubusercontent.com/18202431/28749251-6fe86a28-74c1-11e7-83e7-7d5530fd9357.png">

**Comment by gotthardp** [comment]
But the data I see you got are 3 or 5 bytes long. I don't see how the documentation you shared is matching the frames you are receiving.

**Comment by kazi93** [comment]
@gotthardp I have attached the payload decoding code. How could I use it to have sensor readings on thingspeak? I think script says everything. I am receiving data in the "Received Frames" :)
<img width="1015" alt="screen shot 2017-07-31 at 16 15 29" src="https://user-images.githubusercontent.com/18202431/28781791-8deed9e4-760b-11e7-96fe-09b855b03fcd.png">
[payload.txt.zip](https://github.com/gotthardp/lorawan-server/files/1187808/payload.txt.zip)

**Comment by gotthardp** [comment]
I see. For the data you are getting you can use the following function:
```erlang
fun(_Port, <<16#01, Temp:16/signed-integer, 16#07, VDD:16>>) ->
  #{temp => Temp, vdd => VDD}
end.
```
I hope it is pretty straightforward.

**Comment by kazi93** [comment]
@gotthardp Nothing happened. Even thought it is receiving entries in thingspeak. definitely missing something. 
<img width="1124" alt="screen shot 2017-08-01 at 02 21 20" src="https://user-images.githubusercontent.com/18202431/28803962-70693446-7660-11e7-8a3d-8a115e621238.png">
<img width="455" alt="screen shot 2017-08-01 at 02 21 43" src="https://user-images.githubusercontent.com/18202431/28803963-706d3d2a-7660-11e7-8741-422c45a67c2f.png">
<img width="631" alt="screen shot 2017-08-01 at 02 23 04" src="https://user-images.githubusercontent.com/18202431/28803964-7071086a-7660-11e7-8f8f-e0e5514d2e4d.png">

**Comment by gotthardp** [comment]
Are the names in thingspeak case sensitive? In the message they are all lowercase.

**Comment by kazi93** [comment]
@gotthardp I do not think so. I guess, it is a decoding problem. :(
<img width="1124" alt="screen shot 2017-08-01 at 02 21 20" src="https://user-images.githubusercontent.com/18202431/28826965-4f1a82ce-76cc-11e7-9d58-c9dd6157ae46.png">

**Comment by gotthardp** [comment]
Hi there! The trick is to use "fieldX" names, so the correct Parse Uplink function is:

```erlang
fun(_Port, <<16#01, Temp:16/signed-integer, 16#07, VDD:16>>) ->
  #{field1 => Temp, field2 => VDD}
end.
```

**Comment by kazi93** [comment]
@gotthardp I have gone through the Backends.md, and I have decided to learn erlang programming. However, now I only have a analog gas sensor which sending a decimal value of e.g 40 or 340 (depending on the density of gas). Below is the received frames in ASCII format and the sketch I have used. Please correct me if my parsing is wrong !!
<img width="974" alt="screen shot 2017-08-24 at 13 15 46" src="https://user-images.githubusercontent.com/18202431/29665487-89639e60-88d4-11e7-91b8-d8af430bc54c.png">

fun(_Port, <<16#01, message:16/signed-integer>>) ->
  #{message => message}
end.

**Comment by kazi93** [comment]
@using the same above code : DS18B20 TEMP sensor. Parsing is wrong as the thingspeak output is not the same as the serial output.
Parsing:
**fun(_Port, <<Temp, B>>) ->
  #{field1 => Temp}
end.**

<img width="358" alt="screen shot 2017-08-24 at 21 15 00" src="https://user-images.githubusercontent.com/18202431/29684460-5c032eca-8912-11e7-9f72-f6257ff8e3d3.png">

**Comment by gotthardp** [comment]
The parsing fun has to match the data. If you have a 2-byte value like 000C you can do
```erlang
fun(_Port, <<Val:16/signed-integer>>) ->
  #{field1 => Val}
end.
```

**Comment by kazi93** [comment]
@gotthardp I did it however, I think something is wrong with the my sketch as the serial output is just fine but the server ASCII is not, it is always the same 000C. :(

Note I have just modified SKETCH : @https://github.com/gonzalocasas/arduino-uno-dragino-lorawan/blob/master/send-sensor-data/send-sensor-data.ino and add the ds18b20 code.

What do you think about the analog gas sensor (A0) which also sending the decimal value to the server the parsing is okay? I cannot have any data in the thingspeak too.

fun(_Port, <<16#01, message:16/signed-integer>>) ->
#{message => message}
end.

**Comment by gotthardp** [comment]
The variables have to start with a capital letter, so it has to be:
```erlang
fun(_Port, <<Message:16/signed-integer>>) ->
    #{field1 => Message}
end.
```

**Comment by kazi93** [comment]
@gotthardp Many thanks. I have managed to get temp. from the ds18b20 sensor. Could you please help me to parsing it. I have tried and it did not work unfortunately due to my poor parsing knowledge. I have attached the sketch and rxframes. Thanks again. :)

<img width="980" alt="screen shot 2017-08-29 at 06 18 33" src="https://user-images.githubusercontent.com/18202431/29804546-8ea5017c-8c83-11e7-9cd3-a3427ddcfcb3.png">

[sketch.txt.zip](https://github.com/gotthardp/lorawan-server/files/1259103/sketch.txt.zip)

**Comment by gotthardp** [comment]
You should really learn more about Erlang binaries. It is not that hard.

As a first step you can try. It is just parsing 3-byte singned integer value. I have no clue if this is correct as I had no time to review the sketch.
```erlang
fun(_Port, <<Message:24/signed-integer>>) ->
    #{field1 => Message}
end.
```
